/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CampaignBase from './CampaignBase';
/**
 * The CampaignsListResponseBody model module.
 * @module model/CampaignsListResponseBody
 * @version 3.0.2
 */
class CampaignsListResponseBody {
    /**
     * Constructs a new <code>CampaignsListResponseBody</code>.
     * Schema model for **GET** &#x60;v1/campaigns&#x60;.
     * @alias CampaignsListResponseBody
     */
    constructor() { 
        
        CampaignsListResponseBody.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
        obj['object'] = 'list';
        obj['data_ref'] = 'campaigns';
    }

    /**
     * Constructs a <code>CampaignsListResponseBody</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Partial<CampaignsListResponseBody>} data The plain JavaScript object bearing properties of interest.
     * @param {CampaignsListResponseBody} [obj] Optional instance to populate.
     * @returns {CampaignsListResponseBody} The populated <code>CampaignsListResponseBody</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CampaignsListResponseBody();

            if (data.hasOwnProperty('object')) {
                obj['object'] = ApiClient.convertToType(data['object'], 'String');
            }
            if (data.hasOwnProperty('data_ref')) {
                obj['data_ref'] = ApiClient.convertToType(data['data_ref'], 'String');
            }
            if (data.hasOwnProperty('campaigns')) {
                obj['campaigns'] = ApiClient.convertToType(data['campaigns'], [CampaignBase]);
            }
            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CampaignsListResponseBody</code>.
     * @param {Partial<CampaignsListResponseBody>} data The plain JavaScript object bearing properties of interest.
     * @returns {boolean} to indicate whether the JSON data is valid with respect to <code>CampaignsListResponseBody</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['object'] && !(typeof data['object'] === 'string' || data['object'] instanceof String)) {
            throw new Error("Expected the field `object` to be a primitive type in the JSON string but got " + data['object']);
        }
        // ensure the json data is a string
        if (data['data_ref'] && !(typeof data['data_ref'] === 'string' || data['data_ref'] instanceof String)) {
            throw new Error("Expected the field `data_ref` to be a primitive type in the JSON string but got " + data['data_ref']);
        }
        if (data['campaigns']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['campaigns'])) {
                throw new Error("Expected the field `campaigns` to be an array in the JSON data but got " + data['campaigns']);
            }
            // validate the optional field `campaigns` (array)
            for (const item of data['campaigns']) {
                CampaignBase.validateJSON(item);
            };
        }

        return true;
    }


}



/**
    * The type of the object represented by JSON. This object stores information about campaigns in a dictionary.
    * @type {String | undefined}
    * @default 'list'
    */
CampaignsListResponseBody.prototype['object'] = 'list';

/**
    * Identifies the name of the attribute that contains the array of campaign objects.
    * @type {String | undefined}
    * @default 'campaigns'
    */
CampaignsListResponseBody.prototype['data_ref'] = 'campaigns';

/**
    * Contains array of campaign objects.
    * @type {Array.<CampaignBase> | undefined}
    */
CampaignsListResponseBody.prototype['campaigns'] = undefined;

/**
    * Total number of campaigns.
    * @type {Number | undefined}
    */
CampaignsListResponseBody.prototype['total'] = undefined;






export default CampaignsListResponseBody;

