/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ClientRedemptionsRedeemRequestBodyRedeemablesItemGift from './ClientRedemptionsRedeemRequestBodyRedeemablesItemGift';
import ClientRedemptionsRedeemRequestBodyRedeemablesItemReward from './ClientRedemptionsRedeemRequestBodyRedeemablesItemReward';
/**
 * The ClientRedemptionsRedeemRequestBodyRedeemablesItem model module.
 * @module model/ClientRedemptionsRedeemRequestBodyRedeemablesItem
 * @version 3.0.1
 */
class ClientRedemptionsRedeemRequestBodyRedeemablesItem {
    /**
     * Constructs a new <code>ClientRedemptionsRedeemRequestBodyRedeemablesItem</code>.
     * @alias ClientRedemptionsRedeemRequestBodyRedeemablesItem
     */
    constructor() { 
        
        ClientRedemptionsRedeemRequestBodyRedeemablesItem.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ClientRedemptionsRedeemRequestBodyRedeemablesItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Partial<ClientRedemptionsRedeemRequestBodyRedeemablesItem>} data The plain JavaScript object bearing properties of interest.
     * @param {ClientRedemptionsRedeemRequestBodyRedeemablesItem} [obj] Optional instance to populate.
     * @returns {ClientRedemptionsRedeemRequestBodyRedeemablesItem} The populated <code>ClientRedemptionsRedeemRequestBodyRedeemablesItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ClientRedemptionsRedeemRequestBodyRedeemablesItem();

            if (data.hasOwnProperty('object')) {
                obj['object'] = ApiClient.convertToType(data['object'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('gift')) {
                obj['gift'] = ClientRedemptionsRedeemRequestBodyRedeemablesItemGift.constructFromObject(data['gift']);
            }
            if (data.hasOwnProperty('reward')) {
                obj['reward'] = ClientRedemptionsRedeemRequestBodyRedeemablesItemReward.constructFromObject(data['reward']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ClientRedemptionsRedeemRequestBodyRedeemablesItem</code>.
     * @param {Partial<ClientRedemptionsRedeemRequestBodyRedeemablesItem>} data The plain JavaScript object bearing properties of interest.
     * @returns {boolean} to indicate whether the JSON data is valid with respect to <code>ClientRedemptionsRedeemRequestBodyRedeemablesItem</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['object'] && !(typeof data['object'] === 'string' || data['object'] instanceof String)) {
            throw new Error("Expected the field `object` to be a primitive type in the JSON string but got " + data['object']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // validate the optional field `gift`
        if (data['gift']) { // data not null
          ClientRedemptionsRedeemRequestBodyRedeemablesItemGift.validateJSON(data['gift']);
        }
        // validate the optional field `reward`
        if (data['reward']) { // data not null
          ClientRedemptionsRedeemRequestBodyRedeemablesItemReward.validateJSON(data['reward']);
        }

        return true;
    }


}



/**
    * @type {(keyof typeof ClientRedemptionsRedeemRequestBodyRedeemablesItem.ObjectEnum) | undefined}
    */
ClientRedemptionsRedeemRequestBodyRedeemablesItem.prototype['object'] = undefined;

/**
    * @type {String | undefined}
    */
ClientRedemptionsRedeemRequestBodyRedeemablesItem.prototype['id'] = undefined;

/**
    * @type {ClientRedemptionsRedeemRequestBodyRedeemablesItemGift | undefined}
    */
ClientRedemptionsRedeemRequestBodyRedeemablesItem.prototype['gift'] = undefined;

/**
    * @type {ClientRedemptionsRedeemRequestBodyRedeemablesItemReward | undefined}
    */
ClientRedemptionsRedeemRequestBodyRedeemablesItem.prototype['reward'] = undefined;





    /**
     * Allowed values for the <code>object</code> property.
     * @enum     {String}    
     * @readonly
     */
    ClientRedemptionsRedeemRequestBodyRedeemablesItem['ObjectEnum'] = {
    
        /**
         * value: "voucher"
         * @constant
         */
        "voucher": "voucher",
    
        /**
         * value: "promotion_tier"
         * @constant
         */
        "promotion_tier": "promotion_tier",
    
        /**
         * value: "promotion_stack"
         * @constant
         */
        "promotion_stack": "promotion_stack"    
    };



export default ClientRedemptionsRedeemRequestBodyRedeemablesItem;

