/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ClientValidationsValidateResponseBodyRedeemablesItemResultGift model module.
 * @module model/ClientValidationsValidateResponseBodyRedeemablesItemResultGift
 * @version 3.0.0
 */
class ClientValidationsValidateResponseBodyRedeemablesItemResultGift {
    /**
     * Constructs a new <code>ClientValidationsValidateResponseBodyRedeemablesItemResultGift</code>.
     * Stores the amount of gift card credits to be applied.
     * @alias module:model/ClientValidationsValidateResponseBodyRedeemablesItemResultGift
     */
    constructor() { 
        
        ClientValidationsValidateResponseBodyRedeemablesItemResultGift.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ClientValidationsValidateResponseBodyRedeemablesItemResultGift</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ClientValidationsValidateResponseBodyRedeemablesItemResultGift} obj Optional instance to populate.
     * @returns {module:model/ClientValidationsValidateResponseBodyRedeemablesItemResultGift} The populated <code>ClientValidationsValidateResponseBodyRedeemablesItemResultGift</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ClientValidationsValidateResponseBodyRedeemablesItemResultGift();

            if (data.hasOwnProperty('balance')) {
                obj['balance'] = ApiClient.convertToType(data['balance'], 'Number');
            }
            if (data.hasOwnProperty('credits')) {
                obj['credits'] = ApiClient.convertToType(data['credits'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ClientValidationsValidateResponseBodyRedeemablesItemResultGift</code>.
     * @param {object} data The plain JavaScript object bearing properties of interest.
     * @returns {boolean} to indicate whether the JSON data is valid with respect to <code>ClientValidationsValidateResponseBodyRedeemablesItemResultGift</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * Available funds at the moment of validation. The value is multiplied by 100 to represent 2 decimal places. For example `10000 cents` for `$100.00`.
 * @member {Number} 
 */
ClientValidationsValidateResponseBodyRedeemablesItemResultGift.prototype['balance'] = undefined;

/**
 * Total number of gift card credits to be applied. The value is multiplied by 100 to represent 2 decimal places. For example `10000 cents` for `$100.00`.
 * @member {Number} 
 */
ClientValidationsValidateResponseBodyRedeemablesItemResultGift.prototype['credits'] = undefined;






export default ClientValidationsValidateResponseBodyRedeemablesItemResultGift;

