/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CustomerActivity model module.
 * @module model/CustomerActivity
 * @version v2018-08-01
 */
class CustomerActivity {
    /**
     * Constructs a new <code>CustomerActivity</code>.
     * This is an object representing customer activity.    This is a general object which presents moments from customers&#39; activity. There are all types of different events that customers perform during their journey once they participate in Promotions. Events describe moments when customers redeem coupons and earn points or rewards. The list of all types of activities is listed below.  The details describing the activity are collected in a property named &#x60;data&#x60;. In this object, software integrators will find all further information explaining the event context.
     * @alias module:model/CustomerActivity
     */
    constructor() { 
        
        CustomerActivity.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CustomerActivity</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CustomerActivity} obj Optional instance to populate.
     * @return {module:model/CustomerActivity} The populated <code>CustomerActivity</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CustomerActivity();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], Object);
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('group_id')) {
                obj['group_id'] = ApiClient.convertToType(data['group_id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CustomerActivity</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CustomerActivity</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        // ensure the json data is a string
        if (data['group_id'] && !(typeof data['group_id'] === 'string' || data['group_id'] instanceof String)) {
            throw new Error("Expected the field `group_id` to be a primitive type in the JSON string but got " + data['group_id']);
        }

        return true;
    }


}



/**
 * Unique event ID, assigned by Voucherify.
 * @member {String} id
 */
CustomerActivity.prototype['id'] = undefined;

/**
 * Event type.
 * @member {module:model/CustomerActivity.TypeEnum} type
 */
CustomerActivity.prototype['type'] = undefined;

/**
 * Contains details about the event. The objects that are returned in the data attribute differ based on the context of the event type.
 * @member {Object} data
 */
CustomerActivity.prototype['data'] = undefined;

/**
 * Timestamp representing the date and time when the customer activity occurred in ISO 8601 format.
 * @member {Date} created_at
 */
CustomerActivity.prototype['created_at'] = undefined;

/**
 * Unique identifier of the request that caused the event.
 * @member {String} group_id
 */
CustomerActivity.prototype['group_id'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
CustomerActivity['TypeEnum'] = {

    /**
     * value: "customer.confirmed"
     * @const
     */
    "customer.confirmed": "customer.confirmed",

    /**
     * value: "customer.created"
     * @const
     */
    "customer.created": "customer.created",

    /**
     * value: "customer.updated"
     * @const
     */
    "customer.updated": "customer.updated",

    /**
     * value: "customer.deleted"
     * @const
     */
    "customer.deleted": "customer.deleted",

    /**
     * value: "customer.referred"
     * @const
     */
    "customer.referred": "customer.referred",

    /**
     * value: "customer.custom_event"
     * @const
     */
    "customer.custom_event": "customer.custom_event",

    /**
     * value: "customer.segment.entered"
     * @const
     */
    "customer.segment.entered": "customer.segment.entered",

    /**
     * value: "customer.segment.left"
     * @const
     */
    "customer.segment.left": "customer.segment.left",

    /**
     * value: "customer.sms.sent"
     * @const
     */
    "customer.sms.sent": "customer.sms.sent",

    /**
     * value: "customer.sms.recovered"
     * @const
     */
    "customer.sms.recovered": "customer.sms.recovered",

    /**
     * value: "customer.sms.failed"
     * @const
     */
    "customer.sms.failed": "customer.sms.failed",

    /**
     * value: "customer.email.sent"
     * @const
     */
    "customer.email.sent": "customer.email.sent",

    /**
     * value: "customer.email.recovered"
     * @const
     */
    "customer.email.recovered": "customer.email.recovered",

    /**
     * value: "customer.email.failed"
     * @const
     */
    "customer.email.failed": "customer.email.failed",

    /**
     * value: "customer.activecampaign.sent"
     * @const
     */
    "customer.activecampaign.sent": "customer.activecampaign.sent",

    /**
     * value: "customer.activecampaign.recovered"
     * @const
     */
    "customer.activecampaign.recovered": "customer.activecampaign.recovered",

    /**
     * value: "customer.activecampaign.failed"
     * @const
     */
    "customer.activecampaign.failed": "customer.activecampaign.failed",

    /**
     * value: "customer.braze.sent"
     * @const
     */
    "customer.braze.sent": "customer.braze.sent",

    /**
     * value: "customer.braze.recovered"
     * @const
     */
    "customer.braze.recovered": "customer.braze.recovered",

    /**
     * value: "customer.braze.failed"
     * @const
     */
    "customer.braze.failed": "customer.braze.failed",

    /**
     * value: "customer.mailchimp.sent"
     * @const
     */
    "customer.mailchimp.sent": "customer.mailchimp.sent",

    /**
     * value: "customer.mailchimp.recovered"
     * @const
     */
    "customer.mailchimp.recovered": "customer.mailchimp.recovered",

    /**
     * value: "customer.mailchimp.failed"
     * @const
     */
    "customer.mailchimp.failed": "customer.mailchimp.failed",

    /**
     * value: "customer.intercom.sent"
     * @const
     */
    "customer.intercom.sent": "customer.intercom.sent",

    /**
     * value: "customer.intercom.recovered"
     * @const
     */
    "customer.intercom.recovered": "customer.intercom.recovered",

    /**
     * value: "customer.intercom.failed"
     * @const
     */
    "customer.intercom.failed": "customer.intercom.failed",

    /**
     * value: "customer.shopify.sent"
     * @const
     */
    "customer.shopify.sent": "customer.shopify.sent",

    /**
     * value: "customer.shopify.recovered"
     * @const
     */
    "customer.shopify.recovered": "customer.shopify.recovered",

    /**
     * value: "customer.shopify.failed"
     * @const
     */
    "customer.shopify.failed": "customer.shopify.failed",

    /**
     * value: "customer.klaviyo.sent"
     * @const
     */
    "customer.klaviyo.sent": "customer.klaviyo.sent",

    /**
     * value: "customer.klaviyo.recovered"
     * @const
     */
    "customer.klaviyo.recovered": "customer.klaviyo.recovered",

    /**
     * value: "customer.klaviyo.failed"
     * @const
     */
    "customer.klaviyo.failed": "customer.klaviyo.failed",

    /**
     * value: "customer.batch.sent"
     * @const
     */
    "customer.batch.sent": "customer.batch.sent",

    /**
     * value: "customer.batch.recovered"
     * @const
     */
    "customer.batch.recovered": "customer.batch.recovered",

    /**
     * value: "customer.batch.failed"
     * @const
     */
    "customer.batch.failed": "customer.batch.failed",

    /**
     * value: "customer.rewarded"
     * @const
     */
    "customer.rewarded": "customer.rewarded",

    /**
     * value: "customer.rewarded.loyalty_points"
     * @const
     */
    "customer.rewarded.loyalty_points": "customer.rewarded.loyalty_points",

    /**
     * value: "customer.voucher.gift.balance_added"
     * @const
     */
    "customer.voucher.gift.balance_added": "customer.voucher.gift.balance_added",

    /**
     * value: "customer.voucher.loyalty_card.pending_points.activated"
     * @const
     */
    "customer.voucher.loyalty_card.pending_points.activated": "customer.voucher.loyalty_card.pending_points.activated",

    /**
     * value: "customer.voucher.loyalty_card.pending_points.added"
     * @const
     */
    "customer.voucher.loyalty_card.pending_points.added": "customer.voucher.loyalty_card.pending_points.added",

    /**
     * value: "customer.voucher.loyalty_card.pending_points.canceled"
     * @const
     */
    "customer.voucher.loyalty_card.pending_points.canceled": "customer.voucher.loyalty_card.pending_points.canceled",

    /**
     * value: "customer.voucher.loyalty_card.pending_points.updated"
     * @const
     */
    "customer.voucher.loyalty_card.pending_points.updated": "customer.voucher.loyalty_card.pending_points.updated",

    /**
     * value: "customer.voucher.loyalty_card.points_activated"
     * @const
     */
    "customer.voucher.loyalty_card.points_activated": "customer.voucher.loyalty_card.points_activated",

    /**
     * value: "customer.voucher.loyalty_card.points_added"
     * @const
     */
    "customer.voucher.loyalty_card.points_added": "customer.voucher.loyalty_card.points_added",

    /**
     * value: "customer.voucher.loyalty_card.points_transferred"
     * @const
     */
    "customer.voucher.loyalty_card.points_transferred": "customer.voucher.loyalty_card.points_transferred",

    /**
     * value: "customer.voucher.loyalty_card.points_expired"
     * @const
     */
    "customer.voucher.loyalty_card.points_expired": "customer.voucher.loyalty_card.points_expired",

    /**
     * value: "customer.voucher.deleted"
     * @const
     */
    "customer.voucher.deleted": "customer.voucher.deleted",

    /**
     * value: "customer.publication.succeeded"
     * @const
     */
    "customer.publication.succeeded": "customer.publication.succeeded",

    /**
     * value: "customer.publication.failed"
     * @const
     */
    "customer.publication.failed": "customer.publication.failed",

    /**
     * value: "customer.validation.succeeded"
     * @const
     */
    "customer.validation.succeeded": "customer.validation.succeeded",

    /**
     * value: "customer.validation.failed"
     * @const
     */
    "customer.validation.failed": "customer.validation.failed",

    /**
     * value: "customer.redemption.failed"
     * @const
     */
    "customer.redemption.failed": "customer.redemption.failed",

    /**
     * value: "customer.redemption.succeeded"
     * @const
     */
    "customer.redemption.succeeded": "customer.redemption.succeeded",

    /**
     * value: "customer.redemption.rollback.failed"
     * @const
     */
    "customer.redemption.rollback.failed": "customer.redemption.rollback.failed",

    /**
     * value: "customer.redemption.rollback.succeeded"
     * @const
     */
    "customer.redemption.rollback.succeeded": "customer.redemption.rollback.succeeded",

    /**
     * value: "customer.order.canceled"
     * @const
     */
    "customer.order.canceled": "customer.order.canceled",

    /**
     * value: "customer.order.created"
     * @const
     */
    "customer.order.created": "customer.order.created",

    /**
     * value: "customer.order.fulfilled"
     * @const
     */
    "customer.order.fulfilled": "customer.order.fulfilled",

    /**
     * value: "customer.order.paid"
     * @const
     */
    "customer.order.paid": "customer.order.paid",

    /**
     * value: "customer.order.processing"
     * @const
     */
    "customer.order.processing": "customer.order.processing",

    /**
     * value: "customer.order.updated"
     * @const
     */
    "customer.order.updated": "customer.order.updated",

    /**
     * value: "customer.reward_redemptions.created"
     * @const
     */
    "customer.reward_redemptions.created": "customer.reward_redemptions.created",

    /**
     * value: "customer.reward_redemptions.pending"
     * @const
     */
    "customer.reward_redemptions.pending": "customer.reward_redemptions.pending",

    /**
     * value: "customer.reward_redemptions.completed"
     * @const
     */
    "customer.reward_redemptions.completed": "customer.reward_redemptions.completed",

    /**
     * value: "customer.reward_redemptions.rolledback"
     * @const
     */
    "customer.reward_redemptions.rolledback": "customer.reward_redemptions.rolledback",

    /**
     * value: "customer.loyalty.updated"
     * @const
     */
    "customer.loyalty.updated": "customer.loyalty.updated",

    /**
     * value: "customer.loyalty.tier.upgraded"
     * @const
     */
    "customer.loyalty.tier.upgraded": "customer.loyalty.tier.upgraded",

    /**
     * value: "customer.loyalty.tier.downgraded"
     * @const
     */
    "customer.loyalty.tier.downgraded": "customer.loyalty.tier.downgraded",

    /**
     * value: "customer.loyalty.tier.prolonged"
     * @const
     */
    "customer.loyalty.tier.prolonged": "customer.loyalty.tier.prolonged",

    /**
     * value: "customer.loyalty.tier.expiration.changed"
     * @const
     */
    "customer.loyalty.tier.expiration.changed": "customer.loyalty.tier.expiration.changed",

    /**
     * value: "customer.loyalty.tier.joined"
     * @const
     */
    "customer.loyalty.tier.joined": "customer.loyalty.tier.joined",

    /**
     * value: "customer.loyalty.tier.left"
     * @const
     */
    "customer.loyalty.tier.left": "customer.loyalty.tier.left",

    /**
     * value: "customer.holder.assignment.created"
     * @const
     */
    "customer.holder.assignment.created": "customer.holder.assignment.created",

    /**
     * value: "customer.holder.assignment.deleted"
     * @const
     */
    "customer.holder.assignment.deleted": "customer.holder.assignment.deleted"
};



export default CustomerActivity;

