/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
 * The CustomersCreateResponseBodyAddress model module.
 * @module model/CustomersCreateResponseBodyAddress
 * @version 3.0.2
 */
class CustomersCreateResponseBodyAddress {
    /**
     * Constructs a new <code>CustomersCreateResponseBodyAddress</code>.
     * Customer&#39;s address.
     * @alias CustomersCreateResponseBodyAddress
     */
    constructor() { 
        
        CustomersCreateResponseBodyAddress.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CustomersCreateResponseBodyAddress</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Partial<CustomersCreateResponseBodyAddress>} data The plain JavaScript object bearing properties of interest.
     * @param {CustomersCreateResponseBodyAddress} [obj] Optional instance to populate.
     * @returns {CustomersCreateResponseBodyAddress} The populated <code>CustomersCreateResponseBodyAddress</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CustomersCreateResponseBodyAddress();

            if (data.hasOwnProperty('city')) {
                obj['city'] = ApiClient.convertToType(data['city'], 'String');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
            if (data.hasOwnProperty('line_1')) {
                obj['line_1'] = ApiClient.convertToType(data['line_1'], 'String');
            }
            if (data.hasOwnProperty('line_2')) {
                obj['line_2'] = ApiClient.convertToType(data['line_2'], 'String');
            }
            if (data.hasOwnProperty('country')) {
                obj['country'] = ApiClient.convertToType(data['country'], 'String');
            }
            if (data.hasOwnProperty('postal_code')) {
                obj['postal_code'] = ApiClient.convertToType(data['postal_code'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CustomersCreateResponseBodyAddress</code>.
     * @param {Partial<CustomersCreateResponseBodyAddress>} data The plain JavaScript object bearing properties of interest.
     * @returns {boolean} to indicate whether the JSON data is valid with respect to <code>CustomersCreateResponseBodyAddress</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['city'] && !(typeof data['city'] === 'string' || data['city'] instanceof String)) {
            throw new Error("Expected the field `city` to be a primitive type in the JSON string but got " + data['city']);
        }
        // ensure the json data is a string
        if (data['state'] && !(typeof data['state'] === 'string' || data['state'] instanceof String)) {
            throw new Error("Expected the field `state` to be a primitive type in the JSON string but got " + data['state']);
        }
        // ensure the json data is a string
        if (data['line_1'] && !(typeof data['line_1'] === 'string' || data['line_1'] instanceof String)) {
            throw new Error("Expected the field `line_1` to be a primitive type in the JSON string but got " + data['line_1']);
        }
        // ensure the json data is a string
        if (data['line_2'] && !(typeof data['line_2'] === 'string' || data['line_2'] instanceof String)) {
            throw new Error("Expected the field `line_2` to be a primitive type in the JSON string but got " + data['line_2']);
        }
        // ensure the json data is a string
        if (data['country'] && !(typeof data['country'] === 'string' || data['country'] instanceof String)) {
            throw new Error("Expected the field `country` to be a primitive type in the JSON string but got " + data['country']);
        }
        // ensure the json data is a string
        if (data['postal_code'] && !(typeof data['postal_code'] === 'string' || data['postal_code'] instanceof String)) {
            throw new Error("Expected the field `postal_code` to be a primitive type in the JSON string but got " + data['postal_code']);
        }

        return true;
    }


}



/**
    * City
    * @type {String | undefined}
    */
CustomersCreateResponseBodyAddress.prototype['city'] = undefined;

/**
    * State
    * @type {String | undefined}
    */
CustomersCreateResponseBodyAddress.prototype['state'] = undefined;

/**
    * First line of address.
    * @type {String | undefined}
    */
CustomersCreateResponseBodyAddress.prototype['line_1'] = undefined;

/**
    * Second line of address.
    * @type {String | undefined}
    */
CustomersCreateResponseBodyAddress.prototype['line_2'] = undefined;

/**
    * Country.
    * @type {String | undefined}
    */
CustomersCreateResponseBodyAddress.prototype['country'] = undefined;

/**
    * Postal code.
    * @type {String | undefined}
    */
CustomersCreateResponseBodyAddress.prototype['postal_code'] = undefined;






export default CustomersCreateResponseBodyAddress;

