/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
 * The CustomersUpdateResponseBodyAssets model module.
 * @module model/CustomersUpdateResponseBodyAssets
 * @version 3.0.2
 */
class CustomersUpdateResponseBodyAssets {
    /**
     * Constructs a new <code>CustomersUpdateResponseBodyAssets</code>.
     * Contains information about the customer&#39;s cockpit.
     * @alias CustomersUpdateResponseBodyAssets
     */
    constructor() { 
        
        CustomersUpdateResponseBodyAssets.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CustomersUpdateResponseBodyAssets</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Partial<CustomersUpdateResponseBodyAssets>} data The plain JavaScript object bearing properties of interest.
     * @param {CustomersUpdateResponseBodyAssets} [obj] Optional instance to populate.
     * @returns {CustomersUpdateResponseBodyAssets} The populated <code>CustomersUpdateResponseBodyAssets</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CustomersUpdateResponseBodyAssets();

            if (data.hasOwnProperty('cockpit_url')) {
                obj['cockpit_url'] = ApiClient.convertToType(data['cockpit_url'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CustomersUpdateResponseBodyAssets</code>.
     * @param {Partial<CustomersUpdateResponseBodyAssets>} data The plain JavaScript object bearing properties of interest.
     * @returns {boolean} to indicate whether the JSON data is valid with respect to <code>CustomersUpdateResponseBodyAssets</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['cockpit_url'] && !(typeof data['cockpit_url'] === 'string' || data['cockpit_url'] instanceof String)) {
            throw new Error("Expected the field `cockpit_url` to be a primitive type in the JSON string but got " + data['cockpit_url']);
        }

        return true;
    }


}



/**
    * Customer's cockpit URL address.
    * @type {String | undefined}
    */
CustomersUpdateResponseBodyAssets.prototype['cockpit_url'] = undefined;






export default CustomersUpdateResponseBodyAssets;

