/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ExportsCreateResponseBodyParameters from './ExportsCreateResponseBodyParameters';

/**
 * The ExportsCreateResponseBody model module.
 * @module model/ExportsCreateResponseBody
 * @version 3.0.0
 */
class ExportsCreateResponseBody {
    /**
     * Constructs a new <code>ExportsCreateResponseBody</code>.
     * @alias module:model/ExportsCreateResponseBody
     */
    constructor() { 
        
        ExportsCreateResponseBody.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
        obj['object'] = 'export';
        obj['status'] = 'SCHEDULED';
    }

    /**
     * Constructs a <code>ExportsCreateResponseBody</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ExportsCreateResponseBody} obj Optional instance to populate.
     * @returns {module:model/ExportsCreateResponseBody} The populated <code>ExportsCreateResponseBody</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ExportsCreateResponseBody();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('object')) {
                obj['object'] = ApiClient.convertToType(data['object'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('channel')) {
                obj['channel'] = ApiClient.convertToType(data['channel'], 'String');
            }
            if (data.hasOwnProperty('result')) {
                obj['result'] = ApiClient.convertToType(data['result'], Object);
            }
            if (data.hasOwnProperty('user_id')) {
                obj['user_id'] = ApiClient.convertToType(data['user_id'], 'String');
            }
            if (data.hasOwnProperty('exported_object')) {
                obj['exported_object'] = ApiClient.convertToType(data['exported_object'], 'String');
            }
            if (data.hasOwnProperty('parameters')) {
                obj['parameters'] = ExportsCreateResponseBodyParameters.constructFromObject(data['parameters']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ExportsCreateResponseBody</code>.
     * @param {object} data The plain JavaScript object bearing properties of interest.
     * @returns {boolean} to indicate whether the JSON data is valid with respect to <code>ExportsCreateResponseBody</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['object'] && !(typeof data['object'] === 'string' || data['object'] instanceof String)) {
            throw new Error("Expected the field `object` to be a primitive type in the JSON string but got " + data['object']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        // ensure the json data is a string
        if (data['channel'] && !(typeof data['channel'] === 'string' || data['channel'] instanceof String)) {
            throw new Error("Expected the field `channel` to be a primitive type in the JSON string but got " + data['channel']);
        }
        // ensure the json data is a string
        if (data['user_id'] && !(typeof data['user_id'] === 'string' || data['user_id'] instanceof String)) {
            throw new Error("Expected the field `user_id` to be a primitive type in the JSON string but got " + data['user_id']);
        }
        // ensure the json data is a string
        if (data['exported_object'] && !(typeof data['exported_object'] === 'string' || data['exported_object'] instanceof String)) {
            throw new Error("Expected the field `exported_object` to be a primitive type in the JSON string but got " + data['exported_object']);
        }
        // validate the optional field `parameters`
        if (data['parameters']) { // data not null
          ExportsCreateResponseBodyParameters.validateJSON(data['parameters']);
        }

        return true;
    }


}



/**
 * Unique export ID.
 * @member {String} 
 */
ExportsCreateResponseBody.prototype['id'] = undefined;

/**
 * The type of object being represented. This object stores information about the export.
 * @member {module:model/ExportsCreateResponseBody.ObjectEnum} 
 * @default 'export'
 */
ExportsCreateResponseBody.prototype['object'] = 'export';

/**
 * Timestamp representing the date and time when the export was scheduled in ISO 8601 format.
 * @member {Date} 
 */
ExportsCreateResponseBody.prototype['created_at'] = undefined;

/**
 * Status of the export. Informs you whether the export has already been completed, i.e. indicates whether the file containing the exported data has been generated.
 * @member {module:model/ExportsCreateResponseBody.StatusEnum} 
 * @default 'SCHEDULED'
 */
ExportsCreateResponseBody.prototype['status'] = 'SCHEDULED';

/**
 * The channel through which the export was triggered.
 * @member {String} 
 */
ExportsCreateResponseBody.prototype['channel'] = undefined;

/**
 * Contains the URL of the CSV file.
 * @member {Object} 
 */
ExportsCreateResponseBody.prototype['result'] = undefined;

/**
 * Identifies the specific user who initiated the export through the Voucherify Dashboard; returned when the channel value is WEBSITE.
 * @member {String} 
 */
ExportsCreateResponseBody.prototype['user_id'] = undefined;

/**
 * @member {module:model/ExportsCreateResponseBody.ExportedObjectEnum} 
 */
ExportsCreateResponseBody.prototype['exported_object'] = undefined;

/**
 * @member {module:model/ExportsCreateResponseBodyParameters} 
 */
ExportsCreateResponseBody.prototype['parameters'] = undefined;





/**
 * Allowed values for the <code>object</code> property.
 * @enum {String}
 * @readonly
 */
ExportsCreateResponseBody['ObjectEnum'] = {

    /**
     * value: "export"
     * @constant
     */
    "export": "export"
};


/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
ExportsCreateResponseBody['StatusEnum'] = {

    /**
     * value: "SCHEDULED"
     * @constant
     */
    "SCHEDULED": "SCHEDULED"
};


/**
 * Allowed values for the <code>exported_object</code> property.
 * @enum {String}
 * @readonly
 */
ExportsCreateResponseBody['ExportedObjectEnum'] = {

    /**
     * value: "voucher"
     * @constant
     */
    "voucher": "voucher",

    /**
     * value: "redemption"
     * @constant
     */
    "redemption": "redemption",

    /**
     * value: "customer"
     * @constant
     */
    "customer": "customer",

    /**
     * value: "publication"
     * @constant
     */
    "publication": "publication",

    /**
     * value: "order"
     * @constant
     */
    "order": "order",

    /**
     * value: "points_expiration"
     * @constant
     */
    "points_expiration": "points_expiration",

    /**
     * value: "voucher_transactions"
     * @constant
     */
    "voucher_transactions": "voucher_transactions"
};



export default ExportsCreateResponseBody;

