/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ExportsCreateRequestBodyParameters from './ExportsCreateRequestBodyParameters';
/**
 * The ExportsCreateRequestBody model module.
 * @module model/ExportsCreateRequestBody
 * @version 3.0.2
 */
class ExportsCreateRequestBody {
    /**
     * Constructs a new <code>ExportsCreateRequestBody</code>.
     * @alias ExportsCreateRequestBody
     */
    constructor() { 
        
        ExportsCreateRequestBody.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ExportsCreateRequestBody</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Partial<ExportsCreateRequestBody>} data The plain JavaScript object bearing properties of interest.
     * @param {ExportsCreateRequestBody} [obj] Optional instance to populate.
     * @returns {ExportsCreateRequestBody} The populated <code>ExportsCreateRequestBody</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ExportsCreateRequestBody();

            if (data.hasOwnProperty('exported_object')) {
                obj['exported_object'] = ApiClient.convertToType(data['exported_object'], 'String');
            }
            if (data.hasOwnProperty('parameters')) {
                obj['parameters'] = ExportsCreateRequestBodyParameters.constructFromObject(data['parameters']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ExportsCreateRequestBody</code>.
     * @param {Partial<ExportsCreateRequestBody>} data The plain JavaScript object bearing properties of interest.
     * @returns {boolean} to indicate whether the JSON data is valid with respect to <code>ExportsCreateRequestBody</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['exported_object'] && !(typeof data['exported_object'] === 'string' || data['exported_object'] instanceof String)) {
            throw new Error("Expected the field `exported_object` to be a primitive type in the JSON string but got " + data['exported_object']);
        }
        // validate the optional field `parameters`
        if (data['parameters']) { // data not null
          ExportsCreateRequestBodyParameters.validateJSON(data['parameters']);
        }

        return true;
    }


}



/**
    * @type {(keyof typeof ExportsCreateRequestBody.ExportedObjectEnum) | undefined}
    */
ExportsCreateRequestBody.prototype['exported_object'] = undefined;

/**
    * @type {ExportsCreateRequestBodyParameters | undefined}
    */
ExportsCreateRequestBody.prototype['parameters'] = undefined;





    /**
     * Allowed values for the <code>exported_object</code> property.
     * @enum     {String}    
     * @readonly
     */
    ExportsCreateRequestBody['ExportedObjectEnum'] = {
    
        /**
         * value: "voucher"
         * @constant
         */
        "voucher": "voucher",
    
        /**
         * value: "redemption"
         * @constant
         */
        "redemption": "redemption",
    
        /**
         * value: "customer"
         * @constant
         */
        "customer": "customer",
    
        /**
         * value: "publication"
         * @constant
         */
        "publication": "publication",
    
        /**
         * value: "order"
         * @constant
         */
        "order": "order",
    
        /**
         * value: "points_expiration"
         * @constant
         */
        "points_expiration": "points_expiration",
    
        /**
         * value: "voucher_transactions"
         * @constant
         */
        "voucher_transactions": "voucher_transactions"    
    };



export default ExportsCreateRequestBody;

