/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FiltersCondition model module.
 * @module model/FiltersCondition
 * @version v2018-08-01
 */
class FiltersCondition {
    /**
     * Constructs a new <code>FiltersCondition</code>.
     * @alias module:model/FiltersCondition
     */
    constructor() { 
        
        FiltersCondition.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>FiltersCondition</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FiltersCondition} obj Optional instance to populate.
     * @return {module:model/FiltersCondition} The populated <code>FiltersCondition</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FiltersCondition();

            if (data.hasOwnProperty('$in')) {
                obj['$in'] = ApiClient.convertToType(data['$in'], Object);
            }
            if (data.hasOwnProperty('$not_in')) {
                obj['$not_in'] = ApiClient.convertToType(data['$not_in'], Object);
            }
            if (data.hasOwnProperty('$is')) {
                obj['$is'] = ApiClient.convertToType(data['$is'], Object);
            }
            if (data.hasOwnProperty('$is_days_ago')) {
                obj['$is_days_ago'] = ApiClient.convertToType(data['$is_days_ago'], Object);
            }
            if (data.hasOwnProperty('$is_days_in_future')) {
                obj['$is_days_in_future'] = ApiClient.convertToType(data['$is_days_in_future'], Object);
            }
            if (data.hasOwnProperty('$is_not')) {
                obj['$is_not'] = ApiClient.convertToType(data['$is_not'], Object);
            }
            if (data.hasOwnProperty('$has_value')) {
                obj['$has_value'] = ApiClient.convertToType(data['$has_value'], Object);
            }
            if (data.hasOwnProperty('$is_unknown')) {
                obj['$is_unknown'] = ApiClient.convertToType(data['$is_unknown'], Object);
            }
            if (data.hasOwnProperty('$contains')) {
                obj['$contains'] = ApiClient.convertToType(data['$contains'], Object);
            }
            if (data.hasOwnProperty('$not_contain')) {
                obj['$not_contain'] = ApiClient.convertToType(data['$not_contain'], Object);
            }
            if (data.hasOwnProperty('$starts_with')) {
                obj['$starts_with'] = ApiClient.convertToType(data['$starts_with'], Object);
            }
            if (data.hasOwnProperty('$ends_with')) {
                obj['$ends_with'] = ApiClient.convertToType(data['$ends_with'], Object);
            }
            if (data.hasOwnProperty('$more_than')) {
                obj['$more_than'] = ApiClient.convertToType(data['$more_than'], Object);
            }
            if (data.hasOwnProperty('$less_than')) {
                obj['$less_than'] = ApiClient.convertToType(data['$less_than'], Object);
            }
            if (data.hasOwnProperty('$more_than_ago')) {
                obj['$more_than_ago'] = ApiClient.convertToType(data['$more_than_ago'], Object);
            }
            if (data.hasOwnProperty('$less_than_ago')) {
                obj['$less_than_ago'] = ApiClient.convertToType(data['$less_than_ago'], Object);
            }
            if (data.hasOwnProperty('$more_than_future')) {
                obj['$more_than_future'] = ApiClient.convertToType(data['$more_than_future'], Object);
            }
            if (data.hasOwnProperty('$less_than_future')) {
                obj['$less_than_future'] = ApiClient.convertToType(data['$less_than_future'], Object);
            }
            if (data.hasOwnProperty('$more_than_equal')) {
                obj['$more_than_equal'] = ApiClient.convertToType(data['$more_than_equal'], Object);
            }
            if (data.hasOwnProperty('$less_than_equal')) {
                obj['$less_than_equal'] = ApiClient.convertToType(data['$less_than_equal'], Object);
            }
            if (data.hasOwnProperty('$after')) {
                obj['$after'] = ApiClient.convertToType(data['$after'], Object);
            }
            if (data.hasOwnProperty('$before')) {
                obj['$before'] = ApiClient.convertToType(data['$before'], Object);
            }
            if (data.hasOwnProperty('$count')) {
                obj['$count'] = ApiClient.convertToType(data['$count'], Object);
            }
            if (data.hasOwnProperty('$count_less')) {
                obj['$count_less'] = ApiClient.convertToType(data['$count_less'], Object);
            }
            if (data.hasOwnProperty('$count_more')) {
                obj['$count_more'] = ApiClient.convertToType(data['$count_more'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>FiltersCondition</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>FiltersCondition</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Object} $in
 */
FiltersCondition.prototype['$in'] = undefined;

/**
 * @member {Object} $not_in
 */
FiltersCondition.prototype['$not_in'] = undefined;

/**
 * @member {Object} $is
 */
FiltersCondition.prototype['$is'] = undefined;

/**
 * @member {Object} $is_days_ago
 */
FiltersCondition.prototype['$is_days_ago'] = undefined;

/**
 * @member {Object} $is_days_in_future
 */
FiltersCondition.prototype['$is_days_in_future'] = undefined;

/**
 * @member {Object} $is_not
 */
FiltersCondition.prototype['$is_not'] = undefined;

/**
 * @member {Object} $has_value
 */
FiltersCondition.prototype['$has_value'] = undefined;

/**
 * @member {Object} $is_unknown
 */
FiltersCondition.prototype['$is_unknown'] = undefined;

/**
 * @member {Object} $contains
 */
FiltersCondition.prototype['$contains'] = undefined;

/**
 * @member {Object} $not_contain
 */
FiltersCondition.prototype['$not_contain'] = undefined;

/**
 * @member {Object} $starts_with
 */
FiltersCondition.prototype['$starts_with'] = undefined;

/**
 * @member {Object} $ends_with
 */
FiltersCondition.prototype['$ends_with'] = undefined;

/**
 * @member {Object} $more_than
 */
FiltersCondition.prototype['$more_than'] = undefined;

/**
 * @member {Object} $less_than
 */
FiltersCondition.prototype['$less_than'] = undefined;

/**
 * @member {Object} $more_than_ago
 */
FiltersCondition.prototype['$more_than_ago'] = undefined;

/**
 * @member {Object} $less_than_ago
 */
FiltersCondition.prototype['$less_than_ago'] = undefined;

/**
 * @member {Object} $more_than_future
 */
FiltersCondition.prototype['$more_than_future'] = undefined;

/**
 * @member {Object} $less_than_future
 */
FiltersCondition.prototype['$less_than_future'] = undefined;

/**
 * @member {Object} $more_than_equal
 */
FiltersCondition.prototype['$more_than_equal'] = undefined;

/**
 * @member {Object} $less_than_equal
 */
FiltersCondition.prototype['$less_than_equal'] = undefined;

/**
 * @member {Object} $after
 */
FiltersCondition.prototype['$after'] = undefined;

/**
 * @member {Object} $before
 */
FiltersCondition.prototype['$before'] = undefined;

/**
 * @member {Object} $count
 */
FiltersCondition.prototype['$count'] = undefined;

/**
 * @member {Object} $count_less
 */
FiltersCondition.prototype['$count_less'] = undefined;

/**
 * @member {Object} $count_more
 */
FiltersCondition.prototype['$count_more'] = undefined;






export default FiltersCondition;

