/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CustomerWithSummaryLoyaltyReferrals from './CustomerWithSummaryLoyaltyReferrals';
import ListPublicationsItemValidSingleVoucherMetadata from './ListPublicationsItemValidSingleVoucherMetadata';
import ListPublicationsItemVoucher from './ListPublicationsItemVoucher';

/**
 * The ListPublicationsItemValidSingleVoucher model module.
 * @module model/ListPublicationsItemValidSingleVoucher
 * @version 3.0.0
 */
class ListPublicationsItemValidSingleVoucher {
    /**
     * Constructs a new <code>ListPublicationsItemValidSingleVoucher</code>.
     * @alias module:model/ListPublicationsItemValidSingleVoucher
     */
    constructor() { 
        
        ListPublicationsItemValidSingleVoucher.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
        obj['object'] = 'publication';
        obj['result'] = 'SUCCESS';
    }

    /**
     * Constructs a <code>ListPublicationsItemValidSingleVoucher</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ListPublicationsItemValidSingleVoucher} obj Optional instance to populate.
     * @returns {module:model/ListPublicationsItemValidSingleVoucher} The populated <code>ListPublicationsItemValidSingleVoucher</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ListPublicationsItemValidSingleVoucher();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('object')) {
                obj['object'] = ApiClient.convertToType(data['object'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('customer_id')) {
                obj['customer_id'] = ApiClient.convertToType(data['customer_id'], 'String');
            }
            if (data.hasOwnProperty('tracking_id')) {
                obj['tracking_id'] = ApiClient.convertToType(data['tracking_id'], 'String');
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ListPublicationsItemValidSingleVoucherMetadata.constructFromObject(data['metadata']);
            }
            if (data.hasOwnProperty('channel')) {
                obj['channel'] = ApiClient.convertToType(data['channel'], 'String');
            }
            if (data.hasOwnProperty('source_id')) {
                obj['source_id'] = ApiClient.convertToType(data['source_id'], 'String');
            }
            if (data.hasOwnProperty('customer')) {
                obj['customer'] = CustomerWithSummaryLoyaltyReferrals.constructFromObject(data['customer']);
            }
            if (data.hasOwnProperty('vouchers')) {
                obj['vouchers'] = ApiClient.convertToType(data['vouchers'], ['String']);
            }
            if (data.hasOwnProperty('vouchers_id')) {
                obj['vouchers_id'] = ApiClient.convertToType(data['vouchers_id'], ['String']);
            }
            if (data.hasOwnProperty('result')) {
                obj['result'] = ApiClient.convertToType(data['result'], 'String');
            }
            if (data.hasOwnProperty('voucher')) {
                obj['voucher'] = ListPublicationsItemVoucher.constructFromObject(data['voucher']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ListPublicationsItemValidSingleVoucher</code>.
     * @param {object} data The plain JavaScript object bearing properties of interest.
     * @returns {boolean} to indicate whether the JSON data is valid with respect to <code>ListPublicationsItemValidSingleVoucher</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['object'] && !(typeof data['object'] === 'string' || data['object'] instanceof String)) {
            throw new Error("Expected the field `object` to be a primitive type in the JSON string but got " + data['object']);
        }
        // ensure the json data is a string
        if (data['customer_id'] && !(typeof data['customer_id'] === 'string' || data['customer_id'] instanceof String)) {
            throw new Error("Expected the field `customer_id` to be a primitive type in the JSON string but got " + data['customer_id']);
        }
        // ensure the json data is a string
        if (data['tracking_id'] && !(typeof data['tracking_id'] === 'string' || data['tracking_id'] instanceof String)) {
            throw new Error("Expected the field `tracking_id` to be a primitive type in the JSON string but got " + data['tracking_id']);
        }
        // validate the optional field `metadata`
        if (data['metadata']) { // data not null
          ListPublicationsItemValidSingleVoucherMetadata.validateJSON(data['metadata']);
        }
        // ensure the json data is a string
        if (data['channel'] && !(typeof data['channel'] === 'string' || data['channel'] instanceof String)) {
            throw new Error("Expected the field `channel` to be a primitive type in the JSON string but got " + data['channel']);
        }
        // ensure the json data is a string
        if (data['source_id'] && !(typeof data['source_id'] === 'string' || data['source_id'] instanceof String)) {
            throw new Error("Expected the field `source_id` to be a primitive type in the JSON string but got " + data['source_id']);
        }
        // validate the optional field `customer`
        if (data['customer']) { // data not null
          CustomerWithSummaryLoyaltyReferrals.validateJSON(data['customer']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['vouchers'])) {
            throw new Error("Expected the field `vouchers` to be an array in the JSON data but got " + data['vouchers']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['vouchers_id'])) {
            throw new Error("Expected the field `vouchers_id` to be an array in the JSON data but got " + data['vouchers_id']);
        }
        // ensure the json data is a string
        if (data['result'] && !(typeof data['result'] === 'string' || data['result'] instanceof String)) {
            throw new Error("Expected the field `result` to be a primitive type in the JSON string but got " + data['result']);
        }
        // validate the optional field `voucher`
        if (data['voucher']) { // data not null
          ListPublicationsItemVoucher.validateJSON(data['voucher']);
        }

        return true;
    }


}



/**
 * Unique publication ID, assigned by Voucherify.
 * @member {String} 
 */
ListPublicationsItemValidSingleVoucher.prototype['id'] = undefined;

/**
 * The type of the object represented by the JSON. This object stores information about the `publication`.
 * @member {module:model/ListPublicationsItemValidSingleVoucher.ObjectEnum} 
 * @default 'publication'
 */
ListPublicationsItemValidSingleVoucher.prototype['object'] = 'publication';

/**
 * Timestamp representing the date and time when the publication was created. The value is shown in the ISO 8601 format.
 * @member {Date} 
 */
ListPublicationsItemValidSingleVoucher.prototype['created_at'] = undefined;

/**
 * Unique customer ID of the customer receiving the publication.
 * @member {String} 
 */
ListPublicationsItemValidSingleVoucher.prototype['customer_id'] = undefined;

/**
 * Customer's `source_id`.
 * @member {String} 
 */
ListPublicationsItemValidSingleVoucher.prototype['tracking_id'] = undefined;

/**
 * @member {module:model/ListPublicationsItemValidSingleVoucherMetadata} 
 */
ListPublicationsItemValidSingleVoucher.prototype['metadata'] = undefined;

/**
 * How the publication was originated. It can be your own custom channel or an example value provided here.
 * @member {String} 
 */
ListPublicationsItemValidSingleVoucher.prototype['channel'] = undefined;

/**
 * The merchant's publication ID if it is different from the Voucherify publication ID. It's an optional tracking identifier of a publication. It is really useful in case of an integration between multiple systems. It can be a publication ID from a CRM system, database or 3rd-party service. 
 * @member {String} 
 */
ListPublicationsItemValidSingleVoucher.prototype['source_id'] = undefined;

/**
 * @member {module:model/CustomerWithSummaryLoyaltyReferrals} 
 */
ListPublicationsItemValidSingleVoucher.prototype['customer'] = undefined;

/**
 * Contains the voucher IDs that was assigned by Voucherify.
 * @member {Array.<String>} 
 */
ListPublicationsItemValidSingleVoucher.prototype['vouchers'] = undefined;

/**
 * Contains the unique internal voucher IDs that was assigned by Voucherify.
 * @member {Array.<String>} 
 */
ListPublicationsItemValidSingleVoucher.prototype['vouchers_id'] = undefined;

/**
 * Status of the publication attempt.
 * @member {module:model/ListPublicationsItemValidSingleVoucher.ResultEnum} 
 * @default 'SUCCESS'
 */
ListPublicationsItemValidSingleVoucher.prototype['result'] = 'SUCCESS';

/**
 * @member {module:model/ListPublicationsItemVoucher} 
 */
ListPublicationsItemValidSingleVoucher.prototype['voucher'] = undefined;





/**
 * Allowed values for the <code>object</code> property.
 * @enum {String}
 * @readonly
 */
ListPublicationsItemValidSingleVoucher['ObjectEnum'] = {

    /**
     * value: "publication"
     * @constant
     */
    "publication": "publication"
};


/**
 * Allowed values for the <code>result</code> property.
 * @enum {String}
 * @readonly
 */
ListPublicationsItemValidSingleVoucher['ResultEnum'] = {

    /**
     * value: "SUCCESS"
     * @constant
     */
    "SUCCESS": "SUCCESS"
};



export default ListPublicationsItemValidSingleVoucher;

