/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
 * The LoyaltyCampaignVoucherRedemption model module.
 * @module model/LoyaltyCampaignVoucherRedemption
 * @version 3.0.2
 */
class LoyaltyCampaignVoucherRedemption {
    /**
     * Constructs a new <code>LoyaltyCampaignVoucherRedemption</code>.
     * Defines the redemption limits on vouchers.
     * @alias LoyaltyCampaignVoucherRedemption
     */
    constructor() { 
        
        LoyaltyCampaignVoucherRedemption.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LoyaltyCampaignVoucherRedemption</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Partial<LoyaltyCampaignVoucherRedemption>} data The plain JavaScript object bearing properties of interest.
     * @param {LoyaltyCampaignVoucherRedemption} [obj] Optional instance to populate.
     * @returns {LoyaltyCampaignVoucherRedemption} The populated <code>LoyaltyCampaignVoucherRedemption</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LoyaltyCampaignVoucherRedemption();

            if (data.hasOwnProperty('quantity')) {
                obj['quantity'] = ApiClient.convertToType(data['quantity'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>LoyaltyCampaignVoucherRedemption</code>.
     * @param {Partial<LoyaltyCampaignVoucherRedemption>} data The plain JavaScript object bearing properties of interest.
     * @returns {boolean} to indicate whether the JSON data is valid with respect to <code>LoyaltyCampaignVoucherRedemption</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
    * How many times a voucher can be redeemed. A `null` value means unlimited.
    * @type {Number | undefined}
    */
LoyaltyCampaignVoucherRedemption.prototype['quantity'] = undefined;






export default LoyaltyCampaignVoucherRedemption;

