/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EventSource from './EventSource';
/**
 * The LoyaltyPendingPointsDetailsEvent model module.
 * @module model/LoyaltyPendingPointsDetailsEvent
 * @version 3.0.1
 */
class LoyaltyPendingPointsDetailsEvent {
    /**
     * Constructs a new <code>LoyaltyPendingPointsDetailsEvent</code>.
     * Details about the event that created pending points.
     * @alias LoyaltyPendingPointsDetailsEvent
     */
    constructor() { 
        
        LoyaltyPendingPointsDetailsEvent.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
        obj['type'] = 'customer.order.paid';
    }

    /**
     * Constructs a <code>LoyaltyPendingPointsDetailsEvent</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Partial<LoyaltyPendingPointsDetailsEvent>} data The plain JavaScript object bearing properties of interest.
     * @param {LoyaltyPendingPointsDetailsEvent} [obj] Optional instance to populate.
     * @returns {LoyaltyPendingPointsDetailsEvent} The populated <code>LoyaltyPendingPointsDetailsEvent</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LoyaltyPendingPointsDetailsEvent();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('group_id')) {
                obj['group_id'] = ApiClient.convertToType(data['group_id'], 'String');
            }
            if (data.hasOwnProperty('entity_id')) {
                obj['entity_id'] = ApiClient.convertToType(data['entity_id'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('category')) {
                obj['category'] = ApiClient.convertToType(data['category'], 'String');
            }
            if (data.hasOwnProperty('event_source')) {
                obj['event_source'] = EventSource.constructFromObject(data['event_source']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>LoyaltyPendingPointsDetailsEvent</code>.
     * @param {Partial<LoyaltyPendingPointsDetailsEvent>} data The plain JavaScript object bearing properties of interest.
     * @returns {boolean} to indicate whether the JSON data is valid with respect to <code>LoyaltyPendingPointsDetailsEvent</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        // ensure the json data is a string
        if (data['group_id'] && !(typeof data['group_id'] === 'string' || data['group_id'] instanceof String)) {
            throw new Error("Expected the field `group_id` to be a primitive type in the JSON string but got " + data['group_id']);
        }
        // ensure the json data is a string
        if (data['entity_id'] && !(typeof data['entity_id'] === 'string' || data['entity_id'] instanceof String)) {
            throw new Error("Expected the field `entity_id` to be a primitive type in the JSON string but got " + data['entity_id']);
        }
        // ensure the json data is a string
        if (data['category'] && !(typeof data['category'] === 'string' || data['category'] instanceof String)) {
            throw new Error("Expected the field `category` to be a primitive type in the JSON string but got " + data['category']);
        }
        // validate the optional field `event_source`
        if (data['event_source']) { // data not null
          EventSource.validateJSON(data['event_source']);
        }

        return true;
    }


}



/**
    * Unique event identifier, assigned by Voucherify.
    * @type {String | undefined}
    */
LoyaltyPendingPointsDetailsEvent.prototype['id'] = undefined;

/**
    * Type of the event that triggered the creation of pending points.
    * @type {(keyof typeof LoyaltyPendingPointsDetailsEvent.TypeEnum) | undefined}
    * @default 'customer.order.paid'
    */
LoyaltyPendingPointsDetailsEvent.prototype['type'] = 'customer.order.paid';

/**
    * Unique identifier of the request that triggered the event, assigned by Voucherify.
    * @type {String | undefined}
    */
LoyaltyPendingPointsDetailsEvent.prototype['group_id'] = undefined;

/**
    * Unique identifier of the entity that triggered the event, assigned by Voucherify. For pending points, it is the `customer_id` of the customer who paid for the order.
    * @type {String | undefined}
    */
LoyaltyPendingPointsDetailsEvent.prototype['entity_id'] = undefined;

/**
    * Timestamp representing the date and time when the event occurred. The value is shown in the ISO 8601 format.
    * @type {Date | undefined}
    */
LoyaltyPendingPointsDetailsEvent.prototype['created_at'] = undefined;

/**
    * Type of the event.
    * @type {(keyof typeof LoyaltyPendingPointsDetailsEvent.CategoryEnum) | undefined}
    */
LoyaltyPendingPointsDetailsEvent.prototype['category'] = undefined;

/**
    * @type {EventSource | undefined}
    */
LoyaltyPendingPointsDetailsEvent.prototype['event_source'] = undefined;





    /**
     * Allowed values for the <code>type</code> property.
     * @enum     {String}    
     * @readonly
     */
    LoyaltyPendingPointsDetailsEvent['TypeEnum'] = {
    
        /**
         * value: "customer.order.paid"
         * @constant
         */
        "customer.order.paid": "customer.order.paid"    
    };


    /**
     * Allowed values for the <code>category</code> property.
     * @enum     {String}    
     * @readonly
     */
    LoyaltyPendingPointsDetailsEvent['CategoryEnum'] = {
    
        /**
         * value: "ACTION"
         * @constant
         */
        "ACTION": "ACTION",
    
        /**
         * value: "EFFECT"
         * @constant
         */
        "EFFECT": "EFFECT"    
    };



export default LoyaltyPendingPointsDetailsEvent;

