/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LoyaltiesTiersGetResponseBodyConfigPoints model module.
 * @module model/LoyaltiesTiersGetResponseBodyConfigPoints
 * @version 3.0.0
 */
class LoyaltiesTiersGetResponseBodyConfigPoints {
    /**
     * Constructs a new <code>LoyaltiesTiersGetResponseBodyConfigPoints</code>.
     * Defines range of loyalty tier in points.
     * @alias module:model/LoyaltiesTiersGetResponseBodyConfigPoints
     */
    constructor() { 
        
        LoyaltiesTiersGetResponseBodyConfigPoints.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LoyaltiesTiersGetResponseBodyConfigPoints</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LoyaltiesTiersGetResponseBodyConfigPoints} obj Optional instance to populate.
     * @returns {module:model/LoyaltiesTiersGetResponseBodyConfigPoints} The populated <code>LoyaltiesTiersGetResponseBodyConfigPoints</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LoyaltiesTiersGetResponseBodyConfigPoints();

            if (data.hasOwnProperty('from')) {
                obj['from'] = ApiClient.convertToType(data['from'], 'Number');
            }
            if (data.hasOwnProperty('to')) {
                obj['to'] = ApiClient.convertToType(data['to'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>LoyaltiesTiersGetResponseBodyConfigPoints</code>.
     * @param {object} data The plain JavaScript object bearing properties of interest.
     * @returns {boolean} to indicate whether the JSON data is valid with respect to <code>LoyaltiesTiersGetResponseBodyConfigPoints</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * Bottom points threshold value.
 * @member {Number} 
 */
LoyaltiesTiersGetResponseBodyConfigPoints.prototype['from'] = undefined;

/**
 * Top points threshold value.
 * @member {Number} 
 */
LoyaltiesTiersGetResponseBodyConfigPoints.prototype['to'] = undefined;






export default LoyaltiesTiersGetResponseBodyConfigPoints;

