/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EarningRuleExpirationRules from './EarningRuleExpirationRules';
import LoyaltiesEarningRulesDisableResponseBodyCustomEvent from './LoyaltiesEarningRulesDisableResponseBodyCustomEvent';
import LoyaltiesEarningRulesDisableResponseBodyLoyalty from './LoyaltiesEarningRulesDisableResponseBodyLoyalty';
import LoyaltiesEarningRulesDisableResponseBodyLoyaltyTier from './LoyaltiesEarningRulesDisableResponseBodyLoyaltyTier';
import LoyaltiesEarningRulesDisableResponseBodyPendingPoints from './LoyaltiesEarningRulesDisableResponseBodyPendingPoints';
import LoyaltiesEarningRulesDisableResponseBodySegment from './LoyaltiesEarningRulesDisableResponseBodySegment';
import LoyaltiesEarningRulesDisableResponseBodySource from './LoyaltiesEarningRulesDisableResponseBodySource';
import ValidityHours from './ValidityHours';
import ValidityTimeframe from './ValidityTimeframe';
/**
 * The LoyaltiesEarningRulesDisableResponseBody model module.
 * @module model/LoyaltiesEarningRulesDisableResponseBody
 * @version 3.0.2
 */
class LoyaltiesEarningRulesDisableResponseBody {
    /**
     * Constructs a new <code>LoyaltiesEarningRulesDisableResponseBody</code>.
     * Response body schema for **POST** &#x60;v1/loyalties/{campaignId}/earning-rules/{earningRuleId}/disable&#x60;
     * @alias LoyaltiesEarningRulesDisableResponseBody
     */
    constructor() { 
        
        LoyaltiesEarningRulesDisableResponseBody.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
        obj['object'] = 'earning_rule';
        obj['active'] = false;
    }

    /**
     * Constructs a <code>LoyaltiesEarningRulesDisableResponseBody</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Partial<LoyaltiesEarningRulesDisableResponseBody>} data The plain JavaScript object bearing properties of interest.
     * @param {LoyaltiesEarningRulesDisableResponseBody} [obj] Optional instance to populate.
     * @returns {LoyaltiesEarningRulesDisableResponseBody} The populated <code>LoyaltiesEarningRulesDisableResponseBody</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LoyaltiesEarningRulesDisableResponseBody();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('loyalty')) {
                obj['loyalty'] = LoyaltiesEarningRulesDisableResponseBodyLoyalty.constructFromObject(data['loyalty']);
            }
            if (data.hasOwnProperty('event')) {
                obj['event'] = ApiClient.convertToType(data['event'], 'String');
            }
            if (data.hasOwnProperty('custom_event')) {
                obj['custom_event'] = LoyaltiesEarningRulesDisableResponseBodyCustomEvent.constructFromObject(data['custom_event']);
            }
            if (data.hasOwnProperty('segment')) {
                obj['segment'] = LoyaltiesEarningRulesDisableResponseBodySegment.constructFromObject(data['segment']);
            }
            if (data.hasOwnProperty('loyalty_tier')) {
                obj['loyalty_tier'] = LoyaltiesEarningRulesDisableResponseBodyLoyaltyTier.constructFromObject(data['loyalty_tier']);
            }
            if (data.hasOwnProperty('pending_points')) {
                obj['pending_points'] = LoyaltiesEarningRulesDisableResponseBodyPendingPoints.constructFromObject(data['pending_points']);
            }
            if (data.hasOwnProperty('source')) {
                obj['source'] = LoyaltiesEarningRulesDisableResponseBodySource.constructFromObject(data['source']);
            }
            if (data.hasOwnProperty('object')) {
                obj['object'] = ApiClient.convertToType(data['object'], 'String');
            }
            if (data.hasOwnProperty('automation_id')) {
                obj['automation_id'] = ApiClient.convertToType(data['automation_id'], 'String');
            }
            if (data.hasOwnProperty('start_date')) {
                obj['start_date'] = ApiClient.convertToType(data['start_date'], 'String');
            }
            if (data.hasOwnProperty('expiration_date')) {
                obj['expiration_date'] = ApiClient.convertToType(data['expiration_date'], 'String');
            }
            if (data.hasOwnProperty('validity_timeframe')) {
                obj['validity_timeframe'] = ValidityTimeframe.constructFromObject(data['validity_timeframe']);
            }
            if (data.hasOwnProperty('validity_day_of_week')) {
                obj['validity_day_of_week'] = ApiClient.convertToType(data['validity_day_of_week'], ['Number']);
            }
            if (data.hasOwnProperty('validity_hours')) {
                obj['validity_hours'] = ValidityHours.constructFromObject(data['validity_hours']);
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], Object);
            }
            if (data.hasOwnProperty('expiration_rules')) {
                obj['expiration_rules'] = EarningRuleExpirationRules.constructFromObject(data['expiration_rules']);
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
            if (data.hasOwnProperty('active')) {
                obj['active'] = ApiClient.convertToType(data['active'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>LoyaltiesEarningRulesDisableResponseBody</code>.
     * @param {Partial<LoyaltiesEarningRulesDisableResponseBody>} data The plain JavaScript object bearing properties of interest.
     * @returns {boolean} to indicate whether the JSON data is valid with respect to <code>LoyaltiesEarningRulesDisableResponseBody</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // validate the optional field `loyalty`
        if (data['loyalty']) { // data not null
          LoyaltiesEarningRulesDisableResponseBodyLoyalty.validateJSON(data['loyalty']);
        }
        // ensure the json data is a string
        if (data['event'] && !(typeof data['event'] === 'string' || data['event'] instanceof String)) {
            throw new Error("Expected the field `event` to be a primitive type in the JSON string but got " + data['event']);
        }
        // validate the optional field `custom_event`
        if (data['custom_event']) { // data not null
          LoyaltiesEarningRulesDisableResponseBodyCustomEvent.validateJSON(data['custom_event']);
        }
        // validate the optional field `segment`
        if (data['segment']) { // data not null
          LoyaltiesEarningRulesDisableResponseBodySegment.validateJSON(data['segment']);
        }
        // validate the optional field `loyalty_tier`
        if (data['loyalty_tier']) { // data not null
          LoyaltiesEarningRulesDisableResponseBodyLoyaltyTier.validateJSON(data['loyalty_tier']);
        }
        // validate the optional field `pending_points`
        if (data['pending_points']) { // data not null
          LoyaltiesEarningRulesDisableResponseBodyPendingPoints.validateJSON(data['pending_points']);
        }
        // validate the optional field `source`
        if (data['source']) { // data not null
          LoyaltiesEarningRulesDisableResponseBodySource.validateJSON(data['source']);
        }
        // ensure the json data is a string
        if (data['object'] && !(typeof data['object'] === 'string' || data['object'] instanceof String)) {
            throw new Error("Expected the field `object` to be a primitive type in the JSON string but got " + data['object']);
        }
        // ensure the json data is a string
        if (data['automation_id'] && !(typeof data['automation_id'] === 'string' || data['automation_id'] instanceof String)) {
            throw new Error("Expected the field `automation_id` to be a primitive type in the JSON string but got " + data['automation_id']);
        }
        // ensure the json data is a string
        if (data['start_date'] && !(typeof data['start_date'] === 'string' || data['start_date'] instanceof String)) {
            throw new Error("Expected the field `start_date` to be a primitive type in the JSON string but got " + data['start_date']);
        }
        // ensure the json data is a string
        if (data['expiration_date'] && !(typeof data['expiration_date'] === 'string' || data['expiration_date'] instanceof String)) {
            throw new Error("Expected the field `expiration_date` to be a primitive type in the JSON string but got " + data['expiration_date']);
        }
        // validate the optional field `validity_timeframe`
        if (data['validity_timeframe']) { // data not null
          ValidityTimeframe.validateJSON(data['validity_timeframe']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['validity_day_of_week'])) {
            throw new Error("Expected the field `validity_day_of_week` to be an array in the JSON data but got " + data['validity_day_of_week']);
        }
        // validate the optional field `validity_hours`
        if (data['validity_hours']) { // data not null
          ValidityHours.validateJSON(data['validity_hours']);
        }
        // validate the optional field `expiration_rules`
        if (data['expiration_rules']) { // data not null
          EarningRuleExpirationRules.validateJSON(data['expiration_rules']);
        }

        return true;
    }


}



/**
    * Assigned by the Voucherify API, identifies the earning rule object.
    * @type {String | undefined}
    */
LoyaltiesEarningRulesDisableResponseBody.prototype['id'] = undefined;

/**
    * Timestamp representing the date and time when the earning rule was created. The value is shown in the ISO 8601 format.
    * @type {Date | undefined}
    */
LoyaltiesEarningRulesDisableResponseBody.prototype['created_at'] = undefined;

/**
    * @type {LoyaltiesEarningRulesDisableResponseBodyLoyalty | undefined}
    */
LoyaltiesEarningRulesDisableResponseBody.prototype['loyalty'] = undefined;

/**
    * @type {String | undefined}
    */
LoyaltiesEarningRulesDisableResponseBody.prototype['event'] = undefined;

/**
    * @type {LoyaltiesEarningRulesDisableResponseBodyCustomEvent | undefined}
    */
LoyaltiesEarningRulesDisableResponseBody.prototype['custom_event'] = undefined;

/**
    * @type {LoyaltiesEarningRulesDisableResponseBodySegment | undefined}
    */
LoyaltiesEarningRulesDisableResponseBody.prototype['segment'] = undefined;

/**
    * @type {LoyaltiesEarningRulesDisableResponseBodyLoyaltyTier | undefined}
    */
LoyaltiesEarningRulesDisableResponseBody.prototype['loyalty_tier'] = undefined;

/**
    * @type {LoyaltiesEarningRulesDisableResponseBodyPendingPoints | undefined}
    */
LoyaltiesEarningRulesDisableResponseBody.prototype['pending_points'] = undefined;

/**
    * @type {LoyaltiesEarningRulesDisableResponseBodySource | undefined}
    */
LoyaltiesEarningRulesDisableResponseBody.prototype['source'] = undefined;

/**
    * The type of the object represented by JSON. Default is earning_rule.
    * @type {(keyof typeof LoyaltiesEarningRulesDisableResponseBody.ObjectEnum) | undefined}
    * @default 'earning_rule'
    */
LoyaltiesEarningRulesDisableResponseBody.prototype['object'] = 'earning_rule';

/**
    * For internal use by Voucherify.
    * @type {String | undefined}
    */
LoyaltiesEarningRulesDisableResponseBody.prototype['automation_id'] = undefined;

/**
    * Start date defines when the earning rule starts to be active. Activation timestamp is presented in the ISO 8601 format. The earning rule is inactive before this date. If you do not define the start date for an earning rule, it will inherit the campaign start date by default.
    * @type {String | undefined}
    */
LoyaltiesEarningRulesDisableResponseBody.prototype['start_date'] = undefined;

/**
    * Expiration date defines when the earning rule expires. Expiration timestamp is presented in the ISO 8601 format. The earning rule is inactive after this date. If you do not define the expiration date for an earning rule, it will inherit the campaign expiration date by default.
    * @type {String | undefined}
    */
LoyaltiesEarningRulesDisableResponseBody.prototype['expiration_date'] = undefined;

/**
    * @type {ValidityTimeframe | undefined}
    */
LoyaltiesEarningRulesDisableResponseBody.prototype['validity_timeframe'] = undefined;

/**
    * Integer array corresponding to the particular days of the week in which the voucher is valid.  - `0` Sunday - `1` Monday - `2` Tuesday - `3` Wednesday - `4` Thursday - `5` Friday - `6` Saturday
    * @type {(Array<keyof typeof LoyaltiesEarningRulesDisableResponseBody.ValidityDayOfWeekEnum>) | undefined}
    */
LoyaltiesEarningRulesDisableResponseBody.prototype['validity_day_of_week'] = undefined;

/**
    * @type {ValidityHours | undefined}
    */
LoyaltiesEarningRulesDisableResponseBody.prototype['validity_hours'] = undefined;

/**
    * The metadata object stores all custom attributes assigned to the earning rule. A set of key/value pairs that you can attach to an earning rule object. It can be useful for storing additional information about the earning rule in a structured format.
    * @type {Object | undefined}
    */
LoyaltiesEarningRulesDisableResponseBody.prototype['metadata'] = undefined;

/**
    * @type {EarningRuleExpirationRules | undefined}
    */
LoyaltiesEarningRulesDisableResponseBody.prototype['expiration_rules'] = undefined;

/**
    * Timestamp representing the date and time when the earning rule was last updated in ISO 8601 format.
    * @type {Date | undefined}
    */
LoyaltiesEarningRulesDisableResponseBody.prototype['updated_at'] = undefined;

/**
    * A flag to toggle the earning rule on or off. You can disable an earning rule even though it's within the active period defined by the start_date and expiration_date of the campaign or the earning rule's own start_date and expiration_date.
    * @type {Boolean | undefined}
    * @default false
    */
LoyaltiesEarningRulesDisableResponseBody.prototype['active'] = false;





    /**
     * Allowed values for the <code>object</code> property.
     * @enum     {String}    
     * @readonly
     */
    LoyaltiesEarningRulesDisableResponseBody['ObjectEnum'] = {
    
        /**
         * value: "earning_rule"
         * @constant
         */
        "earning_rule": "earning_rule"    
    };


/**
 * Allowed values for the <code>validityDayOfWeek</code> property.
 * @enum {Number}
 * @readonly
 */
LoyaltiesEarningRulesDisableResponseBody['ValidityDayOfWeekEnum'] = {

    /**
     * value: 0
     * @constant
     */
    "0": 0,

    /**
     * value: 1
     * @constant
     */
    "1": 1,

    /**
     * value: 2
     * @constant
     */
    "2": 2,

    /**
     * value: 3
     * @constant
     */
    "3": 3,

    /**
     * value: 4
     * @constant
     */
    "4": 4,

    /**
     * value: 5
     * @constant
     */
    "5": 5,

    /**
     * value: 6
     * @constant
     */
    "6": 6
};



export default LoyaltiesEarningRulesDisableResponseBody;

