/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LoyaltiesEarningRulesUpdateResponseBodyLoyaltyOrderItemsAmount from './LoyaltiesEarningRulesUpdateResponseBodyLoyaltyOrderItemsAmount';
import LoyaltiesEarningRulesUpdateResponseBodyLoyaltyOrderItemsQuantity from './LoyaltiesEarningRulesUpdateResponseBodyLoyaltyOrderItemsQuantity';
import LoyaltiesEarningRulesUpdateResponseBodyLoyaltyOrderItemsSubtotalAmount from './LoyaltiesEarningRulesUpdateResponseBodyLoyaltyOrderItemsSubtotalAmount';
/**
 * The LoyaltiesEarningRulesUpdateResponseBodyLoyaltyOrderItems model module.
 * @module model/LoyaltiesEarningRulesUpdateResponseBodyLoyaltyOrderItems
 * @version 3.0.1
 */
class LoyaltiesEarningRulesUpdateResponseBodyLoyaltyOrderItems {
    /**
     * Constructs a new <code>LoyaltiesEarningRulesUpdateResponseBodyLoyaltyOrderItems</code>.
     * @alias LoyaltiesEarningRulesUpdateResponseBodyLoyaltyOrderItems
     */
    constructor() { 
        
        LoyaltiesEarningRulesUpdateResponseBodyLoyaltyOrderItems.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LoyaltiesEarningRulesUpdateResponseBodyLoyaltyOrderItems</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Partial<LoyaltiesEarningRulesUpdateResponseBodyLoyaltyOrderItems>} data The plain JavaScript object bearing properties of interest.
     * @param {LoyaltiesEarningRulesUpdateResponseBodyLoyaltyOrderItems} [obj] Optional instance to populate.
     * @returns {LoyaltiesEarningRulesUpdateResponseBodyLoyaltyOrderItems} The populated <code>LoyaltiesEarningRulesUpdateResponseBodyLoyaltyOrderItems</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LoyaltiesEarningRulesUpdateResponseBodyLoyaltyOrderItems();

            if (data.hasOwnProperty('quantity')) {
                obj['quantity'] = LoyaltiesEarningRulesUpdateResponseBodyLoyaltyOrderItemsQuantity.constructFromObject(data['quantity']);
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = LoyaltiesEarningRulesUpdateResponseBodyLoyaltyOrderItemsAmount.constructFromObject(data['amount']);
            }
            if (data.hasOwnProperty('subtotal_amount')) {
                obj['subtotal_amount'] = LoyaltiesEarningRulesUpdateResponseBodyLoyaltyOrderItemsSubtotalAmount.constructFromObject(data['subtotal_amount']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>LoyaltiesEarningRulesUpdateResponseBodyLoyaltyOrderItems</code>.
     * @param {Partial<LoyaltiesEarningRulesUpdateResponseBodyLoyaltyOrderItems>} data The plain JavaScript object bearing properties of interest.
     * @returns {boolean} to indicate whether the JSON data is valid with respect to <code>LoyaltiesEarningRulesUpdateResponseBodyLoyaltyOrderItems</code>.
     */
    static validateJSON(data) {
        // validate the optional field `quantity`
        if (data['quantity']) { // data not null
          LoyaltiesEarningRulesUpdateResponseBodyLoyaltyOrderItemsQuantity.validateJSON(data['quantity']);
        }
        // validate the optional field `amount`
        if (data['amount']) { // data not null
          LoyaltiesEarningRulesUpdateResponseBodyLoyaltyOrderItemsAmount.validateJSON(data['amount']);
        }
        // validate the optional field `subtotal_amount`
        if (data['subtotal_amount']) { // data not null
          LoyaltiesEarningRulesUpdateResponseBodyLoyaltyOrderItemsSubtotalAmount.validateJSON(data['subtotal_amount']);
        }

        return true;
    }


}



/**
    * @type {LoyaltiesEarningRulesUpdateResponseBodyLoyaltyOrderItemsQuantity | undefined}
    */
LoyaltiesEarningRulesUpdateResponseBodyLoyaltyOrderItems.prototype['quantity'] = undefined;

/**
    * @type {LoyaltiesEarningRulesUpdateResponseBodyLoyaltyOrderItemsAmount | undefined}
    */
LoyaltiesEarningRulesUpdateResponseBodyLoyaltyOrderItems.prototype['amount'] = undefined;

/**
    * @type {LoyaltiesEarningRulesUpdateResponseBodyLoyaltyOrderItemsSubtotalAmount | undefined}
    */
LoyaltiesEarningRulesUpdateResponseBodyLoyaltyOrderItems.prototype['subtotal_amount'] = undefined;






export default LoyaltiesEarningRulesUpdateResponseBodyLoyaltyOrderItems;

