/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ManagementProjectsBrandingCreateResponseBodyAddress from './ManagementProjectsBrandingCreateResponseBodyAddress';
import ManagementProjectsBrandingCreateResponseBodyBrand from './ManagementProjectsBrandingCreateResponseBodyBrand';
import ManagementProjectsBrandingCreateResponseBodyCockpits from './ManagementProjectsBrandingCreateResponseBodyCockpits';
import ManagementProjectsBrandingCreateResponseBodyContact from './ManagementProjectsBrandingCreateResponseBodyContact';

/**
 * The ManagementProjectsBrandingCreateResponseBody model module.
 * @module model/ManagementProjectsBrandingCreateResponseBody
 * @version 3.0.0
 */
class ManagementProjectsBrandingCreateResponseBody {
    /**
     * Constructs a new <code>ManagementProjectsBrandingCreateResponseBody</code>.
     * Response body schema for **POST** &#x60;/management/v1/projects/{projectId}/branding&#x60;.
     * @alias module:model/ManagementProjectsBrandingCreateResponseBody
     */
    constructor() { 
        
        ManagementProjectsBrandingCreateResponseBody.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ManagementProjectsBrandingCreateResponseBody</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ManagementProjectsBrandingCreateResponseBody} obj Optional instance to populate.
     * @returns {module:model/ManagementProjectsBrandingCreateResponseBody} The populated <code>ManagementProjectsBrandingCreateResponseBody</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ManagementProjectsBrandingCreateResponseBody();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('brand')) {
                obj['brand'] = ManagementProjectsBrandingCreateResponseBodyBrand.constructFromObject(data['brand']);
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = ManagementProjectsBrandingCreateResponseBodyAddress.constructFromObject(data['address']);
            }
            if (data.hasOwnProperty('contact')) {
                obj['contact'] = ManagementProjectsBrandingCreateResponseBodyContact.constructFromObject(data['contact']);
            }
            if (data.hasOwnProperty('cockpits')) {
                obj['cockpits'] = ManagementProjectsBrandingCreateResponseBodyCockpits.constructFromObject(data['cockpits']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ManagementProjectsBrandingCreateResponseBody</code>.
     * @param {object} data The plain JavaScript object bearing properties of interest.
     * @returns {boolean} to indicate whether the JSON data is valid with respect to <code>ManagementProjectsBrandingCreateResponseBody</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // validate the optional field `brand`
        if (data['brand']) { // data not null
          ManagementProjectsBrandingCreateResponseBodyBrand.validateJSON(data['brand']);
        }
        // validate the optional field `address`
        if (data['address']) { // data not null
          ManagementProjectsBrandingCreateResponseBodyAddress.validateJSON(data['address']);
        }
        // validate the optional field `contact`
        if (data['contact']) { // data not null
          ManagementProjectsBrandingCreateResponseBodyContact.validateJSON(data['contact']);
        }
        // validate the optional field `cockpits`
        if (data['cockpits']) { // data not null
          ManagementProjectsBrandingCreateResponseBodyCockpits.validateJSON(data['cockpits']);
        }

        return true;
    }


}



/**
 * Unique identifier of the brand configuration.
 * @member {String} 
 */
ManagementProjectsBrandingCreateResponseBody.prototype['id'] = undefined;

/**
 * @member {module:model/ManagementProjectsBrandingCreateResponseBodyBrand} 
 */
ManagementProjectsBrandingCreateResponseBody.prototype['brand'] = undefined;

/**
 * @member {module:model/ManagementProjectsBrandingCreateResponseBodyAddress} 
 */
ManagementProjectsBrandingCreateResponseBody.prototype['address'] = undefined;

/**
 * @member {module:model/ManagementProjectsBrandingCreateResponseBodyContact} 
 */
ManagementProjectsBrandingCreateResponseBody.prototype['contact'] = undefined;

/**
 * @member {module:model/ManagementProjectsBrandingCreateResponseBodyCockpits} 
 */
ManagementProjectsBrandingCreateResponseBody.prototype['cockpits'] = undefined;






export default ManagementProjectsBrandingCreateResponseBody;

