/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ManagementProjectsUsersInviteCreateRequestBody model module.
 * @module model/ManagementProjectsUsersInviteCreateRequestBody
 * @version 3.0.0
 */
class ManagementProjectsUsersInviteCreateRequestBody {
    /**
     * Constructs a new <code>ManagementProjectsUsersInviteCreateRequestBody</code>.
     * Request body schema for **POST** &#x60;/management/v1/projects/users/invite&#x60;.
     * @alias module:model/ManagementProjectsUsersInviteCreateRequestBody
     */
    constructor() { 
        
        ManagementProjectsUsersInviteCreateRequestBody.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ManagementProjectsUsersInviteCreateRequestBody</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ManagementProjectsUsersInviteCreateRequestBody} obj Optional instance to populate.
     * @returns {module:model/ManagementProjectsUsersInviteCreateRequestBody} The populated <code>ManagementProjectsUsersInviteCreateRequestBody</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ManagementProjectsUsersInviteCreateRequestBody();

            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('first_name')) {
                obj['first_name'] = ApiClient.convertToType(data['first_name'], 'String');
            }
            if (data.hasOwnProperty('last_name')) {
                obj['last_name'] = ApiClient.convertToType(data['last_name'], 'String');
            }
            if (data.hasOwnProperty('projects')) {
                obj['projects'] = ApiClient.convertToType(data['projects'], {'String': 'String'});
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ManagementProjectsUsersInviteCreateRequestBody</code>.
     * @param {object} data The plain JavaScript object bearing properties of interest.
     * @returns {boolean} to indicate whether the JSON data is valid with respect to <code>ManagementProjectsUsersInviteCreateRequestBody</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['first_name'] && !(typeof data['first_name'] === 'string' || data['first_name'] instanceof String)) {
            throw new Error("Expected the field `first_name` to be a primitive type in the JSON string but got " + data['first_name']);
        }
        // ensure the json data is a string
        if (data['last_name'] && !(typeof data['last_name'] === 'string' || data['last_name'] instanceof String)) {
            throw new Error("Expected the field `last_name` to be a primitive type in the JSON string but got " + data['last_name']);
        }

        return true;
    }


}



/**
 * Email address to which the invitation will be sent. Must be a valid email address.
 * @member {String} 
 */
ManagementProjectsUsersInviteCreateRequestBody.prototype['email'] = undefined;

/**
 * First name of the person who will receive the invitation. The name will be used in the user profile.
 * @member {String} 
 */
ManagementProjectsUsersInviteCreateRequestBody.prototype['first_name'] = undefined;

/**
 * Last name of the person who will receive the invitation. The name will be used in the user profile.
 * @member {String} 
 */
ManagementProjectsUsersInviteCreateRequestBody.prototype['last_name'] = undefined;

/**
 * In the key, provide the project ID to which the new user will be assigned. In the value, provide the role which the user will have in the project. The predefined Voucherify roles are: `ADMIN`, `USER`, `VIEWER`, `MERCHANT`, `USER_RESTRICTED` (for the Areas and Stores, an Enterprise feature). Send a custom role ID (Enterprise feature) to assign a custom role. To find the custom role ID: If you are an admin, go to Voucherify Dashboard, Team settings, and Roles tab. Click on a custom role. The custom role ID is in the URL in the format `role_XyZ7aB9cD2eF4gH1iJ0kL5mN6oP8qR3s`.
 * @member {Object.<String, String>} 
 */
ManagementProjectsUsersInviteCreateRequestBody.prototype['projects'] = undefined;






export default ManagementProjectsUsersInviteCreateRequestBody;

