/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
 * The MemberActivityDataRedemptionVoucherRedemption model module.
 * @module model/MemberActivityDataRedemptionVoucherRedemption
 * @version 3.0.1
 */
class MemberActivityDataRedemptionVoucherRedemption {
    /**
     * Constructs a new <code>MemberActivityDataRedemptionVoucherRedemption</code>.
     * @alias MemberActivityDataRedemptionVoucherRedemption
     */
    constructor() { 
        
        MemberActivityDataRedemptionVoucherRedemption.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
        obj['object'] = 'list';
    }

    /**
     * Constructs a <code>MemberActivityDataRedemptionVoucherRedemption</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Partial<MemberActivityDataRedemptionVoucherRedemption>} data The plain JavaScript object bearing properties of interest.
     * @param {MemberActivityDataRedemptionVoucherRedemption} [obj] Optional instance to populate.
     * @returns {MemberActivityDataRedemptionVoucherRedemption} The populated <code>MemberActivityDataRedemptionVoucherRedemption</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MemberActivityDataRedemptionVoucherRedemption();

            if (data.hasOwnProperty('quantity')) {
                obj['quantity'] = ApiClient.convertToType(data['quantity'], 'Number');
            }
            if (data.hasOwnProperty('redeemed_quantity')) {
                obj['redeemed_quantity'] = ApiClient.convertToType(data['redeemed_quantity'], 'Number');
            }
            if (data.hasOwnProperty('redeemed_points')) {
                obj['redeemed_points'] = ApiClient.convertToType(data['redeemed_points'], 'Number');
            }
            if (data.hasOwnProperty('object')) {
                obj['object'] = ApiClient.convertToType(data['object'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MemberActivityDataRedemptionVoucherRedemption</code>.
     * @param {Partial<MemberActivityDataRedemptionVoucherRedemption>} data The plain JavaScript object bearing properties of interest.
     * @returns {boolean} to indicate whether the JSON data is valid with respect to <code>MemberActivityDataRedemptionVoucherRedemption</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['object'] && !(typeof data['object'] === 'string' || data['object'] instanceof String)) {
            throw new Error("Expected the field `object` to be a primitive type in the JSON string but got " + data['object']);
        }
        // ensure the json data is a string
        if (data['url'] && !(typeof data['url'] === 'string' || data['url'] instanceof String)) {
            throw new Error("Expected the field `url` to be a primitive type in the JSON string but got " + data['url']);
        }

        return true;
    }


}



/**
    * How many times a voucher can be redeemed. A `null` value means unlimited.
    * @type {Number | undefined}
    */
MemberActivityDataRedemptionVoucherRedemption.prototype['quantity'] = undefined;

/**
    * How many times a voucher has already been redeemed.
    * @type {Number | undefined}
    */
MemberActivityDataRedemptionVoucherRedemption.prototype['redeemed_quantity'] = undefined;

/**
    * Total loyalty points redeemed.
    * @type {Number | undefined}
    */
MemberActivityDataRedemptionVoucherRedemption.prototype['redeemed_points'] = undefined;

/**
    * The type of the object represented is by default `list`. To get this list, you need to make a call to the endpoint returned in the url attribute.
    * @type {String | undefined}
    * @default 'list'
    */
MemberActivityDataRedemptionVoucherRedemption.prototype['object'] = 'list';

/**
    * The endpoint where this list of redemptions can be accessed using a **GET** method. `/v1/vouchers/{voucher_code}/redemptions`
    * @type {String | undefined}
    */
MemberActivityDataRedemptionVoucherRedemption.prototype['url'] = undefined;






export default MemberActivityDataRedemptionVoucherRedemption;

