/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ExportOrderFields from './ExportOrderFields';
import ExportOrderOrder from './ExportOrderOrder';
/**
 * The OrdersExportCreateRequestBodyParameters model module.
 * @module model/OrdersExportCreateRequestBodyParameters
 * @version 3.0.1
 */
class OrdersExportCreateRequestBodyParameters {
    /**
     * Constructs a new <code>OrdersExportCreateRequestBodyParameters</code>.
     * List of available fields and filters that can be exported with an order along with the sorting order of the returned data.
     * @alias OrdersExportCreateRequestBodyParameters
     */
    constructor() { 
        
        OrdersExportCreateRequestBodyParameters.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OrdersExportCreateRequestBodyParameters</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Partial<OrdersExportCreateRequestBodyParameters>} data The plain JavaScript object bearing properties of interest.
     * @param {OrdersExportCreateRequestBodyParameters} [obj] Optional instance to populate.
     * @returns {OrdersExportCreateRequestBodyParameters} The populated <code>OrdersExportCreateRequestBodyParameters</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OrdersExportCreateRequestBodyParameters();

            if (data.hasOwnProperty('order')) {
                obj['order'] = ExportOrderOrder.constructFromObject(data['order']);
            }
            if (data.hasOwnProperty('fields')) {
                obj['fields'] = ApiClient.convertToType(data['fields'], [ExportOrderFields]);
            }
            if (data.hasOwnProperty('filters')) {
                obj['filters'] = ApiClient.convertToType(data['filters'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OrdersExportCreateRequestBodyParameters</code>.
     * @param {Partial<OrdersExportCreateRequestBodyParameters>} data The plain JavaScript object bearing properties of interest.
     * @returns {boolean} to indicate whether the JSON data is valid with respect to <code>OrdersExportCreateRequestBodyParameters</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['fields'])) {
            throw new Error("Expected the field `fields` to be an array in the JSON data but got " + data['fields']);
        }

        return true;
    }


}



/**
    * @type {Exclude<keyof typeof ExportOrderOrder, "prototype" | "constructFromObject"> | undefined}
    */
OrdersExportCreateRequestBodyParameters.prototype['order'] = undefined;

/**
    * Array of strings containing the data in the export. These fields define the headers in the CSV file.
    * @type {Array.<Exclude<keyof typeof ExportOrderFields, "prototype" | "constructFromObject">> | undefined}
    */
OrdersExportCreateRequestBodyParameters.prototype['fields'] = undefined;

/**
    * Allowed additional properties must start with \"metadata.\"
    * @type {Object | undefined}
    */
OrdersExportCreateRequestBodyParameters.prototype['filters'] = undefined;






export default OrdersExportCreateRequestBodyParameters;

