/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class ParameterVoucherTypeListPublications.
* @module model/ParameterVoucherTypeListPublications
* @version 3.0.0
* @enum {}
* @readonly
*/
export default class ParameterVoucherTypeListPublications {
    
        /**
         * value: "discount"
         * @constant
         */
        "discount" = "discount";

    
        /**
         * value: "loyalty"
         * @constant
         */
        "loyalty" = "loyalty";

    

    /**
    * Returns a <code>ParameterVoucherTypeListPublications</code> enum value from a Javascript object name.
    * @param {object} object The plain JavaScript object containing the name of the enum value.
    * @returns {module:model/ParameterVoucherTypeListPublications} The enum <code>ParameterVoucherTypeListPublications</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

