/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class ParameterActivityCategory.
* @module model/ParameterActivityCategory
* @version 3.0.0
* @enum {}
* @readonly
*/
export default class ParameterActivityCategory {
    
        /**
         * value: "ACTION"
         * @constant
         */
        "ACTION" = "ACTION";

    
        /**
         * value: "EFFECT"
         * @constant
         */
        "EFFECT" = "EFFECT";

    

    /**
    * Returns a <code>ParameterActivityCategory</code> enum value from a Javascript object name.
    * @param {object} object The plain JavaScript object containing the name of the enum value.
    * @returns {module:model/ParameterActivityCategory} The enum <code>ParameterActivityCategory</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

