/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class ParameterOrderListRedeemables.
* @module model/ParameterOrderListRedeemables
* @version 3.0.0
* @enum {}
* @readonly
*/
export default class ParameterOrderListRedeemables {
    
        /**
         * value: "id"
         * @constant
         */
        "id" = "id";

    
        /**
         * value: "-id"
         * @constant
         */
        "-id" = "-id";

    

    /**
    * Returns a <code>ParameterOrderListRedeemables</code> enum value from a Javascript object name.
    * @param {object} object The plain JavaScript object containing the name of the enum value.
    * @returns {module:model/ParameterOrderListRedeemables} The enum <code>ParameterOrderListRedeemables</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

