/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ParameterFiltersListCustomerRedeemablesRedeemableObjectConditions model module.
 * @module model/ParameterFiltersListCustomerRedeemablesRedeemableObjectConditions
 * @version 3.0.0
 */
class ParameterFiltersListCustomerRedeemablesRedeemableObjectConditions {
    /**
     * Constructs a new <code>ParameterFiltersListCustomerRedeemablesRedeemableObjectConditions</code>.
     * @alias module:model/ParameterFiltersListCustomerRedeemablesRedeemableObjectConditions
     */
    constructor() { 
        
        ParameterFiltersListCustomerRedeemablesRedeemableObjectConditions.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
        obj['$is'] = 'voucher';
        obj['$is_not'] = 'voucher';
    }

    /**
     * Constructs a <code>ParameterFiltersListCustomerRedeemablesRedeemableObjectConditions</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ParameterFiltersListCustomerRedeemablesRedeemableObjectConditions} obj Optional instance to populate.
     * @returns {module:model/ParameterFiltersListCustomerRedeemablesRedeemableObjectConditions} The populated <code>ParameterFiltersListCustomerRedeemablesRedeemableObjectConditions</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ParameterFiltersListCustomerRedeemablesRedeemableObjectConditions();

            if (data.hasOwnProperty('$in')) {
                obj['$in'] = ApiClient.convertToType(data['$in'], ['String']);
            }
            if (data.hasOwnProperty('$not_in')) {
                obj['$not_in'] = ApiClient.convertToType(data['$not_in'], ['String']);
            }
            if (data.hasOwnProperty('$is')) {
                obj['$is'] = ApiClient.convertToType(data['$is'], 'String');
            }
            if (data.hasOwnProperty('$is_not')) {
                obj['$is_not'] = ApiClient.convertToType(data['$is_not'], 'String');
            }
            if (data.hasOwnProperty('$has_value')) {
                obj['$has_value'] = ApiClient.convertToType(data['$has_value'], 'String');
            }
            if (data.hasOwnProperty('$is_unknown')) {
                obj['$is_unknown'] = ApiClient.convertToType(data['$is_unknown'], 'String');
            }
            if (data.hasOwnProperty('$starts_with')) {
                obj['$starts_with'] = ApiClient.convertToType(data['$starts_with'], 'String');
            }
            if (data.hasOwnProperty('$ends_with')) {
                obj['$ends_with'] = ApiClient.convertToType(data['$ends_with'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ParameterFiltersListCustomerRedeemablesRedeemableObjectConditions</code>.
     * @param {object} data The plain JavaScript object bearing properties of interest.
     * @returns {boolean} to indicate whether the JSON data is valid with respect to <code>ParameterFiltersListCustomerRedeemablesRedeemableObjectConditions</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['$in'])) {
            throw new Error("Expected the field `$in` to be an array in the JSON data but got " + data['$in']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['$not_in'])) {
            throw new Error("Expected the field `$not_in` to be an array in the JSON data but got " + data['$not_in']);
        }
        // ensure the json data is a string
        if (data['$is'] && !(typeof data['$is'] === 'string' || data['$is'] instanceof String)) {
            throw new Error("Expected the field `$is` to be a primitive type in the JSON string but got " + data['$is']);
        }
        // ensure the json data is a string
        if (data['$is_not'] && !(typeof data['$is_not'] === 'string' || data['$is_not'] instanceof String)) {
            throw new Error("Expected the field `$is_not` to be a primitive type in the JSON string but got " + data['$is_not']);
        }
        // ensure the json data is a string
        if (data['$has_value'] && !(typeof data['$has_value'] === 'string' || data['$has_value'] instanceof String)) {
            throw new Error("Expected the field `$has_value` to be a primitive type in the JSON string but got " + data['$has_value']);
        }
        // ensure the json data is a string
        if (data['$is_unknown'] && !(typeof data['$is_unknown'] === 'string' || data['$is_unknown'] instanceof String)) {
            throw new Error("Expected the field `$is_unknown` to be a primitive type in the JSON string but got " + data['$is_unknown']);
        }
        // ensure the json data is a string
        if (data['$starts_with'] && !(typeof data['$starts_with'] === 'string' || data['$starts_with'] instanceof String)) {
            throw new Error("Expected the field `$starts_with` to be a primitive type in the JSON string but got " + data['$starts_with']);
        }
        // ensure the json data is a string
        if (data['$ends_with'] && !(typeof data['$ends_with'] === 'string' || data['$ends_with'] instanceof String)) {
            throw new Error("Expected the field `$ends_with` to be a primitive type in the JSON string but got " + data['$ends_with']);
        }

        return true;
    }


}



/**
 * Array of resource values that should be included in the results (multiple values).
 * @member {Array.<module:model/ParameterFiltersListCustomerRedeemablesRedeemableObjectConditions.InEnum>} 
 */
ParameterFiltersListCustomerRedeemablesRedeemableObjectConditions.prototype['$in'] = undefined;

/**
 * Array of resource values that should be included in the results (multiple values).
 * @member {Array.<module:model/ParameterFiltersListCustomerRedeemablesRedeemableObjectConditions.NotInEnum>} 
 */
ParameterFiltersListCustomerRedeemablesRedeemableObjectConditions.prototype['$not_in'] = undefined;

/**
 * Value is exactly this value (single value).
 * @member {module:model/ParameterFiltersListCustomerRedeemablesRedeemableObjectConditions.IsEnum} 
 * @default 'voucher'
 */
ParameterFiltersListCustomerRedeemablesRedeemableObjectConditions.prototype['$is'] = 'voucher';

/**
 * Results omit this value (single value).
 * @member {module:model/ParameterFiltersListCustomerRedeemablesRedeemableObjectConditions.IsNotEnum} 
 * @default 'voucher'
 */
ParameterFiltersListCustomerRedeemablesRedeemableObjectConditions.prototype['$is_not'] = 'voucher';

/**
 * Value is NOT null. The value for this parameter is an empty string.
 * @member {String} 
 */
ParameterFiltersListCustomerRedeemablesRedeemableObjectConditions.prototype['$has_value'] = undefined;

/**
 * Value is null. The value for this parameter is an empty string.
 * @member {String} 
 */
ParameterFiltersListCustomerRedeemablesRedeemableObjectConditions.prototype['$is_unknown'] = undefined;

/**
 * Value starts with the specified string.
 * @member {String} 
 */
ParameterFiltersListCustomerRedeemablesRedeemableObjectConditions.prototype['$starts_with'] = undefined;

/**
 * Value ends with the specified string.
 * @member {String} 
 */
ParameterFiltersListCustomerRedeemablesRedeemableObjectConditions.prototype['$ends_with'] = undefined;





/**
 * Allowed values for the <code>_in</code> property.
 * @enum {String}
 * @readonly
 */
ParameterFiltersListCustomerRedeemablesRedeemableObjectConditions['InEnum'] = {

    /**
     * value: "voucher"
     * @constant
     */
    "voucher": "voucher"
};


/**
 * Allowed values for the <code>notIn</code> property.
 * @enum {String}
 * @readonly
 */
ParameterFiltersListCustomerRedeemablesRedeemableObjectConditions['NotInEnum'] = {

    /**
     * value: "voucher"
     * @constant
     */
    "voucher": "voucher"
};


/**
 * Allowed values for the <code>$is</code> property.
 * @enum {String}
 * @readonly
 */
ParameterFiltersListCustomerRedeemablesRedeemableObjectConditions['IsEnum'] = {

    /**
     * value: "voucher"
     * @constant
     */
    "voucher": "voucher"
};


/**
 * Allowed values for the <code>$is_not</code> property.
 * @enum {String}
 * @readonly
 */
ParameterFiltersListCustomerRedeemablesRedeemableObjectConditions['IsNotEnum'] = {

    /**
     * value: "voucher"
     * @constant
     */
    "voucher": "voucher"
};



export default ParameterFiltersListCustomerRedeemablesRedeemableObjectConditions;

