/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Junction from './Junction';
import ParameterFiltersListBinId from './ParameterFiltersListBinId';
import ParameterFiltersListBinResourceId from './ParameterFiltersListBinResourceId';
import ParameterFiltersListBinResourceName from './ParameterFiltersListBinResourceName';
import ParameterFiltersListBinResourceType from './ParameterFiltersListBinResourceType';

/**
 * The ParameterFiltersListBin model module.
 * @module model/ParameterFiltersListBin
 * @version 3.0.0
 */
class ParameterFiltersListBin {
    /**
     * Constructs a new <code>ParameterFiltersListBin</code>.
     * @alias module:model/ParameterFiltersListBin
     */
    constructor() { 
        
        ParameterFiltersListBin.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ParameterFiltersListBin</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ParameterFiltersListBin} obj Optional instance to populate.
     * @returns {module:model/ParameterFiltersListBin} The populated <code>ParameterFiltersListBin</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ParameterFiltersListBin();

            if (data.hasOwnProperty('junction')) {
                obj['junction'] = Junction.constructFromObject(data['junction']);
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ParameterFiltersListBinId.constructFromObject(data['id']);
            }
            if (data.hasOwnProperty('resource_type')) {
                obj['resource_type'] = ParameterFiltersListBinResourceType.constructFromObject(data['resource_type']);
            }
            if (data.hasOwnProperty('resource_name')) {
                obj['resource_name'] = ParameterFiltersListBinResourceName.constructFromObject(data['resource_name']);
            }
            if (data.hasOwnProperty('resource_id')) {
                obj['resource_id'] = ParameterFiltersListBinResourceId.constructFromObject(data['resource_id']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ParameterFiltersListBin</code>.
     * @param {object} data The plain JavaScript object bearing properties of interest.
     * @returns {boolean} to indicate whether the JSON data is valid with respect to <code>ParameterFiltersListBin</code>.
     */
    static validateJSON(data) {
        // validate the optional field `id`
        if (data['id']) { // data not null
          ParameterFiltersListBinId.validateJSON(data['id']);
        }
        // validate the optional field `resource_type`
        if (data['resource_type']) { // data not null
          ParameterFiltersListBinResourceType.validateJSON(data['resource_type']);
        }
        // validate the optional field `resource_name`
        if (data['resource_name']) { // data not null
          ParameterFiltersListBinResourceName.validateJSON(data['resource_name']);
        }
        // validate the optional field `resource_id`
        if (data['resource_id']) { // data not null
          ParameterFiltersListBinResourceId.validateJSON(data['resource_id']);
        }

        return true;
    }


}



/**
 * @member {module:model/Junction} 
 */
ParameterFiltersListBin.prototype['junction'] = undefined;

/**
 * @member {module:model/ParameterFiltersListBinId} 
 */
ParameterFiltersListBin.prototype['id'] = undefined;

/**
 * @member {module:model/ParameterFiltersListBinResourceType} 
 */
ParameterFiltersListBin.prototype['resource_type'] = undefined;

/**
 * @member {module:model/ParameterFiltersListBinResourceName} 
 */
ParameterFiltersListBin.prototype['resource_name'] = undefined;

/**
 * @member {module:model/ParameterFiltersListBinResourceId} 
 */
ParameterFiltersListBin.prototype['resource_id'] = undefined;






export default ParameterFiltersListBin;

