/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FilterConditionsDateTime from './FilterConditionsDateTime';

/**
 * The ParameterFiltersListCampaignsUpdatedAt model module.
 * @module model/ParameterFiltersListCampaignsUpdatedAt
 * @version 3.0.0
 */
class ParameterFiltersListCampaignsUpdatedAt {
    /**
     * Constructs a new <code>ParameterFiltersListCampaignsUpdatedAt</code>.
     * Timestamp representing the date and time when the campaign was last updated. The value is shown in the ISO 8601 format.
     * @alias module:model/ParameterFiltersListCampaignsUpdatedAt
     */
    constructor() { 
        
        ParameterFiltersListCampaignsUpdatedAt.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ParameterFiltersListCampaignsUpdatedAt</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ParameterFiltersListCampaignsUpdatedAt} obj Optional instance to populate.
     * @returns {module:model/ParameterFiltersListCampaignsUpdatedAt} The populated <code>ParameterFiltersListCampaignsUpdatedAt</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ParameterFiltersListCampaignsUpdatedAt();

            if (data.hasOwnProperty('conditions')) {
                obj['conditions'] = FilterConditionsDateTime.constructFromObject(data['conditions']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ParameterFiltersListCampaignsUpdatedAt</code>.
     * @param {object} data The plain JavaScript object bearing properties of interest.
     * @returns {boolean} to indicate whether the JSON data is valid with respect to <code>ParameterFiltersListCampaignsUpdatedAt</code>.
     */
    static validateJSON(data) {
        // validate the optional field `conditions`
        if (data['conditions']) { // data not null
          FilterConditionsDateTime.validateJSON(data['conditions']);
        }

        return true;
    }


}



/**
 * @member {module:model/FilterConditionsDateTime} 
 */
ParameterFiltersListCampaignsUpdatedAt.prototype['conditions'] = undefined;






export default ParameterFiltersListCampaignsUpdatedAt;

