/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
 * The ProductCollectionsItemProductsItem model module.
 * @module model/ProductCollectionsItemProductsItem
 * @version 3.0.1
 */
class ProductCollectionsItemProductsItem {
    /**
     * Constructs a new <code>ProductCollectionsItemProductsItem</code>.
     * @alias ProductCollectionsItemProductsItem
     * @param {String} id The product ID.
     * @param {ProductCollectionsItemProductsItem.ObjectEnum} object Denotes the type of the object represented by the ID.
     */
    constructor(id, object) { 
        
        ProductCollectionsItemProductsItem.initialize(this, id, object);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, object) { 
        obj['id'] = id;
        obj['object'] = object;
    }

    /**
     * Constructs a <code>ProductCollectionsItemProductsItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Partial<ProductCollectionsItemProductsItem>} data The plain JavaScript object bearing properties of interest.
     * @param {ProductCollectionsItemProductsItem} [obj] Optional instance to populate.
     * @returns {ProductCollectionsItemProductsItem} The populated <code>ProductCollectionsItemProductsItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductCollectionsItemProductsItem();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('product_id')) {
                obj['product_id'] = ApiClient.convertToType(data['product_id'], 'String');
            }
            if (data.hasOwnProperty('object')) {
                obj['object'] = ApiClient.convertToType(data['object'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProductCollectionsItemProductsItem</code>.
     * @param {Partial<ProductCollectionsItemProductsItem>} data The plain JavaScript object bearing properties of interest.
     * @returns {boolean} to indicate whether the JSON data is valid with respect to <code>ProductCollectionsItemProductsItem</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ProductCollectionsItemProductsItem.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['product_id'] && !(typeof data['product_id'] === 'string' || data['product_id'] instanceof String)) {
            throw new Error("Expected the field `product_id` to be a primitive type in the JSON string but got " + data['product_id']);
        }
        // ensure the json data is a string
        if (data['object'] && !(typeof data['object'] === 'string' || data['object'] instanceof String)) {
            throw new Error("Expected the field `object` to be a primitive type in the JSON string but got " + data['object']);
        }

        return true;
    }


}

ProductCollectionsItemProductsItem.RequiredProperties = ["id", "object"];

/**
    * The product ID.
    * @type {String}
    */
ProductCollectionsItemProductsItem.prototype['id'] = undefined;

/**
    * Product ID for SKUs.
    * @type {String | undefined}
    */
ProductCollectionsItemProductsItem.prototype['product_id'] = undefined;

/**
    * Denotes the type of the object represented by the ID.
    * @type {(keyof typeof ProductCollectionsItemProductsItem.ObjectEnum)}
    */
ProductCollectionsItemProductsItem.prototype['object'] = undefined;





    /**
     * Allowed values for the <code>object</code> property.
     * @enum     {String}    
     * @readonly
     */
    ProductCollectionsItemProductsItem['ObjectEnum'] = {
    
        /**
         * value: "sku"
         * @constant
         */
        "sku": "sku",
    
        /**
         * value: "product"
         * @constant
         */
        "product": "product"    
    };



export default ProductCollectionsItemProductsItem;

