/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
 * The PromotionsTiersUpdateResponseBodySummaryRedemptions model module.
 * @module model/PromotionsTiersUpdateResponseBodySummaryRedemptions
 * @version 3.0.2
 */
class PromotionsTiersUpdateResponseBodySummaryRedemptions {
    /**
     * Constructs a new <code>PromotionsTiersUpdateResponseBodySummaryRedemptions</code>.
     * Contains statistics about promotion tier redemptions.
     * @alias PromotionsTiersUpdateResponseBodySummaryRedemptions
     */
    constructor() { 
        
        PromotionsTiersUpdateResponseBodySummaryRedemptions.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PromotionsTiersUpdateResponseBodySummaryRedemptions</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Partial<PromotionsTiersUpdateResponseBodySummaryRedemptions>} data The plain JavaScript object bearing properties of interest.
     * @param {PromotionsTiersUpdateResponseBodySummaryRedemptions} [obj] Optional instance to populate.
     * @returns {PromotionsTiersUpdateResponseBodySummaryRedemptions} The populated <code>PromotionsTiersUpdateResponseBodySummaryRedemptions</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PromotionsTiersUpdateResponseBodySummaryRedemptions();

            if (data.hasOwnProperty('total_redeemed')) {
                obj['total_redeemed'] = ApiClient.convertToType(data['total_redeemed'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PromotionsTiersUpdateResponseBodySummaryRedemptions</code>.
     * @param {Partial<PromotionsTiersUpdateResponseBodySummaryRedemptions>} data The plain JavaScript object bearing properties of interest.
     * @returns {boolean} to indicate whether the JSON data is valid with respect to <code>PromotionsTiersUpdateResponseBodySummaryRedemptions</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
    * Number of times the promotion tier was redeemed.
    * @type {Number | undefined}
    */
PromotionsTiersUpdateResponseBodySummaryRedemptions.prototype['total_redeemed'] = undefined;






export default PromotionsTiersUpdateResponseBodySummaryRedemptions;

