/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
 * The RedemptionVoucherGift model module.
 * @module model/RedemptionVoucherGift
 * @version 3.0.2
 */
class RedemptionVoucherGift {
    /**
     * Constructs a new <code>RedemptionVoucherGift</code>.
     * Object representing gift parameters. Child attributes are present only if &#x60;type&#x60; is &#x60;GIFT_VOUCHER&#x60;. Defaults to &#x60;null&#x60;.
     * @alias RedemptionVoucherGift
     */
    constructor() { 
        
        RedemptionVoucherGift.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RedemptionVoucherGift</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Partial<RedemptionVoucherGift>} data The plain JavaScript object bearing properties of interest.
     * @param {RedemptionVoucherGift} [obj] Optional instance to populate.
     * @returns {RedemptionVoucherGift} The populated <code>RedemptionVoucherGift</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RedemptionVoucherGift();

            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('subtracted_amount')) {
                obj['subtracted_amount'] = ApiClient.convertToType(data['subtracted_amount'], 'Number');
            }
            if (data.hasOwnProperty('balance')) {
                obj['balance'] = ApiClient.convertToType(data['balance'], 'Number');
            }
            if (data.hasOwnProperty('effect')) {
                obj['effect'] = ApiClient.convertToType(data['effect'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RedemptionVoucherGift</code>.
     * @param {Partial<RedemptionVoucherGift>} data The plain JavaScript object bearing properties of interest.
     * @returns {boolean} to indicate whether the JSON data is valid with respect to <code>RedemptionVoucherGift</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['effect'] && !(typeof data['effect'] === 'string' || data['effect'] instanceof String)) {
            throw new Error("Expected the field `effect` to be a primitive type in the JSON string but got " + data['effect']);
        }

        return true;
    }


}



/**
    * Total gift card income over the lifetime of the card. The value is multiplied by 100 to represent 2 decimal places. For example `10000 cents` for `$100.00`.
    * @type {Number | undefined}
    */
RedemptionVoucherGift.prototype['amount'] = undefined;

/**
    * Total amount of subtracted credits over the gift card lifetime. The value is multiplied by 100 to represent 2 decimal places. For example `10000 cents` for `$100.00`.
    * @type {Number | undefined}
    */
RedemptionVoucherGift.prototype['subtracted_amount'] = undefined;

/**
    * Available funds. The value is multiplied by 100 to represent 2 decimal places. For example `10000 cents` for `$100.00`.
    * @type {Number | undefined}
    */
RedemptionVoucherGift.prototype['balance'] = undefined;

/**
    * Defines how the credits are applied to the customer's order.
    * @type {(keyof typeof RedemptionVoucherGift.EffectEnum) | undefined}
    */
RedemptionVoucherGift.prototype['effect'] = undefined;





    /**
     * Allowed values for the <code>effect</code> property.
     * @enum     {String}    
     * @readonly
     */
    RedemptionVoucherGift['EffectEnum'] = {
    
        /**
         * value: "APPLY_TO_ORDER"
         * @constant
         */
        "APPLY_TO_ORDER": "APPLY_TO_ORDER",
    
        /**
         * value: "APPLY_TO_ITEMS"
         * @constant
         */
        "APPLY_TO_ITEMS": "APPLY_TO_ITEMS"    
    };



export default RedemptionVoucherGift;

