/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Category from './Category';
import RedemptionsGetResponseBodyPromotionTierAction from './RedemptionsGetResponseBodyPromotionTierAction';
import RedemptionsGetResponseBodyPromotionTierCampaign from './RedemptionsGetResponseBodyPromotionTierCampaign';
import RedemptionsGetResponseBodyPromotionTierSummary from './RedemptionsGetResponseBodyPromotionTierSummary';
import ValidationRuleAssignmentsList from './ValidationRuleAssignmentsList';
import ValidityHours from './ValidityHours';
import ValidityTimeframe from './ValidityTimeframe';
/**
 * The RedemptionsGetResponseBodyPromotionTier model module.
 * @module model/RedemptionsGetResponseBodyPromotionTier
 * @version 3.0.1
 */
class RedemptionsGetResponseBodyPromotionTier {
    /**
     * Constructs a new <code>RedemptionsGetResponseBodyPromotionTier</code>.
     * @alias RedemptionsGetResponseBodyPromotionTier
     */
    constructor() { 
        
        RedemptionsGetResponseBodyPromotionTier.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
        obj['object'] = 'promotion_tier';
    }

    /**
     * Constructs a <code>RedemptionsGetResponseBodyPromotionTier</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Partial<RedemptionsGetResponseBodyPromotionTier>} data The plain JavaScript object bearing properties of interest.
     * @param {RedemptionsGetResponseBodyPromotionTier} [obj] Optional instance to populate.
     * @returns {RedemptionsGetResponseBodyPromotionTier} The populated <code>RedemptionsGetResponseBodyPromotionTier</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RedemptionsGetResponseBodyPromotionTier();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('banner')) {
                obj['banner'] = ApiClient.convertToType(data['banner'], 'String');
            }
            if (data.hasOwnProperty('action')) {
                obj['action'] = RedemptionsGetResponseBodyPromotionTierAction.constructFromObject(data['action']);
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], Object);
            }
            if (data.hasOwnProperty('hierarchy')) {
                obj['hierarchy'] = ApiClient.convertToType(data['hierarchy'], 'Number');
            }
            if (data.hasOwnProperty('promotion_id')) {
                obj['promotion_id'] = ApiClient.convertToType(data['promotion_id'], 'String');
            }
            if (data.hasOwnProperty('campaign')) {
                obj['campaign'] = RedemptionsGetResponseBodyPromotionTierCampaign.constructFromObject(data['campaign']);
            }
            if (data.hasOwnProperty('campaign_id')) {
                obj['campaign_id'] = ApiClient.convertToType(data['campaign_id'], 'String');
            }
            if (data.hasOwnProperty('active')) {
                obj['active'] = ApiClient.convertToType(data['active'], 'Boolean');
            }
            if (data.hasOwnProperty('start_date')) {
                obj['start_date'] = ApiClient.convertToType(data['start_date'], 'Date');
            }
            if (data.hasOwnProperty('expiration_date')) {
                obj['expiration_date'] = ApiClient.convertToType(data['expiration_date'], 'Date');
            }
            if (data.hasOwnProperty('validity_timeframe')) {
                obj['validity_timeframe'] = ValidityTimeframe.constructFromObject(data['validity_timeframe']);
            }
            if (data.hasOwnProperty('validity_day_of_week')) {
                obj['validity_day_of_week'] = ApiClient.convertToType(data['validity_day_of_week'], ['Number']);
            }
            if (data.hasOwnProperty('validity_hours')) {
                obj['validity_hours'] = ValidityHours.constructFromObject(data['validity_hours']);
            }
            if (data.hasOwnProperty('summary')) {
                obj['summary'] = RedemptionsGetResponseBodyPromotionTierSummary.constructFromObject(data['summary']);
            }
            if (data.hasOwnProperty('object')) {
                obj['object'] = ApiClient.convertToType(data['object'], 'String');
            }
            if (data.hasOwnProperty('validation_rule_assignments')) {
                obj['validation_rule_assignments'] = ValidationRuleAssignmentsList.constructFromObject(data['validation_rule_assignments']);
            }
            if (data.hasOwnProperty('category_id')) {
                obj['category_id'] = ApiClient.convertToType(data['category_id'], 'String');
            }
            if (data.hasOwnProperty('categories')) {
                obj['categories'] = ApiClient.convertToType(data['categories'], [Category]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RedemptionsGetResponseBodyPromotionTier</code>.
     * @param {Partial<RedemptionsGetResponseBodyPromotionTier>} data The plain JavaScript object bearing properties of interest.
     * @returns {boolean} to indicate whether the JSON data is valid with respect to <code>RedemptionsGetResponseBodyPromotionTier</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['banner'] && !(typeof data['banner'] === 'string' || data['banner'] instanceof String)) {
            throw new Error("Expected the field `banner` to be a primitive type in the JSON string but got " + data['banner']);
        }
        // validate the optional field `action`
        if (data['action']) { // data not null
          RedemptionsGetResponseBodyPromotionTierAction.validateJSON(data['action']);
        }
        // ensure the json data is a string
        if (data['promotion_id'] && !(typeof data['promotion_id'] === 'string' || data['promotion_id'] instanceof String)) {
            throw new Error("Expected the field `promotion_id` to be a primitive type in the JSON string but got " + data['promotion_id']);
        }
        // validate the optional field `campaign`
        if (data['campaign']) { // data not null
          RedemptionsGetResponseBodyPromotionTierCampaign.validateJSON(data['campaign']);
        }
        // ensure the json data is a string
        if (data['campaign_id'] && !(typeof data['campaign_id'] === 'string' || data['campaign_id'] instanceof String)) {
            throw new Error("Expected the field `campaign_id` to be a primitive type in the JSON string but got " + data['campaign_id']);
        }
        // validate the optional field `validity_timeframe`
        if (data['validity_timeframe']) { // data not null
          ValidityTimeframe.validateJSON(data['validity_timeframe']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['validity_day_of_week'])) {
            throw new Error("Expected the field `validity_day_of_week` to be an array in the JSON data but got " + data['validity_day_of_week']);
        }
        // validate the optional field `validity_hours`
        if (data['validity_hours']) { // data not null
          ValidityHours.validateJSON(data['validity_hours']);
        }
        // validate the optional field `summary`
        if (data['summary']) { // data not null
          RedemptionsGetResponseBodyPromotionTierSummary.validateJSON(data['summary']);
        }
        // ensure the json data is a string
        if (data['object'] && !(typeof data['object'] === 'string' || data['object'] instanceof String)) {
            throw new Error("Expected the field `object` to be a primitive type in the JSON string but got " + data['object']);
        }
        // validate the optional field `validation_rule_assignments`
        if (data['validation_rule_assignments']) { // data not null
          ValidationRuleAssignmentsList.validateJSON(data['validation_rule_assignments']);
        }
        // ensure the json data is a string
        if (data['category_id'] && !(typeof data['category_id'] === 'string' || data['category_id'] instanceof String)) {
            throw new Error("Expected the field `category_id` to be a primitive type in the JSON string but got " + data['category_id']);
        }
        if (data['categories']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['categories'])) {
                throw new Error("Expected the field `categories` to be an array in the JSON data but got " + data['categories']);
            }
            // validate the optional field `categories` (array)
            for (const item of data['categories']) {
                Category.validateJSON(item);
            };
        }

        return true;
    }


}



/**
    * Unique promotion tier ID.
    * @type {String | undefined}
    */
RedemptionsGetResponseBodyPromotionTier.prototype['id'] = undefined;

/**
    * Timestamp representing the date and time when the promotion tier was created. The value is shown in the ISO 8601 format.
    * @type {Date | undefined}
    */
RedemptionsGetResponseBodyPromotionTier.prototype['created_at'] = undefined;

/**
    * Timestamp representing the date and time when the promotion tier was updated. The value is shown in the ISO 8601 format.
    * @type {Date | undefined}
    */
RedemptionsGetResponseBodyPromotionTier.prototype['updated_at'] = undefined;

/**
    * Name of the promotion tier.
    * @type {String | undefined}
    */
RedemptionsGetResponseBodyPromotionTier.prototype['name'] = undefined;

/**
    * Text to be displayed to your customers on your website.
    * @type {String | undefined}
    */
RedemptionsGetResponseBodyPromotionTier.prototype['banner'] = undefined;

/**
    * @type {RedemptionsGetResponseBodyPromotionTierAction | undefined}
    */
RedemptionsGetResponseBodyPromotionTier.prototype['action'] = undefined;

/**
    * The metadata object stores all custom attributes assigned to the promotion tier. A set of key/value pairs that you can attach to a promotion tier object. It can be useful for storing additional information about the promotion tier in a structured format.
    * @type {Object | undefined}
    */
RedemptionsGetResponseBodyPromotionTier.prototype['metadata'] = undefined;

/**
    * The promotions hierarchy defines the order in which the discounts from different tiers will be applied to a customer's order. If a customer qualifies for discounts from more than one tier, discounts will be applied in the order defined in the hierarchy.
    * @type {Number | undefined}
    */
RedemptionsGetResponseBodyPromotionTier.prototype['hierarchy'] = undefined;

/**
    * Promotion unique ID.
    * @type {String | undefined}
    */
RedemptionsGetResponseBodyPromotionTier.prototype['promotion_id'] = undefined;

/**
    * @type {RedemptionsGetResponseBodyPromotionTierCampaign | undefined}
    */
RedemptionsGetResponseBodyPromotionTier.prototype['campaign'] = undefined;

/**
    * Promotion tier's parent campaign's unique ID.
    * @type {String | undefined}
    */
RedemptionsGetResponseBodyPromotionTier.prototype['campaign_id'] = undefined;

/**
    * A flag to toggle the promotion tier on or off. You can disable a promotion tier even though it's within the active period defined by the `start_date` and `expiration_date`.    - `true` indicates an *active* promotion tier - `false` indicates an *inactive* promotion tier
    * @type {Boolean | undefined}
    */
RedemptionsGetResponseBodyPromotionTier.prototype['active'] = undefined;

/**
    * Activation timestamp defines when the promotion tier starts to be active in ISO 8601 format. Promotion tier is *inactive before* this date. 
    * @type {Date | undefined}
    */
RedemptionsGetResponseBodyPromotionTier.prototype['start_date'] = undefined;

/**
    * Activation timestamp defines when the promotion tier expires in ISO 8601 format. Promotion tier is *inactive after* this date. 
    * @type {Date | undefined}
    */
RedemptionsGetResponseBodyPromotionTier.prototype['expiration_date'] = undefined;

/**
    * @type {ValidityTimeframe | undefined}
    */
RedemptionsGetResponseBodyPromotionTier.prototype['validity_timeframe'] = undefined;

/**
    * Integer array corresponding to the particular days of the week in which the voucher is valid.  - `0` Sunday - `1` Monday - `2` Tuesday - `3` Wednesday - `4` Thursday - `5` Friday - `6` Saturday
    * @type {(Array<keyof typeof RedemptionsGetResponseBodyPromotionTier.ValidityDayOfWeekEnum>) | undefined}
    */
RedemptionsGetResponseBodyPromotionTier.prototype['validity_day_of_week'] = undefined;

/**
    * @type {ValidityHours | undefined}
    */
RedemptionsGetResponseBodyPromotionTier.prototype['validity_hours'] = undefined;

/**
    * @type {RedemptionsGetResponseBodyPromotionTierSummary | undefined}
    */
RedemptionsGetResponseBodyPromotionTier.prototype['summary'] = undefined;

/**
    * The type of the object represented by JSON. This object stores information about the promotion tier.
    * @type {String | undefined}
    * @default 'promotion_tier'
    */
RedemptionsGetResponseBodyPromotionTier.prototype['object'] = 'promotion_tier';

/**
    * @type {ValidationRuleAssignmentsList | undefined}
    */
RedemptionsGetResponseBodyPromotionTier.prototype['validation_rule_assignments'] = undefined;

/**
    * Promotion tier category ID.
    * @type {String | undefined}
    */
RedemptionsGetResponseBodyPromotionTier.prototype['category_id'] = undefined;

/**
    * @type {Array.<Category> | undefined}
    */
RedemptionsGetResponseBodyPromotionTier.prototype['categories'] = undefined;





/**
 * Allowed values for the <code>validityDayOfWeek</code> property.
 * @enum {Number}
 * @readonly
 */
RedemptionsGetResponseBodyPromotionTier['ValidityDayOfWeekEnum'] = {

    /**
     * value: 0
     * @constant
     */
    "0": 0,

    /**
     * value: 1
     * @constant
     */
    "1": 1,

    /**
     * value: 2
     * @constant
     */
    "2": 2,

    /**
     * value: 3
     * @constant
     */
    "3": 3,

    /**
     * value: 4
     * @constant
     */
    "4": 4,

    /**
     * value: 5
     * @constant
     */
    "5": 5,

    /**
     * value: 6
     * @constant
     */
    "6": 6
};



export default RedemptionsGetResponseBodyPromotionTier;

