/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RewardAssignmentParameters from './RewardAssignmentParameters';

/**
 * The RewardAssignment model module.
 * @module model/RewardAssignment
 * @version 3.0.0
 */
class RewardAssignment {
    /**
     * Constructs a new <code>RewardAssignment</code>.
     * @alias module:model/RewardAssignment
     */
    constructor() { 
        
        RewardAssignment.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
        obj['object'] = 'reward_assignment';
        obj['related_object_type'] = 'campaign';
    }

    /**
     * Constructs a <code>RewardAssignment</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RewardAssignment} obj Optional instance to populate.
     * @returns {module:model/RewardAssignment} The populated <code>RewardAssignment</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RewardAssignment();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('reward_id')) {
                obj['reward_id'] = ApiClient.convertToType(data['reward_id'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
            if (data.hasOwnProperty('object')) {
                obj['object'] = ApiClient.convertToType(data['object'], 'String');
            }
            if (data.hasOwnProperty('related_object_id')) {
                obj['related_object_id'] = ApiClient.convertToType(data['related_object_id'], 'String');
            }
            if (data.hasOwnProperty('related_object_type')) {
                obj['related_object_type'] = ApiClient.convertToType(data['related_object_type'], 'String');
            }
            if (data.hasOwnProperty('parameters')) {
                obj['parameters'] = RewardAssignmentParameters.constructFromObject(data['parameters']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RewardAssignment</code>.
     * @param {object} data The plain JavaScript object bearing properties of interest.
     * @returns {boolean} to indicate whether the JSON data is valid with respect to <code>RewardAssignment</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['reward_id'] && !(typeof data['reward_id'] === 'string' || data['reward_id'] instanceof String)) {
            throw new Error("Expected the field `reward_id` to be a primitive type in the JSON string but got " + data['reward_id']);
        }
        // ensure the json data is a string
        if (data['object'] && !(typeof data['object'] === 'string' || data['object'] instanceof String)) {
            throw new Error("Expected the field `object` to be a primitive type in the JSON string but got " + data['object']);
        }
        // ensure the json data is a string
        if (data['related_object_id'] && !(typeof data['related_object_id'] === 'string' || data['related_object_id'] instanceof String)) {
            throw new Error("Expected the field `related_object_id` to be a primitive type in the JSON string but got " + data['related_object_id']);
        }
        // ensure the json data is a string
        if (data['related_object_type'] && !(typeof data['related_object_type'] === 'string' || data['related_object_type'] instanceof String)) {
            throw new Error("Expected the field `related_object_type` to be a primitive type in the JSON string but got " + data['related_object_type']);
        }
        // validate the optional field `parameters`
        if (data['parameters']) { // data not null
          RewardAssignmentParameters.validateJSON(data['parameters']);
        }

        return true;
    }


}



/**
 * Unique reward assignment ID, assigned by Voucherify.
 * @member {String} 
 */
RewardAssignment.prototype['id'] = undefined;

/**
 * Associated reward ID.
 * @member {String} 
 */
RewardAssignment.prototype['reward_id'] = undefined;

/**
 * Timestamp representing the date and time when the reward assignment was created. The value is shown in the ISO 8601 format.
 * @member {Date} 
 */
RewardAssignment.prototype['created_at'] = undefined;

/**
 * Timestamp representing the date and time when the reward assignment was updated. The value is shown in the ISO 8601 format.
 * @member {Date} 
 */
RewardAssignment.prototype['updated_at'] = undefined;

/**
 * The type of the object represented by the JSON. This object stores information about the reward assignment.
 * @member {module:model/RewardAssignment.ObjectEnum} 
 * @default 'reward_assignment'
 */
RewardAssignment.prototype['object'] = 'reward_assignment';

/**
 * Related object ID to which the reward was assigned.
 * @member {String} 
 */
RewardAssignment.prototype['related_object_id'] = undefined;

/**
 * Related object type to which the reward was assigned.
 * @member {module:model/RewardAssignment.RelatedObjectTypeEnum} 
 * @default 'campaign'
 */
RewardAssignment.prototype['related_object_type'] = 'campaign';

/**
 * @member {module:model/RewardAssignmentParameters} 
 */
RewardAssignment.prototype['parameters'] = undefined;





/**
 * Allowed values for the <code>object</code> property.
 * @enum {String}
 * @readonly
 */
RewardAssignment['ObjectEnum'] = {

    /**
     * value: "reward_assignment"
     * @constant
     */
    "reward_assignment": "reward_assignment"
};


/**
 * Allowed values for the <code>related_object_type</code> property.
 * @enum {String}
 * @readonly
 */
RewardAssignment['RelatedObjectTypeEnum'] = {

    /**
     * value: "campaign"
     * @constant
     */
    "campaign": "campaign"
};



export default RewardAssignment;

