/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RewardAttributes from './RewardAttributes';
import RewardType from './RewardType';
/**
 * The Reward model module.
 * @module model/Reward
 * @version 3.0.2
 */
class Reward {
    /**
     * Constructs a new <code>Reward</code>.
     * @alias Reward
     * @param {Reward.ObjectEnum} object The type of the object represented by the JSON. This object stores information about the reward.
     */
    constructor(object) { 
        
        Reward.initialize(this, object);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, object) { 
        obj['object'] = object || 'reward';
    }

    /**
     * Constructs a <code>Reward</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Partial<Reward>} data The plain JavaScript object bearing properties of interest.
     * @param {Reward} [obj] Optional instance to populate.
     * @returns {Reward} The populated <code>Reward</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Reward();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('stock')) {
                obj['stock'] = ApiClient.convertToType(data['stock'], 'Number');
            }
            if (data.hasOwnProperty('redeemed')) {
                obj['redeemed'] = ApiClient.convertToType(data['redeemed'], 'Number');
            }
            if (data.hasOwnProperty('attributes')) {
                obj['attributes'] = RewardAttributes.constructFromObject(data['attributes']);
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], Object);
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('parameters')) {
                obj['parameters'] = RewardType.constructFromObject(data['parameters']);
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
            if (data.hasOwnProperty('object')) {
                obj['object'] = ApiClient.convertToType(data['object'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Reward</code>.
     * @param {Partial<Reward>} data The plain JavaScript object bearing properties of interest.
     * @returns {boolean} to indicate whether the JSON data is valid with respect to <code>Reward</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Reward.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // validate the optional field `attributes`
        if (data['attributes']) { // data not null
          RewardAttributes.validateJSON(data['attributes']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        // validate the optional field `parameters`
        if (data['parameters']) { // data not null
          RewardType.validateJSON(data['parameters']);
        }
        // ensure the json data is a string
        if (data['object'] && !(typeof data['object'] === 'string' || data['object'] instanceof String)) {
            throw new Error("Expected the field `object` to be a primitive type in the JSON string but got " + data['object']);
        }

        return true;
    }


}

Reward.RequiredProperties = ["object"];

/**
    * Unique reward ID, assigned by Voucherify.
    * @type {String | undefined}
    */
Reward.prototype['id'] = undefined;

/**
    * Reward name.
    * @type {String | undefined}
    */
Reward.prototype['name'] = undefined;

/**
    * Configurable for **material rewards**. The number of units of the product that you want to share as a reward. Use this parameter to code a stock-taking logic.
    * @type {Number | undefined}
    */
Reward.prototype['stock'] = undefined;

/**
    * Defines the number of already invoked (successful) reward redemptions. 
    * @type {Number | undefined}
    */
Reward.prototype['redeemed'] = undefined;

/**
    * @type {RewardAttributes | undefined}
    */
Reward.prototype['attributes'] = undefined;

/**
    * The metadata object stores all custom attributes assigned to the reward. A set of key/value pairs that you can attach to a reward object. It can be useful for storing additional information about the reward in a structured format.
    * @type {Object | undefined}
    */
Reward.prototype['metadata'] = undefined;

/**
    * Reward type.
    * @type {(keyof typeof Reward.TypeEnum) | undefined}
    */
Reward.prototype['type'] = undefined;

/**
    * @type {RewardType | undefined}
    */
Reward.prototype['parameters'] = undefined;

/**
    * Timestamp representing the date and time when the reward was created. The value is shown in the ISO 8601 format.
    * @type {Date | undefined}
    */
Reward.prototype['created_at'] = undefined;

/**
    * Timestamp representing the date and time when the reward was updated. The value is shown in the ISO 8601 format.
    * @type {Date | undefined}
    */
Reward.prototype['updated_at'] = undefined;

/**
    * The type of the object represented by the JSON. This object stores information about the reward.
    * @type {(keyof typeof Reward.ObjectEnum)}
    * @default 'reward'
    */
Reward.prototype['object'] = 'reward';





    /**
     * Allowed values for the <code>type</code> property.
     * @enum     {String}    
     * @readonly
     */
    Reward['TypeEnum'] = {
    
        /**
         * value: "CAMPAIGN"
         * @constant
         */
        "CAMPAIGN": "CAMPAIGN",
    
        /**
         * value: "COIN"
         * @constant
         */
        "COIN": "COIN",
    
        /**
         * value: "MATERIAL"
         * @constant
         */
        "MATERIAL": "MATERIAL"    
    };


    /**
     * Allowed values for the <code>object</code> property.
     * @enum     {String}    
     * @readonly
     */
    Reward['ObjectEnum'] = {
    
        /**
         * value: "reward"
         * @constant
         */
        "reward": "reward"    
    };



export default Reward;

