/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
 * The RewardsUpdateRequestBodyAttributes model module.
 * @module model/RewardsUpdateRequestBodyAttributes
 * @version 3.0.1
 */
class RewardsUpdateRequestBodyAttributes {
    /**
     * Constructs a new <code>RewardsUpdateRequestBodyAttributes</code>.
     * Attributes of a material reward.
     * @alias RewardsUpdateRequestBodyAttributes
     */
    constructor() { 
        
        RewardsUpdateRequestBodyAttributes.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RewardsUpdateRequestBodyAttributes</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Partial<RewardsUpdateRequestBodyAttributes>} data The plain JavaScript object bearing properties of interest.
     * @param {RewardsUpdateRequestBodyAttributes} [obj] Optional instance to populate.
     * @returns {RewardsUpdateRequestBodyAttributes} The populated <code>RewardsUpdateRequestBodyAttributes</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RewardsUpdateRequestBodyAttributes();

            if (data.hasOwnProperty('image_url')) {
                obj['image_url'] = ApiClient.convertToType(data['image_url'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RewardsUpdateRequestBodyAttributes</code>.
     * @param {Partial<RewardsUpdateRequestBodyAttributes>} data The plain JavaScript object bearing properties of interest.
     * @returns {boolean} to indicate whether the JSON data is valid with respect to <code>RewardsUpdateRequestBodyAttributes</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['image_url'] && !(typeof data['image_url'] === 'string' || data['image_url'] instanceof String)) {
            throw new Error("Expected the field `image_url` to be a primitive type in the JSON string but got " + data['image_url']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }

        return true;
    }


}



/**
    * HTTPS URL pointing to a .png or .jpg file.
    * @type {String | undefined}
    */
RewardsUpdateRequestBodyAttributes.prototype['image_url'] = undefined;

/**
    * Description of a material reward.
    * @type {String | undefined}
    */
RewardsUpdateRequestBodyAttributes.prototype['description'] = undefined;






export default RewardsUpdateRequestBodyAttributes;

