/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
 * The SimpleOrderItem model module.
 * @module model/SimpleOrderItem
 * @version 3.0.2
 */
class SimpleOrderItem {
    /**
     * Constructs a new <code>SimpleOrderItem</code>.
     * @alias SimpleOrderItem
     */
    constructor() { 
        
        SimpleOrderItem.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
        obj['object'] = 'order_item';
    }

    /**
     * Constructs a <code>SimpleOrderItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Partial<SimpleOrderItem>} data The plain JavaScript object bearing properties of interest.
     * @param {SimpleOrderItem} [obj] Optional instance to populate.
     * @returns {SimpleOrderItem} The populated <code>SimpleOrderItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SimpleOrderItem();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('object')) {
                obj['object'] = ApiClient.convertToType(data['object'], 'String');
            }
            if (data.hasOwnProperty('source_id')) {
                obj['source_id'] = ApiClient.convertToType(data['source_id'], 'String');
            }
            if (data.hasOwnProperty('related_object')) {
                obj['related_object'] = ApiClient.convertToType(data['related_object'], 'String');
            }
            if (data.hasOwnProperty('product_id')) {
                obj['product_id'] = ApiClient.convertToType(data['product_id'], 'String');
            }
            if (data.hasOwnProperty('sku_id')) {
                obj['sku_id'] = ApiClient.convertToType(data['sku_id'], 'String');
            }
            if (data.hasOwnProperty('quantity')) {
                obj['quantity'] = ApiClient.convertToType(data['quantity'], 'Number');
            }
            if (data.hasOwnProperty('applied_quantity')) {
                obj['applied_quantity'] = ApiClient.convertToType(data['applied_quantity'], 'Number');
            }
            if (data.hasOwnProperty('applied_quantity_amount')) {
                obj['applied_quantity_amount'] = ApiClient.convertToType(data['applied_quantity_amount'], 'Number');
            }
            if (data.hasOwnProperty('discount_quantity')) {
                obj['discount_quantity'] = ApiClient.convertToType(data['discount_quantity'], 'Number');
            }
            if (data.hasOwnProperty('applied_discount_quantity')) {
                obj['applied_discount_quantity'] = ApiClient.convertToType(data['applied_discount_quantity'], 'Number');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('discount_amount')) {
                obj['discount_amount'] = ApiClient.convertToType(data['discount_amount'], 'Number');
            }
            if (data.hasOwnProperty('applied_discount_amount')) {
                obj['applied_discount_amount'] = ApiClient.convertToType(data['applied_discount_amount'], 'Number');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'Number');
            }
            if (data.hasOwnProperty('subtotal_amount')) {
                obj['subtotal_amount'] = ApiClient.convertToType(data['subtotal_amount'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SimpleOrderItem</code>.
     * @param {Partial<SimpleOrderItem>} data The plain JavaScript object bearing properties of interest.
     * @returns {boolean} to indicate whether the JSON data is valid with respect to <code>SimpleOrderItem</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['object'] && !(typeof data['object'] === 'string' || data['object'] instanceof String)) {
            throw new Error("Expected the field `object` to be a primitive type in the JSON string but got " + data['object']);
        }
        // ensure the json data is a string
        if (data['source_id'] && !(typeof data['source_id'] === 'string' || data['source_id'] instanceof String)) {
            throw new Error("Expected the field `source_id` to be a primitive type in the JSON string but got " + data['source_id']);
        }
        // ensure the json data is a string
        if (data['related_object'] && !(typeof data['related_object'] === 'string' || data['related_object'] instanceof String)) {
            throw new Error("Expected the field `related_object` to be a primitive type in the JSON string but got " + data['related_object']);
        }
        // ensure the json data is a string
        if (data['product_id'] && !(typeof data['product_id'] === 'string' || data['product_id'] instanceof String)) {
            throw new Error("Expected the field `product_id` to be a primitive type in the JSON string but got " + data['product_id']);
        }
        // ensure the json data is a string
        if (data['sku_id'] && !(typeof data['sku_id'] === 'string' || data['sku_id'] instanceof String)) {
            throw new Error("Expected the field `sku_id` to be a primitive type in the JSON string but got " + data['sku_id']);
        }

        return true;
    }


}



/**
    * Unique identifier of the order line item.
    * @type {String | undefined}
    */
SimpleOrderItem.prototype['id'] = undefined;

/**
    * The type of the object represented by JSON. This object stores information about the `order_item`.
    * @type {(keyof typeof SimpleOrderItem.ObjectEnum) | undefined}
    * @default 'order_item'
    */
SimpleOrderItem.prototype['object'] = 'order_item';

/**
    * The merchant's product/SKU ID (if it is different from the Voucherify product/SKU ID). It is useful in the integration between multiple systems. It can be an ID from an eCommerce site, a database, or a third-party service.
    * @type {String | undefined}
    */
SimpleOrderItem.prototype['source_id'] = undefined;

/**
    * Used along with the `source_id` property, can be set to either SKU or product.
    * @type {(keyof typeof SimpleOrderItem.RelatedObjectEnum) | undefined}
    */
SimpleOrderItem.prototype['related_object'] = undefined;

/**
    * Unique identifier of the product. It is assigned by Voucherify.
    * @type {String | undefined}
    */
SimpleOrderItem.prototype['product_id'] = undefined;

/**
    * Unique identifier of the SKU. It is assigned by Voucherify.
    * @type {String | undefined}
    */
SimpleOrderItem.prototype['sku_id'] = undefined;

/**
    * Quantity of the particular item in the cart.
    * @type {Number | undefined}
    */
SimpleOrderItem.prototype['quantity'] = undefined;

/**
    * Quantity of items changed by the application of a new quantity items. It can be positive when an item is added or negative if an item is replaced.
    * @type {Number | undefined}
    */
SimpleOrderItem.prototype['applied_quantity'] = undefined;

/**
    * Amount for the items changed by the application of a new quantity items. It can be positive when an item is added or negative if an item is replaced.
    * @type {Number | undefined}
    */
SimpleOrderItem.prototype['applied_quantity_amount'] = undefined;

/**
    * Number of discounted items.
    * @type {Number | undefined}
    */
SimpleOrderItem.prototype['discount_quantity'] = undefined;

/**
    * Number of the discounted items applied in the transaction.
    * @type {Number | undefined}
    */
SimpleOrderItem.prototype['applied_discount_quantity'] = undefined;

/**
    * Total amount of the order item (price * quantity).
    * @type {Number | undefined}
    */
SimpleOrderItem.prototype['amount'] = undefined;

/**
    * Sum of all order-item-level discounts applied to the order.
    * @type {Number | undefined}
    */
SimpleOrderItem.prototype['discount_amount'] = undefined;

/**
    * Order-level discount amount applied in the transaction.
    * @type {Number | undefined}
    */
SimpleOrderItem.prototype['applied_discount_amount'] = undefined;

/**
    * Unit price of an item. The value is multiplied by 100 to represent 2 decimal places. For example `10000 cents` for `$100.00`.
    * @type {Number | undefined}
    */
SimpleOrderItem.prototype['price'] = undefined;

/**
    * Final order item amount after the applied item-level discount.  If there are no item-level discounts applied, this item is equal to the `amount`.    `subtotal_amount`=`amount`-`discount_amount`
    * @type {Number | undefined}
    */
SimpleOrderItem.prototype['subtotal_amount'] = undefined;





    /**
     * Allowed values for the <code>object</code> property.
     * @enum     {String}    
     * @readonly
     */
    SimpleOrderItem['ObjectEnum'] = {
    
        /**
         * value: "order_item"
         * @constant
         */
        "order_item": "order_item"    
    };


    /**
     * Allowed values for the <code>related_object</code> property.
     * @enum     {String}    
     * @readonly
     */
    SimpleOrderItem['RelatedObjectEnum'] = {
    
        /**
         * value: "product"
         * @constant
         */
        "product": "product",
    
        /**
         * value: "sku"
         * @constant
         */
        "sku": "sku"    
    };



export default SimpleOrderItem;

