/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Bundle from './Bundle';
import Error from './Error';
import ValidationsValidateResponseBodyRedeemablesItemResultDetails from './ValidationsValidateResponseBodyRedeemablesItemResultDetails';
import ValidationsValidateResponseBodyRedeemablesItemResultDiscount from './ValidationsValidateResponseBodyRedeemablesItemResultDiscount';
import ValidationsValidateResponseBodyRedeemablesItemResultGift from './ValidationsValidateResponseBodyRedeemablesItemResultGift';
import ValidationsValidateResponseBodyRedeemablesItemResultLoyaltyCard from './ValidationsValidateResponseBodyRedeemablesItemResultLoyaltyCard';

/**
 * The ValidationsValidateResponseBodyRedeemablesItemResult model module.
 * @module model/ValidationsValidateResponseBodyRedeemablesItemResult
 * @version 3.0.0
 */
class ValidationsValidateResponseBodyRedeemablesItemResult {
    /**
     * Constructs a new <code>ValidationsValidateResponseBodyRedeemablesItemResult</code>.
     * @alias module:model/ValidationsValidateResponseBodyRedeemablesItemResult
     */
    constructor() { 
        
        ValidationsValidateResponseBodyRedeemablesItemResult.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ValidationsValidateResponseBodyRedeemablesItemResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ValidationsValidateResponseBodyRedeemablesItemResult} obj Optional instance to populate.
     * @returns {module:model/ValidationsValidateResponseBodyRedeemablesItemResult} The populated <code>ValidationsValidateResponseBodyRedeemablesItemResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ValidationsValidateResponseBodyRedeemablesItemResult();

            if (data.hasOwnProperty('discount')) {
                obj['discount'] = ValidationsValidateResponseBodyRedeemablesItemResultDiscount.constructFromObject(data['discount']);
            }
            if (data.hasOwnProperty('bundle')) {
                obj['bundle'] = Bundle.constructFromObject(data['bundle']);
            }
            if (data.hasOwnProperty('gift')) {
                obj['gift'] = ValidationsValidateResponseBodyRedeemablesItemResultGift.constructFromObject(data['gift']);
            }
            if (data.hasOwnProperty('loyalty_card')) {
                obj['loyalty_card'] = ValidationsValidateResponseBodyRedeemablesItemResultLoyaltyCard.constructFromObject(data['loyalty_card']);
            }
            if (data.hasOwnProperty('error')) {
                obj['error'] = Error.constructFromObject(data['error']);
            }
            if (data.hasOwnProperty('details')) {
                obj['details'] = ValidationsValidateResponseBodyRedeemablesItemResultDetails.constructFromObject(data['details']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ValidationsValidateResponseBodyRedeemablesItemResult</code>.
     * @param {object} data The plain JavaScript object bearing properties of interest.
     * @returns {boolean} to indicate whether the JSON data is valid with respect to <code>ValidationsValidateResponseBodyRedeemablesItemResult</code>.
     */
    static validateJSON(data) {
        // validate the optional field `discount`
        if (data['discount']) { // data not null
          ValidationsValidateResponseBodyRedeemablesItemResultDiscount.validateJSON(data['discount']);
        }
        // validate the optional field `bundle`
        if (data['bundle']) { // data not null
          Bundle.validateJSON(data['bundle']);
        }
        // validate the optional field `gift`
        if (data['gift']) { // data not null
          ValidationsValidateResponseBodyRedeemablesItemResultGift.validateJSON(data['gift']);
        }
        // validate the optional field `loyalty_card`
        if (data['loyalty_card']) { // data not null
          ValidationsValidateResponseBodyRedeemablesItemResultLoyaltyCard.validateJSON(data['loyalty_card']);
        }
        // validate the optional field `error`
        if (data['error']) { // data not null
          Error.validateJSON(data['error']);
        }
        // validate the optional field `details`
        if (data['details']) { // data not null
          ValidationsValidateResponseBodyRedeemablesItemResultDetails.validateJSON(data['details']);
        }

        return true;
    }


}



/**
 * @member {module:model/ValidationsValidateResponseBodyRedeemablesItemResultDiscount} 
 */
ValidationsValidateResponseBodyRedeemablesItemResult.prototype['discount'] = undefined;

/**
 * @member {module:model/Bundle} 
 */
ValidationsValidateResponseBodyRedeemablesItemResult.prototype['bundle'] = undefined;

/**
 * @member {module:model/ValidationsValidateResponseBodyRedeemablesItemResultGift} 
 */
ValidationsValidateResponseBodyRedeemablesItemResult.prototype['gift'] = undefined;

/**
 * @member {module:model/ValidationsValidateResponseBodyRedeemablesItemResultLoyaltyCard} 
 */
ValidationsValidateResponseBodyRedeemablesItemResult.prototype['loyalty_card'] = undefined;

/**
 * @member {module:model/Error} 
 */
ValidationsValidateResponseBodyRedeemablesItemResult.prototype['error'] = undefined;

/**
 * @member {module:model/ValidationsValidateResponseBodyRedeemablesItemResultDetails} 
 */
ValidationsValidateResponseBodyRedeemablesItemResult.prototype['details'] = undefined;






export default ValidationsValidateResponseBodyRedeemablesItemResult;

