/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ValidationsRedeemableSkippedResultDetails from './ValidationsRedeemableSkippedResultDetails';
/**
 * The ValidationsRedeemableSkippedResult model module.
 * @module model/ValidationsRedeemableSkippedResult
 * @version 3.0.1
 */
class ValidationsRedeemableSkippedResult {
    /**
     * Constructs a new <code>ValidationsRedeemableSkippedResult</code>.
     * Provides details about the reason why the redeemable is skipped.
     * @alias ValidationsRedeemableSkippedResult
     */
    constructor() { 
        
        ValidationsRedeemableSkippedResult.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ValidationsRedeemableSkippedResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Partial<ValidationsRedeemableSkippedResult>} data The plain JavaScript object bearing properties of interest.
     * @param {ValidationsRedeemableSkippedResult} [obj] Optional instance to populate.
     * @returns {ValidationsRedeemableSkippedResult} The populated <code>ValidationsRedeemableSkippedResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ValidationsRedeemableSkippedResult();

            if (data.hasOwnProperty('details')) {
                obj['details'] = ValidationsRedeemableSkippedResultDetails.constructFromObject(data['details']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ValidationsRedeemableSkippedResult</code>.
     * @param {Partial<ValidationsRedeemableSkippedResult>} data The plain JavaScript object bearing properties of interest.
     * @returns {boolean} to indicate whether the JSON data is valid with respect to <code>ValidationsRedeemableSkippedResult</code>.
     */
    static validateJSON(data) {
        // validate the optional field `details`
        if (data['details']) { // data not null
          ValidationsRedeemableSkippedResultDetails.validateJSON(data['details']);
        }

        return true;
    }


}



/**
    * @type {ValidationsRedeemableSkippedResultDetails | undefined}
    */
ValidationsRedeemableSkippedResult.prototype['details'] = undefined;






export default ValidationsRedeemableSkippedResult;

