/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ParameterFiltersListBin from '../model/ParameterFiltersListBin';
import ParameterOrderListBin from '../model/ParameterOrderListBin';
import TrashBinListResponseBody from '../model/TrashBinListResponseBody';

/**
* Bin service.
* @module api/BinApi
* @version 3.0.1
*/
export default class BinApi {

    /**
    * Constructs a new BinApi. 
    * @alias BinApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the deleteBinEntry operation.
     * @callback deleteBinEntryCallback
     * @param {Error|null} error Error object if failed, null otherwise.
     * @param data This operation does not return a value.
     * @param {Object} [response] Full response object if successful.
     */

    /**
     * Delete Bin Entry
     * Deletes permanently a bin entry with a given ID.The following resources can be moved to the bin and permanently deleted: - campaigns - vouchers - products - SKUs To use this endpoint and delete a given resource type, you must have the following permissions: - vouchers.delete to delete a voucher, - campaigns.delete to delete a campaign, - products.delete to delete a product or SKU.
     * @param {String} binEntryId Provide the unique identifier of the bin entry.
     * @param {deleteBinEntryCallback} [callback] The callback function, accepting three arguments: error, data, response
     * @returns {Promise<( | undefined)>} Depending on whether the `callback` parameter is provided, the promise will resolve with a `` object or with `undefined`.
     */
    deleteBinEntry(binEntryId, callback) {
      let postBody = null;
      // verify the required parameter 'binEntryId' is set

      let pathParams = {
        'binEntryId': binEntryId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['X-App-Id', 'X-App-Token', 'X-Voucherify-OAuth'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/v1/trash-bin/{binEntryId}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the listBinEntries operation.
     * @callback listBinEntriesCallback
     * @param {Error|null} error Error object if failed, null otherwise.
     * @param {TrashBinListResponseBody} [data] The data returned by the service call.
     * @param {Object} [response] Full response object if successful.
     */

    /**
     * List Bin Entries
     * Retrieves a list of resources moved to the bin. The following resources can be moved to the bin: - campaigns - vouchers - products - SKUs To use this endpoint, you must have the following permissions: - vouchers.read - campaigns.read - products.read
     * @param {{
        limit?: Number,
        order?: Exclude<keyof typeof ParameterOrderListBin, "prototype" | "constructFromObject">,
        startingAfterId?: String,
        filters?: ParameterFiltersListBin,
     }} [opts] Optional parameters
     * @param {listBinEntriesCallback} [callback] The callback function, accepting three arguments: error, data, response
     * data is of type: {@link TrashBinListResponseBody}
     * @returns {Promise<(TrashBinListResponseBody | undefined)>} Depending on whether the `callback` parameter is provided, the promise will resolve with a `TrashBinListResponseBody` object or with `undefined`.
     */
    listBinEntries(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'limit': opts['limit'],
        'order': opts['order'],
        'starting_after_id': opts['startingAfterId'],
        'filters': opts['filters']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['X-App-Id', 'X-App-Token', 'X-Voucherify-OAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = TrashBinListResponseBody;
      return this.apiClient.callApi(
        '/v1/trash-bin', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
