/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ValidationsValidateRequestBody from '../model/ValidationsValidateRequestBody';
import ValidationsValidateResponseBody from '../model/ValidationsValidateResponseBody';

/**
* Validations service.
* @module api/ValidationsApi
* @version 3.0.0
*/
export default class ValidationsApi {

    /**
    * Constructs a new ValidationsApi. 
    * @alias module:api/ValidationsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the validateStackedDiscounts operation.
     * @callback module:api/ValidationsApi~validateStackedDiscountsCallback
     * @param {Error|null} error Error object if failed, null otherwise.
     * @param {module:model/ValidationsValidateResponseBody} [data] The data returned by the service call.
     * @param {Object} [response] Full response object if successful.
     */

    /**
     * Validate Stackable Discounts
     * Verify redeemables provided in the request. This method is designed for server side integration which means that it is accessible only through private keys. API keys with a Merchant role cant use this endpoint.
     * @param {module:model/ValidationsValidateRequestBody} validationsValidateRequestBody 
     * @param {module:api/ValidationsApi~validateStackedDiscountsCallback} [callback] The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ValidationsValidateResponseBody}
     */
    validateStackedDiscounts(validationsValidateRequestBody, callback) {
      let postBody = validationsValidateRequestBody;
      // verify the required parameter 'validationsValidateRequestBody' is set

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['X-App-Id', 'X-App-Token', 'X-Voucherify-OAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = ValidationsValidateResponseBody;
      return this.apiClient.callApi(
        '/v1/validations', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
