/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Voucherify);
  }
}(this, function(expect, Voucherify) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Voucherify.LoyaltyMemberLoyaltyCard();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LoyaltyMemberLoyaltyCard', function() {
    it('should create an instance of LoyaltyMemberLoyaltyCard', function() {
      // uncomment below and update the code to test LoyaltyMemberLoyaltyCard
      //var instance = new Voucherify.LoyaltyMemberLoyaltyCard();
      //expect(instance).to.be.a(Voucherify.LoyaltyMemberLoyaltyCard);
    });

    it('should have the property points (base name: "points")', function() {
      // uncomment below and update the code to test the property points
      //var instance = new Voucherify.LoyaltyMemberLoyaltyCard();
      //expect(instance).to.be();
    });

    it('should have the property balance (base name: "balance")', function() {
      // uncomment below and update the code to test the property balance
      //var instance = new Voucherify.LoyaltyMemberLoyaltyCard();
      //expect(instance).to.be();
    });

    it('should have the property nextExpirationDate (base name: "next_expiration_date")', function() {
      // uncomment below and update the code to test the property nextExpirationDate
      //var instance = new Voucherify.LoyaltyMemberLoyaltyCard();
      //expect(instance).to.be();
    });

    it('should have the property nextExpirationPoints (base name: "next_expiration_points")', function() {
      // uncomment below and update the code to test the property nextExpirationPoints
      //var instance = new Voucherify.LoyaltyMemberLoyaltyCard();
      //expect(instance).to.be();
    });

    it('should have the property pendingPoints (base name: "pending_points")', function() {
      // uncomment below and update the code to test the property pendingPoints
      //var instance = new Voucherify.LoyaltyMemberLoyaltyCard();
      //expect(instance).to.be();
    });

    it('should have the property expiredPoints (base name: "expired_points")', function() {
      // uncomment below and update the code to test the property expiredPoints
      //var instance = new Voucherify.LoyaltyMemberLoyaltyCard();
      //expect(instance).to.be();
    });

    it('should have the property subtractedPoints (base name: "subtracted_points")', function() {
      // uncomment below and update the code to test the property subtractedPoints
      //var instance = new Voucherify.LoyaltyMemberLoyaltyCard();
      //expect(instance).to.be();
    });

  });

}));
