/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Voucherify);
  }
}(this, function(expect, Voucherify) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Voucherify.SimpleRedemption();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SimpleRedemption', function() {
    it('should create an instance of SimpleRedemption', function() {
      // uncomment below and update the code to test SimpleRedemption
      //var instance = new Voucherify.SimpleRedemption();
      //expect(instance).to.be.a(Voucherify.SimpleRedemption);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new Voucherify.SimpleRedemption();
      //expect(instance).to.be();
    });

    it('should have the property customerId (base name: "customer_id")', function() {
      // uncomment below and update the code to test the property customerId
      //var instance = new Voucherify.SimpleRedemption();
      //expect(instance).to.be();
    });

    it('should have the property trackingId (base name: "tracking_id")', function() {
      // uncomment below and update the code to test the property trackingId
      //var instance = new Voucherify.SimpleRedemption();
      //expect(instance).to.be();
    });

    it('should have the property date (base name: "date")', function() {
      // uncomment below and update the code to test the property date
      //var instance = new Voucherify.SimpleRedemption();
      //expect(instance).to.be();
    });

    it('should have the property amount (base name: "amount")', function() {
      // uncomment below and update the code to test the property amount
      //var instance = new Voucherify.SimpleRedemption();
      //expect(instance).to.be();
    });

    it('should have the property order (base name: "order")', function() {
      // uncomment below and update the code to test the property order
      //var instance = new Voucherify.SimpleRedemption();
      //expect(instance).to.be();
    });

    it('should have the property reward (base name: "reward")', function() {
      // uncomment below and update the code to test the property reward
      //var instance = new Voucherify.SimpleRedemption();
      //expect(instance).to.be();
    });

    it('should have the property customer (base name: "customer")', function() {
      // uncomment below and update the code to test the property customer
      //var instance = new Voucherify.SimpleRedemption();
      //expect(instance).to.be();
    });

    it('should have the property result (base name: "result")', function() {
      // uncomment below and update the code to test the property result
      //var instance = new Voucherify.SimpleRedemption();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new Voucherify.SimpleRedemption();
      //expect(instance).to.be();
    });

    it('should have the property voucher (base name: "voucher")', function() {
      // uncomment below and update the code to test the property voucher
      //var instance = new Voucherify.SimpleRedemption();
      //expect(instance).to.be();
    });

    it('should have the property promotionTier (base name: "promotion_tier")', function() {
      // uncomment below and update the code to test the property promotionTier
      //var instance = new Voucherify.SimpleRedemption();
      //expect(instance).to.be();
    });

    it('should have the property redemption (base name: "redemption")', function() {
      // uncomment below and update the code to test the property redemption
      //var instance = new Voucherify.SimpleRedemption();
      //expect(instance).to.be();
    });

    it('should have the property metadata (base name: "metadata")', function() {
      // uncomment below and update the code to test the property metadata
      //var instance = new Voucherify.SimpleRedemption();
      //expect(instance).to.be();
    });

    it('should have the property failureCode (base name: "failure_code")', function() {
      // uncomment below and update the code to test the property failureCode
      //var instance = new Voucherify.SimpleRedemption();
      //expect(instance).to.be();
    });

    it('should have the property failureMessage (base name: "failure_message")', function() {
      // uncomment below and update the code to test the property failureMessage
      //var instance = new Voucherify.SimpleRedemption();
      //expect(instance).to.be();
    });

    it('should have the property reason (base name: "reason")', function() {
      // uncomment below and update the code to test the property reason
      //var instance = new Voucherify.SimpleRedemption();
      //expect(instance).to.be();
    });

    it('should have the property channel (base name: "channel")', function() {
      // uncomment below and update the code to test the property channel
      //var instance = new Voucherify.SimpleRedemption();
      //expect(instance).to.be();
    });

    it('should have the property object (base name: "object")', function() {
      // uncomment below and update the code to test the property object
      //var instance = new Voucherify.SimpleRedemption();
      //expect(instance).to.be();
    });

  });

}));
