/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Voucherify);
  }
}(this, function(expect, Voucherify) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Voucherify.ValidationRulesUpdateRequestBody();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ValidationRulesUpdateRequestBody', function() {
    it('should create an instance of ValidationRulesUpdateRequestBody', function() {
      // uncomment below and update the code to test ValidationRulesUpdateRequestBody
      //var instance = new Voucherify.ValidationRulesUpdateRequestBody();
      //expect(instance).to.be.a(Voucherify.ValidationRulesUpdateRequestBody);
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new Voucherify.ValidationRulesUpdateRequestBody();
      //expect(instance).to.be();
    });

    it('should have the property rules (base name: "rules")', function() {
      // uncomment below and update the code to test the property rules
      //var instance = new Voucherify.ValidationRulesUpdateRequestBody();
      //expect(instance).to.be();
    });

    it('should have the property bundleRules (base name: "bundle_rules")', function() {
      // uncomment below and update the code to test the property bundleRules
      //var instance = new Voucherify.ValidationRulesUpdateRequestBody();
      //expect(instance).to.be();
    });

    it('should have the property error (base name: "error")', function() {
      // uncomment below and update the code to test the property error
      //var instance = new Voucherify.ValidationRulesUpdateRequestBody();
      //expect(instance).to.be();
    });

    it('should have the property applicableTo (base name: "applicable_to")', function() {
      // uncomment below and update the code to test the property applicableTo
      //var instance = new Voucherify.ValidationRulesUpdateRequestBody();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new Voucherify.ValidationRulesUpdateRequestBody();
      //expect(instance).to.be();
    });

    it('should have the property contextType (base name: "context_type")', function() {
      // uncomment below and update the code to test the property contextType
      //var instance = new Voucherify.ValidationRulesUpdateRequestBody();
      //expect(instance).to.be();
    });

  });

}));
