/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * OpenAPI spec version: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AccessSettingsAssign } from '../models/AccessSettingsAssign';
import { AccessSettingsUnassign } from '../models/AccessSettingsUnassign';
import { HttpFile } from '../http/http';

/**
* Assigns or unassigns an area or store to the campaign.  **NOTE**: this object can be sent if the Areas and Stores enterprise feature is enabled. Contact [Voucherify Sales](https://www.voucherify.io/contact-sales) to learn more.
*/
export class AccessSettings {
    'assign'?: AccessSettingsAssign | null;
    'unassign'?: AccessSettingsUnassign | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "assign",
            "baseName": "assign",
            "type": "AccessSettingsAssign",
            "format": ""
        },
        {
            "name": "unassign",
            "baseName": "unassign",
            "type": "AccessSettingsUnassign",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AccessSettings.attributeTypeMap;
    }

    public constructor() {
    }
}
