/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * OpenAPI spec version: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CampaignLoyaltyCard } from '../models/CampaignLoyaltyCard';
import { CampaignLoyaltyVoucherRedemption } from '../models/CampaignLoyaltyVoucherRedemption';
import { CodeConfig } from '../models/CodeConfig';
import { HttpFile } from '../http/http';

/**
* Schema model for a discount voucher.
*/
export class CampaignLoyaltyVoucher {
    /**
    * Type of voucher.
    */
    'type'?: CampaignLoyaltyVoucherTypeEnum | null;
    'loyaltyCard': CampaignLoyaltyCard;
    'redemption'?: CampaignLoyaltyVoucherRedemption | null;
    'codeConfig'?: CodeConfig;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "CampaignLoyaltyVoucherTypeEnum",
            "format": ""
        },
        {
            "name": "loyaltyCard",
            "baseName": "loyalty_card",
            "type": "CampaignLoyaltyCard",
            "format": ""
        },
        {
            "name": "redemption",
            "baseName": "redemption",
            "type": "CampaignLoyaltyVoucherRedemption",
            "format": ""
        },
        {
            "name": "codeConfig",
            "baseName": "code_config",
            "type": "CodeConfig",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CampaignLoyaltyVoucher.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum CampaignLoyaltyVoucherTypeEnum {
    LoyaltyCard = 'LOYALTY_CARD'
}

