/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * OpenAPI spec version: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CampaignsTransactionsExportCreateRequestBodyParameters } from '../models/CampaignsTransactionsExportCreateRequestBodyParameters';
import { HttpFile } from '../http/http';

/**
* Request body schema for **POST** `v1/campaigns/{campaignId}/transactions/export`.
*/
export class CampaignsTransactionsExportCreateRequestBody {
    'parameters'?: CampaignsTransactionsExportCreateRequestBodyParameters | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "parameters",
            "baseName": "parameters",
            "type": "CampaignsTransactionsExportCreateRequestBodyParameters",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CampaignsTransactionsExportCreateRequestBody.attributeTypeMap;
    }

    public constructor() {
    }
}
