/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * OpenAPI spec version: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ClientRedemptionsRedeemResponseBodyOrder } from '../models/ClientRedemptionsRedeemResponseBodyOrder';
import { Redemption } from '../models/Redemption';
import { ValidationsRedeemableInapplicable } from '../models/ValidationsRedeemableInapplicable';
import { ValidationsRedeemableSkipped } from '../models/ValidationsRedeemableSkipped';
import { HttpFile } from '../http/http';

/**
* Response body schema for **POST** `v1/redemptions`.
*/
export class ClientRedemptionsRedeemResponseBody {
    'redemptions'?: Array<Redemption> | null;
    'parentRedemption'?: Redemption;
    'order'?: ClientRedemptionsRedeemResponseBodyOrder | null;
    /**
    * Lists validation results of each inapplicable redeemable.
    */
    'inapplicableRedeemables'?: Array<ValidationsRedeemableInapplicable> | null;
    /**
    * Lists validation results of each redeemable. If a redeemable can be applied, the API returns `\"status\": \"APPLICABLE\"`.
    */
    'skippedRedeemables'?: Array<ValidationsRedeemableSkipped> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "redemptions",
            "baseName": "redemptions",
            "type": "Array<Redemption>",
            "format": ""
        },
        {
            "name": "parentRedemption",
            "baseName": "parent_redemption",
            "type": "Redemption",
            "format": ""
        },
        {
            "name": "order",
            "baseName": "order",
            "type": "ClientRedemptionsRedeemResponseBodyOrder",
            "format": ""
        },
        {
            "name": "inapplicableRedeemables",
            "baseName": "inapplicable_redeemables",
            "type": "Array<ValidationsRedeemableInapplicable>",
            "format": ""
        },
        {
            "name": "skippedRedeemables",
            "baseName": "skipped_redeemables",
            "type": "Array<ValidationsRedeemableSkipped>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ClientRedemptionsRedeemResponseBody.attributeTypeMap;
    }

    public constructor() {
    }
}
