/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * OpenAPI spec version: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LocationShapeDistance } from '../models/LocationShapeDistance';
import { LocationShapeGeojson } from '../models/LocationShapeGeojson';
import { HttpFile } from '../http/http';

export class LocationShape {
    'type'?: LocationShapeTypeEnum | null;
    'format'?: LocationShapeFormatEnum | null;
    'distance'?: LocationShapeDistance | null;
    'geojson'?: LocationShapeGeojson | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "LocationShapeTypeEnum",
            "format": ""
        },
        {
            "name": "format",
            "baseName": "format",
            "type": "LocationShapeFormatEnum",
            "format": ""
        },
        {
            "name": "distance",
            "baseName": "distance",
            "type": "LocationShapeDistance",
            "format": ""
        },
        {
            "name": "geojson",
            "baseName": "geojson",
            "type": "LocationShapeGeojson",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LocationShape.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum LocationShapeTypeEnum {
    Circle = 'circle',
    Polygon = 'polygon'
}
export enum LocationShapeFormatEnum {
    Distance = 'distance',
    Geojson = 'geojson'
}

