/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * OpenAPI spec version: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LoyaltiesRewardsUpdateAssignmentResponseBodyParametersLoyalty } from '../models/LoyaltiesRewardsUpdateAssignmentResponseBodyParametersLoyalty';
import { HttpFile } from '../http/http';

/**
* Defines the cost of the reward.
*/
export class LoyaltiesRewardsUpdateAssignmentResponseBodyParameters {
    'loyalty'?: LoyaltiesRewardsUpdateAssignmentResponseBodyParametersLoyalty | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "loyalty",
            "baseName": "loyalty",
            "type": "LoyaltiesRewardsUpdateAssignmentResponseBodyParametersLoyalty",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LoyaltiesRewardsUpdateAssignmentResponseBodyParameters.attributeTypeMap;
    }

    public constructor() {
    }
}
