/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * OpenAPI spec version: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EarningRuleExpirationRules } from '../models/EarningRuleExpirationRules';
import { LoyaltiesEarningRulesEnableResponseBodyCustomEvent } from '../models/LoyaltiesEarningRulesEnableResponseBodyCustomEvent';
import { LoyaltiesEarningRulesEnableResponseBodyLoyalty } from '../models/LoyaltiesEarningRulesEnableResponseBodyLoyalty';
import { LoyaltiesEarningRulesEnableResponseBodyLoyaltyTier } from '../models/LoyaltiesEarningRulesEnableResponseBodyLoyaltyTier';
import { LoyaltiesEarningRulesEnableResponseBodyPendingPoints } from '../models/LoyaltiesEarningRulesEnableResponseBodyPendingPoints';
import { LoyaltiesEarningRulesEnableResponseBodySegment } from '../models/LoyaltiesEarningRulesEnableResponseBodySegment';
import { LoyaltiesEarningRulesEnableResponseBodySource } from '../models/LoyaltiesEarningRulesEnableResponseBodySource';
import { ValidityHours } from '../models/ValidityHours';
import { ValidityTimeframe } from '../models/ValidityTimeframe';
import { HttpFile } from '../http/http';

/**
* Response body schema for **POST** `v1/loyalties/{campaignId}/earning-rules/{earningRuleId}/enable`
*/
export class LoyaltiesEarningRulesEnableResponseBody {
    /**
    * Assigned by the Voucherify API, identifies the earning rule object.
    */
    'id'?: string | null;
    /**
    * Timestamp representing the date and time when the earning rule was created. The value is shown in the ISO 8601 format.
    */
    'createdAt'?: Date | null;
    'loyalty'?: LoyaltiesEarningRulesEnableResponseBodyLoyalty | null;
    'event'?: string;
    'customEvent'?: LoyaltiesEarningRulesEnableResponseBodyCustomEvent | null;
    'segment'?: LoyaltiesEarningRulesEnableResponseBodySegment | null;
    'loyaltyTier'?: LoyaltiesEarningRulesEnableResponseBodyLoyaltyTier | null;
    'pendingPoints'?: LoyaltiesEarningRulesEnableResponseBodyPendingPoints | null;
    'source'?: LoyaltiesEarningRulesEnableResponseBodySource | null;
    /**
    * The type of the object represented by JSON. Default is earning_rule.
    */
    'object'?: LoyaltiesEarningRulesEnableResponseBodyObjectEnum | null;
    /**
    * For internal use by Voucherify.
    */
    'automationId'?: string | null;
    /**
    * Start date defines when the earning rule starts to be active. Activation timestamp is presented in the ISO 8601 format. The earning rule is inactive before this date. If you do not define the start date for an earning rule, it will inherit the campaign start date by default.
    */
    'startDate'?: string | null;
    /**
    * Expiration date defines when the earning rule expires. Expiration timestamp is presented in the ISO 8601 format. The earning rule is inactive after this date. If you do not define the expiration date for an earning rule, it will inherit the campaign expiration date by default.
    */
    'expirationDate'?: string | null;
    'validityTimeframe'?: ValidityTimeframe;
    /**
    * Integer array corresponding to the particular days of the week in which the voucher is valid.  - `0` Sunday - `1` Monday - `2` Tuesday - `3` Wednesday - `4` Thursday - `5` Friday - `6` Saturday
    */
    'validityDayOfWeek'?: Array<LoyaltiesEarningRulesEnableResponseBodyValidityDayOfWeekEnum>;
    'validityHours'?: ValidityHours;
    /**
    * The metadata object stores all custom attributes assigned to the earning rule. A set of key/value pairs that you can attach to an earning rule object. It can be useful for storing additional information about the earning rule in a structured format.
    */
    'metadata'?: any | null;
    'expirationRules'?: EarningRuleExpirationRules;
    /**
    * Timestamp representing the date and time when the earning rule was last updated in ISO 8601 format.
    */
    'updatedAt'?: Date | null;
    /**
    * A flag to toggle the earning rule on or off. You can disable an earning rule even though it\'s within the active period defined by the start_date and expiration_date of the campaign or the earning rule\'s own start_date and expiration_date.
    */
    'active'?: boolean | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "loyalty",
            "baseName": "loyalty",
            "type": "LoyaltiesEarningRulesEnableResponseBodyLoyalty",
            "format": ""
        },
        {
            "name": "event",
            "baseName": "event",
            "type": "string",
            "format": ""
        },
        {
            "name": "customEvent",
            "baseName": "custom_event",
            "type": "LoyaltiesEarningRulesEnableResponseBodyCustomEvent",
            "format": ""
        },
        {
            "name": "segment",
            "baseName": "segment",
            "type": "LoyaltiesEarningRulesEnableResponseBodySegment",
            "format": ""
        },
        {
            "name": "loyaltyTier",
            "baseName": "loyalty_tier",
            "type": "LoyaltiesEarningRulesEnableResponseBodyLoyaltyTier",
            "format": ""
        },
        {
            "name": "pendingPoints",
            "baseName": "pending_points",
            "type": "LoyaltiesEarningRulesEnableResponseBodyPendingPoints",
            "format": ""
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "LoyaltiesEarningRulesEnableResponseBodySource",
            "format": ""
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "LoyaltiesEarningRulesEnableResponseBodyObjectEnum",
            "format": ""
        },
        {
            "name": "automationId",
            "baseName": "automation_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "startDate",
            "baseName": "start_date",
            "type": "string",
            "format": ""
        },
        {
            "name": "expirationDate",
            "baseName": "expiration_date",
            "type": "string",
            "format": ""
        },
        {
            "name": "validityTimeframe",
            "baseName": "validity_timeframe",
            "type": "ValidityTimeframe",
            "format": ""
        },
        {
            "name": "validityDayOfWeek",
            "baseName": "validity_day_of_week",
            "type": "Array<LoyaltiesEarningRulesEnableResponseBodyValidityDayOfWeekEnum>",
            "format": ""
        },
        {
            "name": "validityHours",
            "baseName": "validity_hours",
            "type": "ValidityHours",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "any",
            "format": ""
        },
        {
            "name": "expirationRules",
            "baseName": "expiration_rules",
            "type": "EarningRuleExpirationRules",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "active",
            "baseName": "active",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LoyaltiesEarningRulesEnableResponseBody.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum LoyaltiesEarningRulesEnableResponseBodyObjectEnum {
    EarningRule = 'earning_rule'
}
export enum LoyaltiesEarningRulesEnableResponseBodyValidityDayOfWeekEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3,
    NUMBER_4 = 4,
    NUMBER_5 = 5,
    NUMBER_6 = 6
}

