/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * OpenAPI spec version: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Defines the configuration for pending points. Pending points can be used only with the `order.paid` event. Pass `null` to remove pending points from the earning rule.
*/
export class LoyaltiesEarningRulesUpdateRequestBodyPendingPoints {
    /**
    * Defines the type of the period during which the points are in the pending state. Currently, only `DAY` value is accepted.
    */
    'periodType'?: LoyaltiesEarningRulesUpdateRequestBodyPendingPointsPeriodTypeEnum | null;
    /**
    * Defines for how long the points are in the pending state. The minimum value is 1, maximum is 90.
    */
    'periodValue'?: number | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "periodType",
            "baseName": "period_type",
            "type": "LoyaltiesEarningRulesUpdateRequestBodyPendingPointsPeriodTypeEnum",
            "format": ""
        },
        {
            "name": "periodValue",
            "baseName": "period_value",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LoyaltiesEarningRulesUpdateRequestBodyPendingPoints.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum LoyaltiesEarningRulesUpdateRequestBodyPendingPointsPeriodTypeEnum {
    Day = 'DAY'
}

