/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * OpenAPI spec version: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Defines the equivalent points value of the reward.
*/
export class LoyaltiesRewardAssignmentsGetResponseBodyParametersLoyalty {
    /**
    * The number of points required to redeem the reward.
    */
    'points'?: number | null;
    /**
    * Determines if the reward is redeemed automatically when the customer reaches the sufficient number of points to redeem it. Value `true` means that the automatic reward redemption is active. Only one reward can be set to be redeemed automatically in a loyalty campaign, i.e. only one can have the value `true`.
    */
    'autoRedeem'?: boolean | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "points",
            "baseName": "points",
            "type": "number",
            "format": ""
        },
        {
            "name": "autoRedeem",
            "baseName": "auto_redeem",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LoyaltiesRewardAssignmentsGetResponseBodyParametersLoyalty.attributeTypeMap;
    }

    public constructor() {
    }
}
