/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * OpenAPI spec version: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LoyaltiesEarningRulesGetResponseBodyLoyaltyOrderItemsAmount } from '../models/LoyaltiesEarningRulesGetResponseBodyLoyaltyOrderItemsAmount';
import { LoyaltiesEarningRulesGetResponseBodyLoyaltyOrderItemsQuantity } from '../models/LoyaltiesEarningRulesGetResponseBodyLoyaltyOrderItemsQuantity';
import { LoyaltiesEarningRulesGetResponseBodyLoyaltyOrderItemsSubtotalAmount } from '../models/LoyaltiesEarningRulesGetResponseBodyLoyaltyOrderItemsSubtotalAmount';
import { HttpFile } from '../http/http';

export class LoyaltiesEarningRulesGetResponseBodyLoyaltyOrderItems {
    'quantity'?: LoyaltiesEarningRulesGetResponseBodyLoyaltyOrderItemsQuantity | null;
    'amount'?: LoyaltiesEarningRulesGetResponseBodyLoyaltyOrderItemsAmount | null;
    'subtotalAmount'?: LoyaltiesEarningRulesGetResponseBodyLoyaltyOrderItemsSubtotalAmount | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "LoyaltiesEarningRulesGetResponseBodyLoyaltyOrderItemsQuantity",
            "format": ""
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "LoyaltiesEarningRulesGetResponseBodyLoyaltyOrderItemsAmount",
            "format": ""
        },
        {
            "name": "subtotalAmount",
            "baseName": "subtotal_amount",
            "type": "LoyaltiesEarningRulesGetResponseBodyLoyaltyOrderItemsSubtotalAmount",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LoyaltiesEarningRulesGetResponseBodyLoyaltyOrderItems.attributeTypeMap;
    }

    public constructor() {
    }
}
