/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * OpenAPI spec version: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MemberActivity } from '../models/MemberActivity';
import { HttpFile } from '../http/http';

/**
* Response body schema for retrieving member activity.
*/
export class LoyaltiesMemberActivityListResponseBody {
    /**
    * The type of the object represented by JSON. This object stores information about member activities in a dictionary.
    */
    'object'?: LoyaltiesMemberActivityListResponseBodyObjectEnum | null;
    /**
    * Identifies the name of the attribute that contains the array of member activity objects.
    */
    'dataRef'?: string | null;
    /**
    * Array of member activity objects.
    */
    'data'?: Array<MemberActivity> | null;
    /**
    * As query results are always limited (by the limit parameter), the `has_more` flag indicates if there are more records for given filter parameters. This lets you know if you can run another request with a `starting_after_id` query or a different limit to get more records returned in the results.
    */
    'hasMore'?: boolean | null;
    /**
    * Returns an ID that can be used to return another page of results. Use the event ID in the `starting_after_id` query parameter to display another page of the results starting after the event with that ID.
    */
    'moreStartingAfter'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "object",
            "baseName": "object",
            "type": "LoyaltiesMemberActivityListResponseBodyObjectEnum",
            "format": ""
        },
        {
            "name": "dataRef",
            "baseName": "data_ref",
            "type": "string",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<MemberActivity>",
            "format": ""
        },
        {
            "name": "hasMore",
            "baseName": "has_more",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "moreStartingAfter",
            "baseName": "more_starting_after",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LoyaltiesMemberActivityListResponseBody.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum LoyaltiesMemberActivityListResponseBodyObjectEnum {
    List = 'list'
}

