/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * OpenAPI spec version: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ManagementProjectApiUsageNotifications } from '../models/ManagementProjectApiUsageNotifications';
import { ManagementProjectDefaultCodeConfig } from '../models/ManagementProjectDefaultCodeConfig';
import { ManagementProjectLimits } from '../models/ManagementProjectLimits';
import { ManagementProjectWebhooksCalloutNotifications } from '../models/ManagementProjectWebhooksCalloutNotifications';
import { HttpFile } from '../http/http';

export class ManagementProject {
    /**
    * Unique identifier of the project.
    */
    'id'?: string | null;
    /**
    * The name of the project.
    */
    'name'?: string | null;
    /**
    * A user-defined description of the project, e.g. its purpose, scope, region.
    */
    'description'?: string | null;
    /**
    * The time zone in which the project is established. It can be in the GMT format or in accordance with IANA time zone database.
    */
    'timezone'?: string | null;
    /**
    * The currency used in the project. It is equal to a 3-letter ISO 4217 code.
    */
    'currency'?: string | null;
    /**
    * The country dial code for the project. It is equal to an ITU country code.
    */
    'dialCode'?: string | null;
    /**
    * The webhook version used in the project.
    */
    'webhookVersion'?: ManagementProjectWebhookVersionEnum | null;
    /**
    * An array of URL addresses that allow client requests.
    */
    'clientTrustedDomains'?: Array<string> | null;
    /**
    * Enables client-side redemption.
    */
    'clientRedeemEnabled'?: boolean | null;
    /**
    * Enables client-side publication.
    */
    'clientPublishEnabled'?: boolean | null;
    /**
    * Enables client-side listing of vouchers.
    */
    'clientListVouchersEnabled'?: boolean | null;
    /**
    * Enables client-side creation of customers.
    */
    'clientCreateCustomerEnabled'?: boolean | null;
    /**
    * Enables client-side events for loyalty and referral programs.
    */
    'clientLoyaltyEventsEnabled'?: boolean | null;
    /**
    * Enables client-side setting of voucher expiration date.
    */
    'clientSetVoucherExpirationDateEnabled'?: boolean | null;
    'webhooksCalloutNotifications'?: ManagementProjectWebhooksCalloutNotifications | null;
    'apiUsageNotifications'?: ManagementProjectApiUsageNotifications | null;
    /**
    * The identifier of the cluster where the project will be created.
    */
    'clusterId'?: string | null;
    /**
    * Determines if the vouchers in the project will be: - case sensitive - if `true`, `C0dE-cfV` is **not** equal to `c0de-cfv`), - case insensitive - if `false`, `C0dE-cfV` is equal to `c0de-cfv`.
    */
    'caseSensitiveCodes'?: boolean | null;
    /**
    * The API version used in the project. Currently, the default and only value is `v2018-08-01`.
    */
    'apiVersion'?: ManagementProjectApiVersionEnum | null;
    /**
    * Determines if the project is a sandbox project.
    */
    'isSandbox'?: boolean | null;
    /**
    * Webhook token used for authentication.
    */
    'webhookToken'?: string | null;
    'defaultCodeConfig'?: ManagementProjectDefaultCodeConfig | null;
    'limits'?: ManagementProjectLimits | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "timezone",
            "baseName": "timezone",
            "type": "string",
            "format": ""
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string",
            "format": ""
        },
        {
            "name": "dialCode",
            "baseName": "dial_code",
            "type": "string",
            "format": ""
        },
        {
            "name": "webhookVersion",
            "baseName": "webhook_version",
            "type": "ManagementProjectWebhookVersionEnum",
            "format": ""
        },
        {
            "name": "clientTrustedDomains",
            "baseName": "client_trusted_domains",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "clientRedeemEnabled",
            "baseName": "client_redeem_enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "clientPublishEnabled",
            "baseName": "client_publish_enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "clientListVouchersEnabled",
            "baseName": "client_list_vouchers_enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "clientCreateCustomerEnabled",
            "baseName": "client_create_customer_enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "clientLoyaltyEventsEnabled",
            "baseName": "client_loyalty_events_enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "clientSetVoucherExpirationDateEnabled",
            "baseName": "client_set_voucher_expiration_date_enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "webhooksCalloutNotifications",
            "baseName": "webhooks_callout_notifications",
            "type": "ManagementProjectWebhooksCalloutNotifications",
            "format": ""
        },
        {
            "name": "apiUsageNotifications",
            "baseName": "api_usage_notifications",
            "type": "ManagementProjectApiUsageNotifications",
            "format": ""
        },
        {
            "name": "clusterId",
            "baseName": "cluster_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "caseSensitiveCodes",
            "baseName": "case_sensitive_codes",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "apiVersion",
            "baseName": "api_version",
            "type": "ManagementProjectApiVersionEnum",
            "format": ""
        },
        {
            "name": "isSandbox",
            "baseName": "is_sandbox",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "webhookToken",
            "baseName": "webhook_token",
            "type": "string",
            "format": ""
        },
        {
            "name": "defaultCodeConfig",
            "baseName": "default_code_config",
            "type": "ManagementProjectDefaultCodeConfig",
            "format": ""
        },
        {
            "name": "limits",
            "baseName": "limits",
            "type": "ManagementProjectLimits",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ManagementProject.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum ManagementProjectWebhookVersionEnum {
    V20240101 = 'v2024-01-01'
}
export enum ManagementProjectApiVersionEnum {
    V20180801 = 'v2018-08-01'
}

