/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * OpenAPI spec version: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Junction } from '../models/Junction';
import { ParameterFiltersListBinId } from '../models/ParameterFiltersListBinId';
import { ParameterFiltersListBinResourceId } from '../models/ParameterFiltersListBinResourceId';
import { ParameterFiltersListBinResourceName } from '../models/ParameterFiltersListBinResourceName';
import { ParameterFiltersListBinResourceType } from '../models/ParameterFiltersListBinResourceType';
import { HttpFile } from '../http/http';

export class ParameterFiltersListBin {
    'junction'?: Junction;
    'id'?: ParameterFiltersListBinId | null;
    'resourceType'?: ParameterFiltersListBinResourceType | null;
    'resourceName'?: ParameterFiltersListBinResourceName | null;
    'resourceId'?: ParameterFiltersListBinResourceId | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "junction",
            "baseName": "junction",
            "type": "Junction",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "ParameterFiltersListBinId",
            "format": ""
        },
        {
            "name": "resourceType",
            "baseName": "resource_type",
            "type": "ParameterFiltersListBinResourceType",
            "format": ""
        },
        {
            "name": "resourceName",
            "baseName": "resource_name",
            "type": "ParameterFiltersListBinResourceName",
            "format": ""
        },
        {
            "name": "resourceId",
            "baseName": "resource_id",
            "type": "ParameterFiltersListBinResourceId",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ParameterFiltersListBin.attributeTypeMap;
    }

    public constructor() {
    }
}


