/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * OpenAPI spec version: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PromotionsStacksCreateRequestBodyTiers } from '../models/PromotionsStacksCreateRequestBodyTiers';
import { HttpFile } from '../http/http';

/**
* Request body schema for **POST** `v1/promotions/{campaignId}/stacks`.
*/
export class PromotionsStacksCreateRequestBody {
    /**
    * Promotion stack name.
    */
    'name'?: string | null;
    'tiers'?: PromotionsStacksCreateRequestBodyTiers | null;
    /**
    * Promotion stack category ID.
    */
    'categoryId'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "tiers",
            "baseName": "tiers",
            "type": "PromotionsStacksCreateRequestBodyTiers",
            "format": ""
        },
        {
            "name": "categoryId",
            "baseName": "category_id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PromotionsStacksCreateRequestBody.attributeTypeMap;
    }

    public constructor() {
    }
}
