/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * OpenAPI spec version: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PromotionTierCreateParamsAction } from '../models/PromotionTierCreateParamsAction';
import { ValidityHours } from '../models/ValidityHours';
import { ValidityTimeframe } from '../models/ValidityTimeframe';
import { HttpFile } from '../http/http';

/**
* This is an object representing a promotion tier create params. Promotion tiers are always assigned to a campaign and cannot be used standalone.
*/
export class PromotionTierCreateParams {
    /**
    * Name of the promotion tier.
    */
    'name'?: string | null;
    /**
    * Text to be displayed to your customers on your website.
    */
    'banner'?: string | null;
    'action'?: PromotionTierCreateParamsAction | null;
    /**
    * The metadata object stores all custom attributes assigned to the promotion tier. A set of key/value pairs that you can attach to a promotion tier object. It can be useful for storing additional information about the promotion tier in a structured format.
    */
    'metadata'?: any | null;
    /**
    * Array containing the ID of the validation rule associated with the promotion tier.
    */
    'validationRules'?: Array<string> | null;
    /**
    * A flag to toggle the promotion tier on or off. You can disable a promotion tier even though it\'s within the active period defined by the `start_date` and `expiration_date`.    - `true` indicates an *active* promotion tier - `false` indicates an *inactive* promotion tier
    */
    'active'?: boolean | null;
    /**
    * The promotions hierarchy defines the order in which the discounts from different tiers will be applied to a customer\'s order. If a customer qualifies for discounts from more than one tier, discounts will be applied in the order defined in the hierarchy.
    */
    'hierarchy'?: number | null;
    /**
    * Activation timestamp defines when the promotion tier starts to be active in ISO 8601 format. Promotion tier is *inactive before* this date. 
    */
    'startDate'?: Date | null;
    /**
    * Activation timestamp defines when the promotion tier expires in ISO 8601 format. Promotion tier is *inactive after* this date. 
    */
    'expirationDate'?: Date | null;
    'validityTimeframe'?: ValidityTimeframe;
    /**
    * Integer array corresponding to the particular days of the week in which the voucher is valid.  - `0` Sunday - `1` Monday - `2` Tuesday - `3` Wednesday - `4` Thursday - `5` Friday - `6` Saturday
    */
    'validityDayOfWeek'?: Array<PromotionTierCreateParamsValidityDayOfWeekEnum>;
    'validityHours'?: ValidityHours;
    /**
    * Assign category to the promotion tier.
    */
    'category'?: string | null;
    /**
    * Instead of using the category name, you can alternatively assign a new category to a promotion tier using a unique category ID, i.e. `cat_0c9da30e7116ba6bba`.
    */
    'categoryId'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "banner",
            "baseName": "banner",
            "type": "string",
            "format": ""
        },
        {
            "name": "action",
            "baseName": "action",
            "type": "PromotionTierCreateParamsAction",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "any",
            "format": ""
        },
        {
            "name": "validationRules",
            "baseName": "validation_rules",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "active",
            "baseName": "active",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "hierarchy",
            "baseName": "hierarchy",
            "type": "number",
            "format": ""
        },
        {
            "name": "startDate",
            "baseName": "start_date",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "expirationDate",
            "baseName": "expiration_date",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "validityTimeframe",
            "baseName": "validity_timeframe",
            "type": "ValidityTimeframe",
            "format": ""
        },
        {
            "name": "validityDayOfWeek",
            "baseName": "validity_day_of_week",
            "type": "Array<PromotionTierCreateParamsValidityDayOfWeekEnum>",
            "format": ""
        },
        {
            "name": "validityHours",
            "baseName": "validity_hours",
            "type": "ValidityHours",
            "format": ""
        },
        {
            "name": "category",
            "baseName": "category",
            "type": "string",
            "format": ""
        },
        {
            "name": "categoryId",
            "baseName": "category_id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PromotionTierCreateParams.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum PromotionTierCreateParamsValidityDayOfWeekEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3,
    NUMBER_4 = 4,
    NUMBER_5 = 5,
    NUMBER_6 = 6
}

