/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * OpenAPI spec version: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Contains the number of points returned to the loyalty card in the reward redemption rollback. It is expressed as a negative integer.
*/
export class RedemptionsRollbackCreateResponseBodyLoyaltyCard {
    /**
    * Number of points being returned to the loyalty card for the reward redemption rollback. It is expressed as a negative integer.
    */
    'points'?: number | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "points",
            "baseName": "points",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RedemptionsRollbackCreateResponseBodyLoyaltyCard.attributeTypeMap;
    }

    public constructor() {
    }
}
