/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * OpenAPI spec version: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RedemptionEntryChannel } from '../models/RedemptionEntryChannel';
import { RedemptionEntryCustomer } from '../models/RedemptionEntryCustomer';
import { RedemptionEntryGift } from '../models/RedemptionEntryGift';
import { RedemptionEntryLoyaltyCard } from '../models/RedemptionEntryLoyaltyCard';
import { RedemptionEntryOrder } from '../models/RedemptionEntryOrder';
import { RedemptionEntryPromotionTier } from '../models/RedemptionEntryPromotionTier';
import { RedemptionEntryRelatedRedemptions } from '../models/RedemptionEntryRelatedRedemptions';
import { RedemptionEntrySession } from '../models/RedemptionEntrySession';
import { RedemptionEntryVoucher } from '../models/RedemptionEntryVoucher';
import { RedemptionRewardResult } from '../models/RedemptionRewardResult';
import { HttpFile } from '../http/http';

export class RedemptionEntry {
    'id'?: string | null;
    'object'?: RedemptionEntryObjectEnum | null;
    /**
    * Timestamp representing the date and time when the object was created. The value is shown in the ISO 8601 format.
    */
    'date'?: Date | null;
    /**
    * Unique customer ID of the redeeming customer.
    */
    'customerId'?: string | null;
    /**
    * Hashed customer source ID.
    */
    'trackingId'?: string | null;
    /**
    * The metadata object stores all custom attributes assigned to the redemption.
    */
    'metadata'?: any | null;
    /**
    * For gift cards, this is a positive integer in the smallest currency unit (e.g. 100 cents for $1.00) representing the number of redeemed credits. For loyalty cards, this is the number of loyalty points used in the transaction. and For gift cards, this represents the number of the credits restored to the card in the rolledback redemption. The number is a negative integer in the smallest currency unit, e.g. -100 cents for $1.00 added back to the card. For loyalty cards, this represents the number of loyalty points restored to the card in the rolledback redemption. The number is a negative integer.
    */
    'amount'?: number | null;
    /**
    * Unique redemption ID of the parent redemption.
    */
    'redemption'?: string | null;
    /**
    * Redemption result.
    */
    'result'?: RedemptionEntryResultEnum | null;
    'status'?: RedemptionEntryStatusEnum | null;
    'session'?: RedemptionEntrySession | null;
    'relatedRedemptions'?: RedemptionEntryRelatedRedemptions | null;
    /**
    * If the result is `FAILURE`, this parameter will provide a generic reason as to why the redemption failed.
    */
    'failureCode'?: string | null;
    /**
    * If the result is `FAILURE`, this parameter will provide a more expanded reason as to why the redemption failed.
    */
    'failureMessage'?: string | null;
    'order'?: RedemptionEntryOrder | null;
    'channel'?: RedemptionEntryChannel | null;
    'customer'?: RedemptionEntryCustomer | null;
    /**
    * Defines the related object.
    */
    'relatedObjectType'?: RedemptionEntryRelatedObjectTypeEnum | null;
    'relatedObjectId'?: string | null;
    'promotionTier'?: RedemptionEntryPromotionTier | null;
    'reward'?: RedemptionRewardResult;
    'gift'?: RedemptionEntryGift | null;
    'loyaltyCard'?: RedemptionEntryLoyaltyCard | null;
    'voucher'?: RedemptionEntryVoucher | null;
    /**
    * System generated cause for the redemption being invalid in the context of the provided parameters.
    */
    'reason'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "RedemptionEntryObjectEnum",
            "format": ""
        },
        {
            "name": "date",
            "baseName": "date",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "customerId",
            "baseName": "customer_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "trackingId",
            "baseName": "tracking_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "any",
            "format": ""
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number",
            "format": ""
        },
        {
            "name": "redemption",
            "baseName": "redemption",
            "type": "string",
            "format": ""
        },
        {
            "name": "result",
            "baseName": "result",
            "type": "RedemptionEntryResultEnum",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "RedemptionEntryStatusEnum",
            "format": ""
        },
        {
            "name": "session",
            "baseName": "session",
            "type": "RedemptionEntrySession",
            "format": ""
        },
        {
            "name": "relatedRedemptions",
            "baseName": "related_redemptions",
            "type": "RedemptionEntryRelatedRedemptions",
            "format": ""
        },
        {
            "name": "failureCode",
            "baseName": "failure_code",
            "type": "string",
            "format": ""
        },
        {
            "name": "failureMessage",
            "baseName": "failure_message",
            "type": "string",
            "format": ""
        },
        {
            "name": "order",
            "baseName": "order",
            "type": "RedemptionEntryOrder",
            "format": ""
        },
        {
            "name": "channel",
            "baseName": "channel",
            "type": "RedemptionEntryChannel",
            "format": ""
        },
        {
            "name": "customer",
            "baseName": "customer",
            "type": "RedemptionEntryCustomer",
            "format": ""
        },
        {
            "name": "relatedObjectType",
            "baseName": "related_object_type",
            "type": "RedemptionEntryRelatedObjectTypeEnum",
            "format": ""
        },
        {
            "name": "relatedObjectId",
            "baseName": "related_object_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "promotionTier",
            "baseName": "promotion_tier",
            "type": "RedemptionEntryPromotionTier",
            "format": ""
        },
        {
            "name": "reward",
            "baseName": "reward",
            "type": "RedemptionRewardResult",
            "format": ""
        },
        {
            "name": "gift",
            "baseName": "gift",
            "type": "RedemptionEntryGift",
            "format": ""
        },
        {
            "name": "loyaltyCard",
            "baseName": "loyalty_card",
            "type": "RedemptionEntryLoyaltyCard",
            "format": ""
        },
        {
            "name": "voucher",
            "baseName": "voucher",
            "type": "RedemptionEntryVoucher",
            "format": ""
        },
        {
            "name": "reason",
            "baseName": "reason",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RedemptionEntry.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum RedemptionEntryObjectEnum {
    Redemption = 'redemption',
    RedemptionRollback = 'redemption_rollback'
}
export enum RedemptionEntryResultEnum {
    Success = 'SUCCESS',
    Failure = 'FAILURE'
}
export enum RedemptionEntryStatusEnum {
    Succeeded = 'SUCCEEDED',
    Failed = 'FAILED',
    RolledBack = 'ROLLED_BACK'
}
export enum RedemptionEntryRelatedObjectTypeEnum {
    Voucher = 'voucher',
    PromotionTier = 'promotion_tier',
    Redemption = 'redemption'
}

