/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * OpenAPI spec version: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RedemptionsListResponseBodyRedemptionsItemRelatedRedemptionsRedemptionsItem } from '../models/RedemptionsListResponseBodyRedemptionsItemRelatedRedemptionsRedemptionsItem';
import { RedemptionsListResponseBodyRedemptionsItemRelatedRedemptionsRollbacksItem } from '../models/RedemptionsListResponseBodyRedemptionsItemRelatedRedemptionsRollbacksItem';
import { HttpFile } from '../http/http';

export class RedemptionsListResponseBodyRedemptionsItemRelatedRedemptions {
    'rollbacks'?: Array<RedemptionsListResponseBodyRedemptionsItemRelatedRedemptionsRollbacksItem> | null;
    'redemptions'?: Array<RedemptionsListResponseBodyRedemptionsItemRelatedRedemptionsRedemptionsItem> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "rollbacks",
            "baseName": "rollbacks",
            "type": "Array<RedemptionsListResponseBodyRedemptionsItemRelatedRedemptionsRollbacksItem>",
            "format": ""
        },
        {
            "name": "redemptions",
            "baseName": "redemptions",
            "type": "Array<RedemptionsListResponseBodyRedemptionsItemRelatedRedemptionsRedemptionsItem>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RedemptionsListResponseBodyRedemptionsItemRelatedRedemptions.attributeTypeMap;
    }

    public constructor() {
    }
}
