/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * OpenAPI spec version: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LoyaltiesTransferPoints } from '../models/LoyaltiesTransferPoints';
import { HttpFile } from '../http/http';

/**
* Redeemable loyalty card object response
*/
export class RedeemableLoyaltyCard {
    /**
    * Total number of points added to the loyalty card over its lifespan.
    */
    'points'?: number | null;
    /**
    * Points available for reward redemption. This is calculated as follows: `balance` = `points` - `expired_points` - `subtracted_points` - `redemption.redeemed_points`.
    */
    'balance'?: number | null;
    /**
    * The cash equivalent of the points defined in the points_ratio property.
    */
    'exchangeRatio'?: number | null;
    /**
    * The number of loyalty points that will map to the predefined cash amount defined by the exchange_ratio property.
    */
    'pointsRatio'?: number | null;
    'transfers'?: Array<LoyaltiesTransferPoints> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "points",
            "baseName": "points",
            "type": "number",
            "format": ""
        },
        {
            "name": "balance",
            "baseName": "balance",
            "type": "number",
            "format": ""
        },
        {
            "name": "exchangeRatio",
            "baseName": "exchange_ratio",
            "type": "number",
            "format": ""
        },
        {
            "name": "pointsRatio",
            "baseName": "points_ratio",
            "type": "number",
            "format": ""
        },
        {
            "name": "transfers",
            "baseName": "transfers",
            "type": "Array<LoyaltiesTransferPoints>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RedeemableLoyaltyCard.attributeTypeMap;
    }

    public constructor() {
    }
}
