/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * OpenAPI spec version: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Objects stores information about the campaign related to the reward.
*/
export class RewardTypeCampaign {
    /**
    * Unique campaign ID, assigned by Voucherify.
    */
    'id'?: string | null;
    /**
    * The number of points to be added to a loyalty card or the amount to be added to the current balance on the gift card.  For gift cards, the value is multiplied by 100 to precisely represent 2 decimal places. For example, $100 amount is written as 10000.
    */
    'balance'?: number | null;
    /**
    * Campaign type.
    */
    'type'?: RewardTypeCampaignTypeEnum | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "balance",
            "baseName": "balance",
            "type": "number",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "RewardTypeCampaignTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RewardTypeCampaign.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum RewardTypeCampaignTypeEnum {
    DiscountCoupons = 'DISCOUNT_COUPONS',
    GiftVouchers = 'GIFT_VOUCHERS',
    LoyaltyProgram = 'LOYALTY_PROGRAM'
}

