/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * OpenAPI spec version: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CampaignLoyaltyCard } from '../models/CampaignLoyaltyCard';
import { CodeConfig } from '../models/CodeConfig';
import { Discount } from '../models/Discount';
import { Gift } from '../models/Gift';
import { SimpleCampaignVoucherRedemption } from '../models/SimpleCampaignVoucherRedemption';
import { HttpFile } from '../http/http';

/**
* Simplified campaign voucher data.
*/
export class SimpleCampaignVoucher {
    /**
    * Type of the voucher.
    */
    'type'?: SimpleCampaignVoucherTypeEnum | null;
    'discount'?: Discount;
    'gift'?: Gift;
    'loyaltyCard'?: CampaignLoyaltyCard;
    'redemption'?: SimpleCampaignVoucherRedemption | null;
    'codeConfig': CodeConfig;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "SimpleCampaignVoucherTypeEnum",
            "format": ""
        },
        {
            "name": "discount",
            "baseName": "discount",
            "type": "Discount",
            "format": ""
        },
        {
            "name": "gift",
            "baseName": "gift",
            "type": "Gift",
            "format": ""
        },
        {
            "name": "loyaltyCard",
            "baseName": "loyalty_card",
            "type": "CampaignLoyaltyCard",
            "format": ""
        },
        {
            "name": "redemption",
            "baseName": "redemption",
            "type": "SimpleCampaignVoucherRedemption",
            "format": ""
        },
        {
            "name": "codeConfig",
            "baseName": "code_config",
            "type": "CodeConfig",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SimpleCampaignVoucher.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum SimpleCampaignVoucherTypeEnum {
    DiscountVoucher = 'DISCOUNT_VOUCHER',
    LoyaltyCard = 'LOYALTY_CARD',
    GiftVoucher = 'GIFT_VOUCHER'
}

