/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * OpenAPI spec version: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Category } from '../models/Category';
import { ReferralProgram } from '../models/ReferralProgram';
import { SimpleCampaignVoucher } from '../models/SimpleCampaignVoucher';
import { HttpFile } from '../http/http';

/**
* Simplified campaign data.
*/
export class SimpleCampaign {
    /**
    * Campaign ID.
    */
    'id'?: string | null;
    /**
    * Campaign name.
    */
    'name'?: string | null;
    /**
    * Type of campaign.
    */
    'campaignType'?: string | null;
    /**
    * Defines whether the campaign can be updated with new vouchers after campaign creation or if the campaign consists of generic (standalone) vouchers.  - `AUTO_UPDATE`: the campaign is dynamic, i.e. vouchers will generate based on set criteria -  `STATIC`: vouchers need to be manually published - `STANDALONE`: campaign for single vouchers
    */
    'type'?: SimpleCampaignTypeEnum | null;
    /**
    * Flag indicating whether this voucher is a referral code; `true` for campaign type `REFERRAL_PROGRAM`.
    */
    'isReferralCode'?: boolean | null;
    'voucher'?: SimpleCampaignVoucher;
    'referralProgram'?: ReferralProgram;
    /**
    * Indicates whether customers will be able to auto-join the campaign if any earning rule is fulfilled.
    */
    'autoJoin'?: boolean | null;
    /**
    * If this value is set to `true`, customers will be able to join the campaign only once. It is always `false` for generic (standalone) vouchers campaigns and it cannot be changed in them. It is always `true` for loyalty campaigns and it cannot be changed in them.
    */
    'joinOnce'?: boolean | null;
    /**
    * Indicates whether the campaign is active.
    */
    'active'?: boolean | null;
    /**
    * The unique category ID that this campaign belongs to.
    */
    'categoryId'?: string | null;
    /**
    * Unique category name.
    */
    'category'?: string | null;
    /**
    * Contains details about the category.
    */
    'categories'?: Array<Category> | null;
    /**
    * A set of custom key/value pairs that you can attach to a campaign. The metadata object stores all custom attributes assigned to the campaign.
    */
    'metadata'?: any | null;
    /**
    * Activation timestamp defines when the campaign starts to be active in ISO 8601 format. Campaign is inactive *before* this date. 
    */
    'startDate'?: Date | null;
    /**
    * Expiration timestamp defines when the campaign expires in ISO 8601 format.  Campaign is inactive *after* this date.
    */
    'expirationDate'?: Date | null;
    /**
    * An optional field to keep extra textual information about the campaign such as a campaign description and details.
    */
    'description'?: string | null;
    /**
    * Timestamp representing the date and time when the campaign was created. The value is shown in the ISO 8601 format.
    */
    'createdAt'?: Date | null;
    /**
    * Timestamp representing the date and time when the campaign was updated in the ISO 8601 format.
    */
    'updatedAt'?: Date | null;
    /**
    * The type of the object represented by JSON. This object stores information about the campaign.
    */
    'object'?: SimpleCampaignObjectEnum | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "campaignType",
            "baseName": "campaign_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "SimpleCampaignTypeEnum",
            "format": ""
        },
        {
            "name": "isReferralCode",
            "baseName": "is_referral_code",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "voucher",
            "baseName": "voucher",
            "type": "SimpleCampaignVoucher",
            "format": ""
        },
        {
            "name": "referralProgram",
            "baseName": "referral_program",
            "type": "ReferralProgram",
            "format": ""
        },
        {
            "name": "autoJoin",
            "baseName": "auto_join",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "joinOnce",
            "baseName": "join_once",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "active",
            "baseName": "active",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "categoryId",
            "baseName": "category_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "category",
            "baseName": "category",
            "type": "string",
            "format": ""
        },
        {
            "name": "categories",
            "baseName": "categories",
            "type": "Array<Category>",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "any",
            "format": ""
        },
        {
            "name": "startDate",
            "baseName": "start_date",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "expirationDate",
            "baseName": "expiration_date",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "SimpleCampaignObjectEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SimpleCampaign.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum SimpleCampaignTypeEnum {
    AutoUpdate = 'AUTO_UPDATE',
    Static = 'STATIC',
    Standalone = 'STANDALONE'
}
export enum SimpleCampaignObjectEnum {
    Campaign = 'campaign'
}

