/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * OpenAPI spec version: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Provides details about the reason why the redeemable is inapplicable.
*/
export class ValidationsRedeemableInapplicableResultDetails {
    /**
    * Generic message from the `message` string shown in the `error` object or the message configured in a validation rule.
    */
    'message'?: string | null;
    /**
    * Generic message from the `key` string shown in the `error` object.
    */
    'key'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "key",
            "baseName": "key",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ValidationsRedeemableInapplicableResultDetails.attributeTypeMap;
    }

    public constructor() {
    }
}
