/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * OpenAPI spec version: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Bundle } from '../models/Bundle';
import { ValidationsValidateResponseBodyRedeemablesItemResultDetails } from '../models/ValidationsValidateResponseBodyRedeemablesItemResultDetails';
import { ValidationsValidateResponseBodyRedeemablesItemResultDiscount } from '../models/ValidationsValidateResponseBodyRedeemablesItemResultDiscount';
import { ValidationsValidateResponseBodyRedeemablesItemResultGift } from '../models/ValidationsValidateResponseBodyRedeemablesItemResultGift';
import { ValidationsValidateResponseBodyRedeemablesItemResultLoyaltyCard } from '../models/ValidationsValidateResponseBodyRedeemablesItemResultLoyaltyCard';
import { HttpFile } from '../http/http';

export class ValidationsValidateResponseBodyRedeemablesItemResult {
    'discount'?: ValidationsValidateResponseBodyRedeemablesItemResultDiscount;
    'bundle'?: Bundle;
    'gift'?: ValidationsValidateResponseBodyRedeemablesItemResultGift | null;
    'loyaltyCard'?: ValidationsValidateResponseBodyRedeemablesItemResultLoyaltyCard | null;
    'error'?: Error;
    'details'?: ValidationsValidateResponseBodyRedeemablesItemResultDetails;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "discount",
            "baseName": "discount",
            "type": "ValidationsValidateResponseBodyRedeemablesItemResultDiscount",
            "format": ""
        },
        {
            "name": "bundle",
            "baseName": "bundle",
            "type": "Bundle",
            "format": ""
        },
        {
            "name": "gift",
            "baseName": "gift",
            "type": "ValidationsValidateResponseBodyRedeemablesItemResultGift",
            "format": ""
        },
        {
            "name": "loyaltyCard",
            "baseName": "loyalty_card",
            "type": "ValidationsValidateResponseBodyRedeemablesItemResultLoyaltyCard",
            "format": ""
        },
        {
            "name": "error",
            "baseName": "error",
            "type": "Error",
            "format": ""
        },
        {
            "name": "details",
            "baseName": "details",
            "type": "ValidationsValidateResponseBodyRedeemablesItemResultDetails",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ValidationsValidateResponseBodyRedeemablesItemResult.attributeTypeMap;
    }

    public constructor() {
    }
}
