/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * OpenAPI spec version: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ValidationsValidateResponseBodyRedeemablesItemOrderCustomer {
    /**
    * A unique identifier of an existing customer.
    */
    'id'?: string | null;
    /**
    * The type of the object represented by JSON.
    */
    'object'?: ValidationsValidateResponseBodyRedeemablesItemOrderCustomerObjectEnum | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "ValidationsValidateResponseBodyRedeemablesItemOrderCustomerObjectEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ValidationsValidateResponseBodyRedeemablesItemOrderCustomer.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum ValidationsValidateResponseBodyRedeemablesItemOrderCustomerObjectEnum {
    Customer = 'customer'
}

