/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * OpenAPI spec version: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VoucherTransactionsExportParameters } from '../models/VoucherTransactionsExportParameters';
import { HttpFile } from '../http/http';

/**
* Request body schema for **POST** `v1/vouchers/transactions/export`.
*/
export class VouchersTransactionsExportCreateRequestBody {
    'parameters'?: VoucherTransactionsExportParameters;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "parameters",
            "baseName": "parameters",
            "type": "VoucherTransactionsExportParameters",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return VouchersTransactionsExportCreateRequestBody.attributeTypeMap;
    }

    public constructor() {
    }
}
