/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * OpenAPI spec version: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CodeConfig } from '../models/CodeConfig';
import { Discount } from '../models/Discount';
import { Gift } from '../models/Gift';
import { SimpleLoyaltyCard } from '../models/SimpleLoyaltyCard';
import { ValidityHours } from '../models/ValidityHours';
import { ValidityTimeframe } from '../models/ValidityTimeframe';
import { VouchersCreateRequestBodyRedemption } from '../models/VouchersCreateRequestBodyRedemption';
import { HttpFile } from '../http/http';

export class VouchersCreateRequestBody {
    /**
    * Code that identifies a voucher. The pattern can use all the letters of the English alphabet, Arabic numerals, and special characters. Pass this attribute in the request body to create a distinct code. Otherwise, either use the `code_config` object to set the rules that the Voucherify API will use to create a random code, or don\'t pass any code and Voucherify will generate a random code.
    */
    'code'?: string | null;
    /**
    * Identifies the voucher\'s parent campaign using a unique campaign name.
    */
    'campaign'?: string | null;
    /**
    * Identifies the voucher\'s parent campaign using a unique campaign ID assigned by the Voucherify API.
    */
    'campaignId'?: string | null;
    /**
    * The name of the category that this voucher belongs to. Useful when listing vouchers with the [List Vouchers](/api-reference/vouchers/list-vouchers) endpoint.
    */
    'category'?: string | null;
    /**
    * Unique identifier assigned by Voucherify to the name of the category that this voucher belongs to. Useful when listing vouchers with the [List Vouchers](/api-reference/vouchers/list-vouchers) endpoint.
    */
    'categoryId'?: string | null;
    /**
    * Start date defines when the code starts to be active. Activation timestamp is presented in the ISO 8601 format. Voucher is *inactive before* this date.
    */
    'startDate'?: Date | null;
    /**
    * Expiration date defines when the code expires. Expiration timestamp is presented in the ISO 8601 format.  Voucher is *inactive after* this date.
    */
    'expirationDate'?: Date | null;
    'validityTimeframe'?: ValidityTimeframe;
    /**
    * Integer array corresponding to the particular days of the week in which the voucher is valid.  - `0` Sunday - `1` Monday - `2` Tuesday - `3` Wednesday - `4` Thursday - `5` Friday - `6` Saturday
    */
    'validityDayOfWeek'?: Array<VouchersCreateRequestBodyValidityDayOfWeekEnum>;
    'validityHours'?: ValidityHours;
    /**
    * A flag to toggle the voucher on or off. You can disable a voucher even though it\'s within the active period defined by the `start_date` and `expiration_date`.    - `true` indicates an *active* voucher - `false` indicates an *inactive* voucher
    */
    'active'?: boolean | null;
    /**
    * An optional field to keep any extra textual information about the code such as a code description and details.
    */
    'additionalInfo'?: string | null;
    /**
    * The metadata object stores all custom attributes assigned to the code. A set of key/value pairs that you can attach to a voucher object. It can be useful for storing additional information about the voucher in a structured format.
    */
    'metadata'?: any | null;
    /**
    * Array containing the ID of the validation rule associated with the voucher.
    */
    'validationRules'?: Array<string> | null;
    'redemption'?: VouchersCreateRequestBodyRedemption | null;
    'type'?: VouchersCreateRequestBodyTypeEnum | null;
    'loyaltyCard'?: SimpleLoyaltyCard;
    'codeConfig'?: CodeConfig;
    'gift'?: Gift;
    'discount'?: Discount;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "string",
            "format": ""
        },
        {
            "name": "campaign",
            "baseName": "campaign",
            "type": "string",
            "format": ""
        },
        {
            "name": "campaignId",
            "baseName": "campaign_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "category",
            "baseName": "category",
            "type": "string",
            "format": ""
        },
        {
            "name": "categoryId",
            "baseName": "category_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "startDate",
            "baseName": "start_date",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "expirationDate",
            "baseName": "expiration_date",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "validityTimeframe",
            "baseName": "validity_timeframe",
            "type": "ValidityTimeframe",
            "format": ""
        },
        {
            "name": "validityDayOfWeek",
            "baseName": "validity_day_of_week",
            "type": "Array<VouchersCreateRequestBodyValidityDayOfWeekEnum>",
            "format": ""
        },
        {
            "name": "validityHours",
            "baseName": "validity_hours",
            "type": "ValidityHours",
            "format": ""
        },
        {
            "name": "active",
            "baseName": "active",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "additionalInfo",
            "baseName": "additional_info",
            "type": "string",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "any",
            "format": ""
        },
        {
            "name": "validationRules",
            "baseName": "validation_rules",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "redemption",
            "baseName": "redemption",
            "type": "VouchersCreateRequestBodyRedemption",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "VouchersCreateRequestBodyTypeEnum",
            "format": ""
        },
        {
            "name": "loyaltyCard",
            "baseName": "loyalty_card",
            "type": "SimpleLoyaltyCard",
            "format": ""
        },
        {
            "name": "codeConfig",
            "baseName": "code_config",
            "type": "CodeConfig",
            "format": ""
        },
        {
            "name": "gift",
            "baseName": "gift",
            "type": "Gift",
            "format": ""
        },
        {
            "name": "discount",
            "baseName": "discount",
            "type": "Discount",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return VouchersCreateRequestBody.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum VouchersCreateRequestBodyValidityDayOfWeekEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3,
    NUMBER_4 = 4,
    NUMBER_5 = 5,
    NUMBER_6 = 6
}
export enum VouchersCreateRequestBodyTypeEnum {
    LoyaltyCard = 'LOYALTY_CARD',
    GiftVoucher = 'GIFT_VOUCHER',
    DiscountVoucher = 'DISCOUNT_VOUCHER'
}

