/**
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * OpenAPI spec version: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Response body schema for **POST** `v1/vouchers/bulk/async`.
*/
export class VouchersUpdateInBulkResponseBody {
    /**
    * The ID of the scheduled asynchronous action.
    */
    'asyncActionId'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "asyncActionId",
            "baseName": "async_action_id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return VouchersUpdateInBulkResponseBody.attributeTypeMap;
    }

    public constructor() {
    }
}
